### ISSUE TITLE
Add EML 2.2.0 Support in search catalog and dataset landing pages

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacatui#1055]
Metacat is getting EML 2.2.0 support (https://github.com/NCEAS/metacat/issues/1239) which affects MetacatUI in the following ways:

- [x] We can turn the Annotation filter back on in search so people can search for semantic annotations
- [x] We can render Markdown properly on landing pages with the `MarkdownView`
- [x] We need to build an interactive widget on dataset landing pages for Semantic Annotations. See https://github.com/NCEAS/metacatui/issues/943

**Comment by amoeba** [comment]
PR at https://github.com/NCEAS/metacatui/pull/1034. Demo at neutral-cat.nceas.ucsb.edu.

**Comment by amoeba** [comment]
Decisions left:

- [ ] Which release this is going into? It looks like 2.6 is closed so the earliest this can go in is 2.7.
- [ ] Which themes do we enable the annotation filter on?

**Comment by amoeba** [comment]
Re:

> Which release this is going into? It looks like 2.6 is closed so the earliest this can go in is 2.7.

@laurenwalker where would this fit in terms of release versions?

>  Which themes do we enable the annotation filter on?

We decided on this call that we'll keep the annotation filter turned off in version control and enable it on a per-deployment basis.

**Comment by laurenwalker** [comment]
Hey Bryce, I merged your PR into the dev-2.7 branch for a 2.7.0 release. This will be the only feature in that release, so as soon as EML 2.2.0 is officially released, we can tag 2.7.0.

I tried testing your changes with neutral-cat but was getting server errors

**Comment by amoeba** [comment]
Thanks! Sorry for the errors, I nuked Metacat on neutral-cat before I left the office last night in order to test something else and didn't bring it back up yet.

**Comment by amoeba** [comment]
Okay, I set up https://mn-demo-8.test.dataone.org/ as a "stable" place with EML 2.2.0 support for both Metacat and MetacatUI.

**Comment by laurenwalker** [comment]
I tested these changes and they look really good. I turned the annotation search filter on in the arctic theme. 

I made some minor design changes, just to keep the designs of the annotations more consistent with the rest of the app's look. I changed the annotation popover so that it displays on hover, rather than click. I also changed the annotation icon to the check mark inside a "certificate" icon, like we talked about during a couple meetings. That required a change to the eml-attribute.xsl stylesheet in Metacat on dev-2.11. 

I updated mn-demo-8 with all those changes so anyone can take a look. Here's also some screenshots:

### Before
<img width="1116" alt="Screen Shot 2019-08-23 at 4 37 44 PM" src="https://user-images.githubusercontent.com/6643222/63625497-7396c280-c5c5-11e9-963c-1033946845ae.png">

### After 
![Screen Shot 2019-08-23 at 3 45 45 PM](https://user-images.githubusercontent.com/6643222/63625498-7396c280-c5c5-11e9-8673-3e5a7a9c2bc5.png)

**Comment by amoeba** [comment]
Looks way better, thanks @laurenwalker 	!
