### ISSUE TITLE
Summary Statistics is confusing and seems to be buggy

### ISSUE THREAD

**Issue by vchendrix** [NCEAS/metacatui#1068]
We just upgraded to Metacat 2.6.4 and this seems to be a new issue.  If I go to ESS-DIVE and view a data package then view the summary statistics for the repository.  The summary statistics are filtered for that single data packge (I think).  It only shows 2MB of content and 0 data files. The downloads, updates and time period reports seem to be unaffected. If I click away and to the main search page and then back the summary statistics are still filtered by a single data package.

I expect the Data > Summary page to always return the full statistics of the entire repository and this is not the case

**Comment by daagarwal** [comment]
This happens just if I go to the data search page and then go to summary statistics (I do not have to have filtered at all. It happens every time. Then if I reload the summary statistics, they show up propoerly. Since we are using this page to show our program managers the stats about our repository, this is a problem.
Deb

**Comment by laurenwalker** [comment]
I was able to reproduce this bug. Thanks for reporting it, I'll get this fixed for the next release.

**Comment by daagarwal** [comment]
Thanks Lauren!
