### ISSUE TITLE
Complete the Methods section of the Editor

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#11]
- [x] Display a methods section in the editor form
- [x] Display a sampling section in the editor form
- [x] Update the methods and sampling in the EML model when the UI is changed
- [x] Update or add the methods and sampling in the EML doc during serialize()

**Comment by amoeba** [comment]
Just a note for me: We're supporting repeatable methods steps and repeatable sampling steps.

**Comment by amoeba** [comment]
Got a basic implementation done with repeatable method steps and one sampling step and one study extent description (same as in the registry right now). Todos are:

- [ ] More testing on existing docs
- [ ] More testing on docs with complex EMLText structure
- [ ] Extend code to support repeatable sampling steps (easy)

**Comment by csjx** [comment]
Heya @amoeba - FYI https://github.com/NCEAS/metacatui/commit/0a0c470c7f25dac818a071dfa710b2c632071187#commitcomment-21867604

**Comment by amoeba** [comment]
Should be fixed, @csjx. Sorry about that!

**Comment by csjx** [comment]
Ah, cool - thanks! No worries at all. That was quick!

**Comment by amoeba** [comment]
As an addendum, after our discussion last week about what to do when the user has only filled out some of the required parts of a sub-tree prior to clicking Save, I went ahead an implemented my idea of how that might work in this module. If a user has entered text in any _one_ sub-element of `methods` of either (1) a method step, (2) a sampling description, or (3) a study extent description, any of the remaining two sub-elements not filled in will be filled in with placeholder text in order to make the entire `methods` sub-element schema valid.

**Comment by laurenwalker** [comment]
I think the only thing missing in the methods section now are remove buttons next to each method step. I'll work on that today.
