### ISSUE TITLE
File names don't get set when Objects are non-public-read

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacatui#112]
It seems like files that are not public-readable don't download with the SysMeta `fileName`s set as their file name and instead download with their PID as their filename. This is a problem because (1) colons have special meaning for file names on Mac OS and (2) the user surely wants the file to have its file name.

To reproduce:

- Create a simple package, like with`arcticdatautils::create_dummy_package(mn)`
- Remove public read access from all objects
- Browse to the dataset landing page in MetacatUI
- Click "Download"
- Observe the file is downloaded with the PID as its file name

**Comment by amoeba** [comment]
So I notice that clicking the Download button triggers `SolrResult.downloadWithCredientials` which is odd. At the time I click it, the model its trying to download has essentially no attributes set, including fileName, and even includes a 'type' attribute of 'data' which is odd considering I clicked download on a metadata object.

**Comment by amoeba** [comment]
Even weirder, if I download, I get nonsensical file names that look like UUIDs. Is this because MetacatUI is generating new UUIDs for these?

**Comment by amoeba** [comment]
If I'm logged out, `modelToDownload.get('fileName')` is set (correctly) and is null if I am logged in.

**Comment by amoeba** [comment]
Hey @laurenwalker I'm a bit stumped. Any ideas?

**Comment by mbjones** [comment]
There is probably an underlying fix needed on Metacat as well as any client-side changes.  On metacat, we should be setting the filename in the headers to the value stored in system metadata if we have it, and if not, then fall back to our alternates like the identifier.  There should be very little reason for the client to need to intervene in any of this.  

The code block for this is `MetacatHandler.generateOutputName()` on line 1390 of MetacatHandler.java.  I suggest that the logic in this block should be modified to use the SystemMetadata filename.  The code that calls that also sets the mime type as well in a less-than-stellar way, and it should probably default to the system metadata value as well.  `DocumentImpl.getDocname()` and `DocumentImpl.getDocumentInfo()` are also involved and provide the base name if it is set when reading the EML document.

**Comment by csjx** [comment]
Yes, agreed. When `generateOutputName()` was written, we had no `SystemMetadata`, so nows a good time to bring that method up to date.

**Comment by csjx** [comment]
I've modified Metacat for this, see https://projects.ecoinformatics.org/ecoinfo/issues/7187. I'll talk with Jing about testing it.  We can also review the code that sets the MIME type, but I think that needs some discussion - it's not that straight forward because we don't have definitive MIME type information.

**Comment by amoeba** [comment]
Wait, what happened here in this thread? I thought this was a MetacatUI bug w/r/t using the HTML5 Blob API to send the data to the user when they click Download.

**Comment by mbjones** [comment]
It is, but its also falling back to the default metacat behavior of using
the pid for a filename.  So, fixing the underlying default behavior on file
naming means the client won't have to set the filename if one is present in
sysmeta.

Matt

**Comment by amoeba** [comment]
ahhh, thanks

As a note, it's using the wrong PID when it falls back to the PID.

**Comment by laurenwalker** [comment]
Hi guys, I've taken a look at this and fixed the issue. Bryce is correct, this is related to MetacatUI. Downloads happen in MetacatUI by retrieving the object through an AJAX request, which can send tokens as a header (regular downloads ala clicking a link cannot send tokens with the download request). 

When this AJAX request is completed and MetacatUI receives a response with a "Content-Disposition" header, we now retrieve the filename and use that. Otherwise, the filename in the system metadata is used as a backup. (Or the title of the metadata document as a further backup, lastly, relying on the pid).
 
Here is the commit: https://github.com/NCEAS/metacatui/commit/6d74689dfc9dd9560f8abf51268928d083e89a10

**Comment by csjx** [comment]
Okay, well, the Metacat fix is a bonus then - it should be setting the filename from the SystemMetadata now too, so MetacatUI shouldn't be getting a generated `Content-Disposition` value if it's present in the SystemMetadata.  So I think we're covered on both ends.
