### ISSUE TITLE
Can we let the Download button just download from /object when the user isn't logged in?

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacatui#114]
While looking at #112, it looked like the Download button in the PackageTableView always sends the downloaded file via an XHR. In looking at the code that the Download button triggers (often/always? `SolrResult.downloadWithCredentials`, I see this code:

```js
downloadWithCredentials: function(){
			//if(this.get("isPublic")) return;
```

I see that line got commented out in https://github.com/NCEAS/metacatui/commit/75ab50f6d3bc363c2e38c9eca98a8db232c45e85. I figure there was a previous conversation that elicited this change. Was there a reason for this?

I'm wondering two things:

- Is it really the case that clicking Download always sends the file to the user via XHR?
- If the above is true, does the app have to do this or can it just make the button work like a normal link?

If there's no reason we can't let the user download as normal, maybe we could do something like this:

```patch
diff --git a/metacatui/src/main/webapp/js/views/PackageTableView.js b/metacatui/src/main/webapp/js/views/PackageTableView.js
index b1afa0a..2422aec 100644
--- a/metacatui/src/main/webapp/js/views/PackageTableView.js
+++ b/metacatui/src/main/webapp/js/views/PackageTableView.js
@@ -403,7 +403,11 @@ define(['jquery', 'underscore', 'backbone', 'models/PackageModel', 'text!templat
                        return tr;
                },

-               download: function(e){
+               download: function(e){
+                       if(!appUserModel.get("loggedIn")) {
+                               return;
+                       }
```

As an side, when reading the [MDN docs for URL.createObjectURL](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL) I found this note:

> Each time you call createObjectURL(), a new object URL is created, even if you've already created one for the same object. Each of these must be released by calling URL.revokeObjectURL() when you no longer need them. Browsers will release these automatically when the document is unloaded; however, for optimal performance and memory usage, if there are safe times when you can explicitly unload them, you should do so.

Should we be doing that?

**Comment by laurenwalker** [comment]
I was getting lots of feedback that we needed better messaging when a large download has started. See: https://github.com/NCEAS/metacatui/issues/32. 

The solution was to disable and show a "Downloading..." text on the download button while the XHR is pending, and then when the download is complete, change the text to "Complete" briefly before reseting the button back to normal.

But when the user is logged out and we aren't using AJAX to download the object, this functionality isn't possible because the user is simply clicking on the link to download the object.

I don't like the idea of having the download button work differently when you're signed in vs. signed out. So I just made it the same no matter what.

Open to hearing options on how to make the experience the same when logged in vs logged out AND using a simple download link when logged out.

**Comment by amoeba** [comment]
The linked Issue #32 discusses the Download All button which takes an unknown amount of time to begin sending the request so putting a band-aid over that with an XHR is a great interim solution. For the Download button on individual files, when not using an XHR request but just a link to the `/object` URL, the download request should start to send fairly quickly and in constant time. (Maybe I should test that assumption). 

I'm all for uniformity of behavior though, so I take your point on that. As far as I can tell, browser support for the APIs involved in downloading via XHR are widely supported and the behavior seems like it's not just buffering the Object in memory. 

Since I'm lobbying for the behavior to be different, I'll close this for now. Thanks for walking me through the background.

**Comment by laurenwalker** [comment]
The issue is the same for Download All and Download. THe Download All certainly takes longer and has a higher need for giving the user feedback, but especially for large objects that take a few seconds to download, we still need to show the user a download has started.

Just let me know if anyone comes up with any better solutions - I'm certainly open to it
