### ISSUE TITLE
`creator` and `contact` elements are not being written

### ISSUE THREAD

**Issue by jeanetteclark** [NCEAS/metacatui#1203]
As far as I can tell, trying to submit any kind of dataset results in invalid EML because the creator and contact elements are not being written for some reason. Tested on dev.nceas, bug originally found on Arctic production

`Error inserting or updating document: urn:uuid:a039df10-e9cb-44ae-82c9-1a85f9e5daa3 since <?xml version="1.0"?><error>cvc-complex-type.2.4.a: Invalid content was found starting with element 'abstract'. One of '{title, creator}' is expected.</error>`

**Comment by dmullen17** [comment]
I was able to successfully submit a dummy package to production, edit the title, and add a data file (3 different metadata versions).  Final version is here: https://arcticdata.io/catalog/view/urn:uuid:dd54cff4-75e0-4c7f-a09f-b1c90ef09083. 

The original bug was found by Seth Robinson when he tried to add a data file to this submission: https://arcticdata.io/catalog/view/urn:uuid:51a93676-d46d-4519-83fb-008da7b83cde.  Something to note: there isn't a resource map because I cloned that metadata file for him to edit.
