### ISSUE TITLE
Add AccessPolicyView to EML editor

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1231]

**Comment by laurenwalker** [comment]
I did some testing today and everything looks good except for one bug that should be resolved before we release.

When I opened an EML object into the editor that does not have a resource map, or when I start a new submission, the Share button is disabled and it says I don't have changePermission permission.

![Screen Shot 2021-02-23 at 5.08.50 PM.png](https://images.zenhubusercontent.com/5d152e12c27d0c306f021863/ba78162c-ef17-47d0-88b5-b49f95a8e930)

**Comment by amoeba** [comment]
Great catch, @laurenwalker, thanks. I'm not sure I saw that situation in testing but I'll take a look. Might have a question or two.

**Comment by amoeba** [comment]
Fixed in https://github.com/NCEAS/metacatui/commit/2b4115de573728c546127da5429c137b0b7f0e47. See the commit message for more detail. One thing was needing to set `isNew` on the new DataPackage manually and the other was something I had skipped over: When we have a new package and haven't saved it ever, the AccessPolicyView should just update the model on the client and close instead of attempting to call updateSystemMetadata (which would fail).

This is ready for review again. Thanks @laurenwalker !

**Comment by laurenwalker** [comment]
Thanks Bryce, have you tested that that change doesn't affect any other behavior in the editor? I can see it being problematic is set `isNew` to `true` for all DataPackage collections, because not all packages are new. (e.g. opening up an existing package in the editor)

**Comment by amoeba** [comment]
I've done a few tests but haven't had time to make sure I know why the change won't break things. i can take a look next Wednesday if not earlier. I tested:

- Enter editor new
- Edit existing package, immediately hit Save w/o making any changes
- Edit existing package, make changes in AccessPolicyView

**Comment by amoeba** [comment]
Yeah, I don't like this change yet, even though it seems to work. I expected isNew() to get eval to false after an existing package is fetched from the server but it's not doing that.

**Comment by laurenwalker** [comment]
We typically have set the `synced` property to `true` to indicate that the model has been fetched or to "fake" that models have been fetched when they don't exist on the server yet. I'd try that. If you're stuck, let me know and I can play around with it too

**Comment by amoeba** [comment]
Oh okay. Interesting. I'll let you know, thanks.

**Comment by laurenwalker** [comment]
Any update on this? I'd like to get the release out next week.

**Comment by amoeba** [comment]
No, sorry for the holdup. I'll have a look before the end of the day today and update here.

**Comment by amoeba** [comment]
This looks much better now. It turns out using DataONEObject.get("isNew") is problematic anyway so I've:

1. Reverted my change setting `isNew` to `true` by default when we create a new package model. Now this patch won't change any of that behavior.
2. Changed the Share button's display logic from using `.get("isNew")` to `.isNew()` which works. In all my testing `.isNew()` seems to work as expected and returns `true` when an object has never been persisted and `false` otherwise.

I've tested that things work with:

1. Editing a metadata file that isn't already associated with a resource map
2. Editing a metadata file that _is_ already associated with a resource map
2. Create a brand new submission

Thanks for the review and the skepticism about setting `isNew` manually. This ready for you again.
