### ISSUE TITLE
Provide direct link downloads for non-private data

### ISSUE THREAD

**Issue by jeanetteclark** [NCEAS/metacatui#1271]
partially transcribed/pieced together from a slack conversation with Chris and Lauren

We could probably make downloading large files via the download button faster by determining if an object is private first, and downloading the faster way if not. This would allow a user to see the download progress in your browser like you usually do for files.

Because you currently can't see the download progress, users sometimes think the download button isn't doing anything when it takes a long time.

**Comment by amoeba** [comment]
This would be awesome, been on my wish list for years.

**Comment by amoeba** [comment]
Past discussion for reference: https://github.com/NCEAS/metacatui/issues/114

**Comment by laurenwalker** [comment]
This is causing immediate issues with downloads from search.dataone.org, since not all MNs support CORS. MNs should support CORS from search.dataone.org, but just in case they don't, MetacatUI should try it's best to download objects directly (rather than via XHR) instead of serving an error. Bumping this up to an immediate patch release.
