### ISSUE TITLE
Add icons next to each header in the StatsView

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1290]

**Comment by rushirajnenuji** [comment]
Hey @laurenwalker  - keeping this ticket in the review column because I'm not sure if I've used the right icons.
These are the changes that I've made:
- Metadata Assessment: icon-dashboard
- Latest Updates: icon-refresh
- File formats: icon-file

Also, I've removed some extra padding to make sure that the section headers align with each other. It would be great if you could let me know whether this looks okay. Thanks!

**Comment by laurenwalker** [comment]
Sounds great! Let's just change the latest update icon to icon-cloud-upload, which is the opposite of the download icon, so I think it fits better.

Thanks!

**Comment by rushirajnenuji** [comment]
Updated stats view template to include icons for the missing sections:
- Metadata Assessment: icon-dashboard
- Latest Updates: icon-cloud-upload
- File formats: icon-file
