### ISSUE TITLE
Add more file format short names

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1296]
e.g. EML 2.2.0 is still displayed as the full namespace URI

**Comment by rushirajnenuji** [comment]
Hi @laurenwalker  - We were seeing issues because 2.1.1 and 2.2.0 have different format of namespace URIs for different versions of EML. i.e. for v2.1.1 the URI is `eml://ecoinformatics.org/eml-2.1.1` while for v2.2.0 it is `https://eml.ecoinformatics.org/eml-2.2.0`.

I've updated the checks for `2.2.0`, but I was wondering if we need to consider additional short names for other formats? I see a few (`http://ns.dataone.org/metadata/schema/onedcx/v1.0`, `http://www.isotc211.org/2005/gmd-noaa`, `http://www.isotc211.org/2005/gmd-pangaea`) on the CN profile.

**Comment by laurenwalker** [comment]
Hi @rushirajnenuji, thanks for fixing this issue. Yes, let's go ahead and add short names to as many metadata formats as possible. (At least the ones that display on the DataONE profile at search.dataone.org/profile).

Since this isn't a feature release, but is just a minor fix, things like this can be committed directly to the dev branch.

**Comment by rushirajnenuji** [comment]
Added required file format types in commits: https://github.com/NCEAS/metacatui/commit/b72299cb233ee9507ff15228155ee10dcde47090 and https://github.com/NCEAS/metacatui/commit/786f678af218ec51ac3f79595b8a0db0e0ec66d1
