### ISSUE TITLE
Prov editor doesn't check for unsupported metadata formats

### ISSUE THREAD

**Issue by gothub** [NCEAS/metacatui#1326]
For the dataset https://arcticdata.io/catalog/view/doi:10.18739/A2251FK3B, the 'Edit' button is grayed out with the rollover msg "This metadata format is not editable". This metadata is EML 2.2.0.

However, for this dataset, then prov icons are displayed. The prov portion of the editor needs to perform the same checks as are being performed for the 'Edit' button and not display if the metadata is deemed not editable.

For such a dataset, the editor essentially hangs after the user attempts to add/edit prov.

**Comment by laurenwalker** [comment]
HI @gothub - I posted this on Slack, but I'll copy to here to, for future reference. I don't think this is an issue. The prov editor should work with any metadata format, since it just updated the resource map.

I'm going to close this issue unless you see a flaw in my reasoning. Let me know. Thanks!

**Comment by gothub** [comment]
I haven't tested this yet, but @jeanetteclark reported that when she tried to use the prov editor with the above dataset, MetacatUI froze. This may be related to #1325.

**Comment by laurenwalker** [comment]
Yep, I think the bug Jeanette experienced is #1325, which I'm currently working on. I don't think it has anything to do with the specific issue raised in this ticket though (about metadata formats). Thanks!
