### ISSUE TITLE
Make "dataset added manually" unchecked by default

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1330]
It seems like this feature is more confusing than helpful, particularly since datasets cannot be added manually from the UI yet. Once we add that feature, we may want to add this filter by default again.

**Comment by laurenwalker** [comment]
This is a bit more complicated than I originally thought it would be, since the isPartOf filter is created and added to the filter list upon Portal initialization. Going to remove this from the milestone since it was fairly low priority anyway, and should make more sense once we redesign the EditCollectionView (#1175)

**Comment by robyngit** [comment]
I think this issue is obsolete since there is no longer a "dataset added manually" checkbox in the newly implemented query builder (the isPartOf filter is now hidden by default). We also have [another issue](https://github.com/NCEAS/metacatui/issues/1560) that deals with how we should display this filter.
