### ISSUE TITLE
Route MN profiles to new /portals URL

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1350]

**Comment by rushirajnenuji** [comment]
Hi @laurenwalker

- The routing to /portals/{nodeId} is complete. Right now Portal View is the top view for repository profile views for this endpoint: `/portals`.

Here's the flow:

Case 1: when someone goes to `/profile/{nodeId}`
  - User view is the top view
  - the router does not know if this profile is a `user` or a `node` profile. 
  - And it passes the username to UserView to render profile
  - UserView detects this is a node profile. Performs the following step/s (as outlined in the epic #1261 ):
    - User view creates a Portal Model specific to node profiles
    - User View creates Portal View object and calls the Portal View render
      - (Behind the scenes): Portal View uses this updated portal model object to perform the render
    - Update the `/profile/{nodeId}` path to `/portals/{nodeId}`; but we do not trigger the navigate. Commit: https://github.com/NCEAS/metacatui/commit/339c647c1ac678a05f7477da1d52eba1b1b888a5 
  
Case 2: when someone goes to `/portals/{nodeId}`
  - Portal View is the top view
  - the router passes the `nodeId` label to Portal View
  - Portal View detects this as a node profile. Performs the following step/s:
    - Creates a node-specific Portal Model
    - Performs the render

I just wanted to know your thoughts if we should keep it clean and trigger the navigate when we update the paths?

TODO:
Once we have the user profiles migrated to the Portal View (#1336, #1337), we can update the router so that for the render of `/profile/{nodeId}` and `/profile/{user}` we directly follow Case 2 and eliminate the use of UserView.

**Comment by laurenwalker** [comment]
Thanks Rushi! I reviewed your changes and I agree with this:

> I just wanted to know your thoughts if we should keep it clean and trigger the navigate when we update the paths?

Since I was already looking at the code, I just went ahead and made the change while I was in there. So I think this ticket is good to go, however, could you do some wuick testing on different browsers, especially IE/Edge? If that all looks good to go, then let's close this ticket. Yay!

Thank you!

**Comment by rushirajnenuji** [comment]
Thank you for reviewing Lauren! I'll get started with testing this on Windows.
