### ISSUE TITLE
"More info" link missing from large datasets

### ISSUE THREAD

**Issue by laijasmine** [NCEAS/metacatui#1390]
For datasets with hundreds of files, the section "Files in this dataset" appears to be missing the "more info" link that connects it to the corresponding metadata below.

For example this can be seen in this dataset (with >300 files):
https://doi.org/10.18739/A2SN4C

Others with similarly large values can be found through the ICECAPS portal:
https://arcticdata.io/catalog/portals/icecaps/Data

**Comment by amoeba** [comment]
Thanks for the report @laijasmine, and for the links to an example showing the  behavior. We don't show the More Info link when the package has more than 150 members:

https://github.com/NCEAS/metacatui/blob/8dd897b607a15d848f7516becceca396359b9d2c/src/js/views/PackageTableView.js#L53:L53

This limit appears to have been put in for performance reasons. If I disable the limit, expanding the package table to show all items takes 12 seconds. 

<img width="799" alt="Screen Shot 2020-05-15 at 3 24 03 PM" src="https://user-images.githubusercontent.com/563/82103667-5c9e8000-96c0-11ea-9072-77ba9ef99d70.png">

With the limit on, expanding only takes a few hundred ms:

<img width="280" alt="Screen Shot 2020-05-15 at 3 25 10 PM" src="https://user-images.githubusercontent.com/563/82103672-632cf780-96c0-11ea-9449-a967a6ff5148.png">

Right now, we only put a More Info link in when we know there's a place to go to get more info. There's no guarantees that the package table (built from the resource map) has any correspondence with the metadata. If we put a More info link on every package table item, it'd be theoretically possible to receive a click but not have anywhere to scroll to.

In order to only show a More Info link when we know that package table item is described in the metadata, we hit MetadataView.findEntityDetailsContainer which is a very expensive method:

<img width="400" alt="Screen Shot 2020-05-15 at 3 31 31 PM" src="https://user-images.githubusercontent.com/563/82103897-49d87b00-96c1-11ea-9da3-b4f073f1111e.png">

I can imagine us:

1. Keeping the limit in order to keep performance where it is
2. Deciding we can handle More Info links sometimes not having anywhere to scroll to and always put them in. Optionally we can provide feedback when we can't find something lower on the page to scroll to.
3. Tune things so these calls aren't so expensive when called many times.

I think (3) could actually be done by vastly simplifying the routine but any routine which needs to get called hundreds of times and execute selections on the DOM will be slow. I think I'm in favor of (1) or (2). What do others think?

**Comment by laijasmine** [comment]
@amoeba Thank you for taking the time to look into this!  I would rather go with (1). Right now it isn't too problematic because datasets with hundreds of files tend to have about the same information in all of them usually command+F does the trick.

**Comment by laurenwalker** [comment]
Thanks Jasmine and Bryce for describing this issue.

Yes, we implemented this particular behavior for performance reasons. I agree with Jasmine that we should just stick with this behavior for now, even though it's not ideal, just because we have so many critical priority items open right now.

**Comment by amoeba** [comment]
Sounds good, thanks @laurenwalker .
