### ISSUE TITLE
Disable "replace" option for files that I don't have changePermission access 

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1393]
While testing the replace files branch, I ran into this issue. If I have changePermission permission on a resource map and metadata doc, but not on a particular data object in that package, I should not have the ability to replace the file for that data object.

The Replace feature should be disabled both in the UI (the option should be disabled via HTML/CSS) and in the models - so that even if a click event happens to go through somehow, the replace doesn't execute.

This is a rare case for now, but should be fixed before we release this feature into production.

Note the relation to bug #1392

**Comment by amoeba** [comment]
Nice catch! I hadn't even though about permissions. I'll get this patched in.

**Comment by amoeba** [comment]
Hey @laurenwalker, I ended up putting all the logic for this into the UI side since all the model work is also done there. Replacement is disabled by default and eventually will be enabled once MetacatUI gets back the sysmeta indicating we have permission. See https://github.com/NCEAS/metacatui/commit/2eff80cb5c1d7e6e83178ca792a0597d68e3f69f. Did you have something in mind for the model side of this?

A data item that can't be replaced will now look like this (+ with a disabled cursor, but the screenshot doesn't show it):

![image](https://user-images.githubusercontent.com/563/82490139-43fee300-9a8f-11ea-9460-583f61b5faad.png)

**Comment by amoeba** [comment]
@mbjones noted that we can relax the permission to `write` so I've made that change.

**Comment by laurenwalker** [comment]
Looks great, thanks!
