### ISSUE TITLE
support creating and editing EML 2.2.0 annotations

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacatui#1402]
**Describe the feature you'd like**

EML 2.2.0 added the eml-semantics model, which we need to support in the editor. See https://eml.ecoinformatics.org/whats-new-in-eml-2-2-0.html#supporting-semantic-metadata We should support at least two major types of annotations (in priority order):

1. annotations on eml attributes for measurement types
2. general dataset-level annotations

**Is your feature request related to a problem? Please describe.**
We currently lack the ability to edit attribute annotations and dataset annotations, which means the work on our semantic search is at a standstill, and it causes curation bottlenecks.

**Additional context**

Dataset-level annotations are very closely tied to controlled keywords in the EML `keywordSet` element with a thesaurus, and should be harmonized. Its probably best to use `keywordSet` for uncontrolled keywords, and `annotation` for controlled keywords if the vocabulary can uniquely identify terms in URI-space.

Other annotation types are possible in EML documents, but our first pass at editing in MetacatUI might simply enable these two types of annotations, and be sure to not lose the others that are found in a document. 

One challenge will be in handling the multiple locations in which annotations can be stored in an EML document, and the proper reference resolution for those in the general `annotations` element and in `additionalMetadata`.

**Comment by jeanetteclark** [comment]
Given our project to assign Arctic Data Center datasets a theme based on a custom vocabulary, it would be good to enable support for a user to assign their own dataset (via annotating the dataset element) a theme based on a custom list. A dropdown menu or lookahead would be really cool.

**Comment by amoeba** [comment]
This is coming along well. I have dataset- and attribute-level annotations parsing, serializing, and editable via the web interface. I'm trying to track down some bugs in how we update and show inline validation errors and I think I'm close there. @mpsaloha and I will be discussing the UI/UX of this today and I'll want to share our thoughts with the group for discussion.

**Comment by laurenwalker** [comment]
Thanks Bryce, those mockups look good. I really like the Measurement Type mockup and don't really have any feedback on it because it's pretty clear as-is. I do think it might make more sense to display it below the Attribute Label input, so that Attribute Name and Attribute Label can be right next to each other. 

Will we also be able to make inferences of the measurement domain based on the annotation added? (e.g. if someone chooses a carbon flux annotation, we could disable the "date-time" measurement domain, at least.)

I'm not entirely sure on the context of the "Annotations" mockup(s). Where will those be shown in the editor?

**Comment by amoeba** [comment]
Thanks for taking a look @laurenwalker.

Re:

> Will we also be able to make inferences of the measurement domain based on the annotation added? (e.g. if someone chooses a carbon flux annotation, we could disable the "date-time" measurement domain, at least.)

Not with ECSO in its current state but I could see at least two ways of doing this if we were willing to put in a chunk of time. Might be important/beneficial enough to look at.

> I'm not entirely sure on the context of the "Annotations" mockup(s). Where will those be shown in the editor?

The context of those mockups was within the Attributes pane of the Entity modal. This just an add-on to the existing template basically.

**Comment by amoeba** [comment]
Oh, I misunderstood. The jagged line is meant to indicate that the full set of annotations is at the very bottom of the attribute tab, yeah. 

My first implementation actually put the full list of annotations in a third tab called Annotations. I moved things into the Attribute tab because I was worried no one would ever click the Annotations tab but, now that we're hoisted Measurement Type up high, I actually think that might be a good way to go. In a separate tab, we can have more space for context too. I think an expandable/collapsible Advanced section at the bottom of the Annotation tab can work too.

I've mocked up the three variants: https://www.figma.com/file/hH6CrGXgqa6caa1ws8YgpW/Editor-Annotation-View-Placement-Designs?node-id=0%3A1

**Comment by amoeba** [comment]
More or less have this hooked up. I don't like it yet but I think it's a start.

Instead of letting users author arbitrary attribute level annotations (which we haven't really figured out the UX of), we decided to try just provided an easy way to pick a MeasurementType for each attribute. So I've put in a section in the attributes pane where I user can use the BioPortal autocomplete + tree viewer thing to pick one.

<img width="653" alt="Screen Shot 2021-02-02 at 5 04 24 PM" src="https://user-images.githubusercontent.com/563/106687667-10121200-6579-11eb-8f1f-27e1706172be.png">

In this screenshot, the user has already picked a MeasurementType. Clicking on the "pill" shows the same popover as on our metadata landing pages.

<img width="384" alt="Screen Shot 2021-02-02 at 5 08 03 PM" src="https://user-images.githubusercontent.com/563/106687755-3d5ec000-6579-11eb-9021-558447319d35.png">

@mbjones @mpsaloha is this pretty close to what you were thinking?

**Comment by mbjones** [comment]
It looks like a good MVP. Once you have a usable prototype, I think getting some usability testing from @samanthacsik, @jeanetteclark , @laijasmine, and the data team interns who have been selecting measurement types would help identify any outstanding issues. Should be pretty quick to have them give it a spin.

Last I knew, the tree widget in the search pane had an odd behavior where you had to click twice to select a term. Is that also present here? If so, it would be a good time to patch that up.

**Comment by amoeba** [comment]
> Last I knew, the tree widget in the search pane had an odd behavior where you had to click twice to select a term. Is that also present here? If so, it would be a good time to patch that up.

Yep, that's a default but I think we can tweak it. I'll look into that and set up a demo.

**Comment by amoeba** [comment]
Okay, comments from @mbjones addressed and from @laijasmine over on #1659. I've put together a demo over on https://neutral-cat.nceas.ucsb.edu which you can play with.

@laijasmine, @jeanetteclark , @samanthacsik, @mpsaloha (and any others), feedback would be useful at this point. Our idea with this interface was to make it as easy as possible for someone to set an `ECSO:MeasurementType` on an attribute so I've put together a streamlined interface.

**Comment by yvanlebras** [comment]
Hi amazing nceas/metacatui team!

Really interesting functionality and the manner to implement it is really good! Testing it, I am thinking that a thing who can be of interest is that when searching for a term in oboe, you have the resulting corresponding oboe terms who can be seen on the ontology tree, maybe with "neighborhood" so the user can decide to use another term semantically close (brother/parent) even if not matching directly ... ITM, this can maybe be too "big" on the screen...  FYI We are thinking the same kind of widget for MetaShARK to add semantic annotations to EML Assembly Line files through the cedarr R package we, @earnaud , developped

**Comment by amoeba** [comment]
I created [a PR](https://github.com/NCEAS/metacatui/pull/1660) since the diff is kinda big. Some folks on the datateam are testing this and I need to run this by @mbjones and @mpsaloha when we get a chance.

Heya @yvanlebras, your neighborhood idea is smart. Is the widget you're working something we could take a look at now?

**Comment by yvanlebras** [comment]
Unfortunately our widget is R Shiny based (so I don't think this can be useable + or - directly on metacatui) and not implemented for now. @earnaud ""just"" developped the basis bricks with cedarr R package so we can search for equivalent terms in all (or restricted list of) BioPortal ontologies. Moreover, in MetaShARK, the "EML documentation module" is allowing the user searching for terms in a tree representation of all EML modules, so quite close to this neighborhood idea... Maybe this can be like an inspiration but don't think this can be directly used..

**Comment by amoeba** [comment]
Inspiration would be helpful too, @yvanlebras, so any links would be appreciated.

**Comment by amoeba** [comment]
We had a productive feedback session last Thursday and I've made a few the changes we lined out:

- [x] Make `EMLMeasurementTypeView` configurable to only allow a single annotation. Selecting a new term from the autocomplete or the tree just replaces the last selection
- [x] Fix the filler text I left "This is my context string"
- [x] Let the user indicate they couldn't find a suitable term. I'm not happy with this UI just yet. I'd also like the user to be able to be able to indicate the did not find a specific enough term. ie they had to pick "Carbon Flux" when they really had measurements of some specialized form of carbon flux we didn't have a term for.

Two issues I haven't gotten to are:

- Popovers don't stay with the element the are bound to. I think this might be hard to fix because of the way the modal is styled but I'm not sure. Might have to ask for help here.
- You can open multiple popovers at a time and it'd be better if others close. I think this should be easy enough.

Up to date code is deployed at https://neutral-cat.nceas.ucsb.edu

**Comment by amoeba** [comment]
I built this kinda funky UI that allows the user to either (1) skip picking the term and indicate they couldn't find any good match or (2) pick a term but specify that it was correct but not specific enough:

<img width="740" alt="Screen Shot 2021-02-18 at 4 15 39 PM" src="https://user-images.githubusercontent.com/563/108443105-a8a8c300-7204-11eb-98c7-534c66564184.png">

@mbjones keyed in that the buttons on the right might make a lot more sense as checkboxes or radio buttons. I agree and am I going to tweak it since I think what I've got here is pretty weird as far as UX goes.

On our call today we talked about next steps and we decided to get the earlier version of this

<img width="763" alt="Screen Shot 2021-02-18 at 4 22 33 PM" src="https://user-images.githubusercontent.com/563/108443648-a4c97080-7205-11eb-9be0-e4527f3921f2.png">

onto test.arcticdata so the data team can benefit from it and then I'd continue working to make it more understandable to scientists. But after checking in with what's been annotated on the ADC so far, it looks like there are many cases where annotations were made with too broad a term. e.g., the term "depth" chosen for "True bin depth" or "depth of profile start". I also see that many attributes aren't annotated and I'm guessing it's because of holes in ECSO. The datateam maintains a spreadsheet that supposedly only has 14 term requests in it. So I'm wondering if maybe the datateam actually needs the next iteration . Thoughts, @laijasmine?

**Comment by laijasmine** [comment]
Same with what I mentioned at #202  - This feature might not get as much use if it is on test because we rarely create new datasets from scratch on test while most of the time datasets start on production. I want to avoid getting interns to switch back and forth using test and production might cause some confusion. 

The current iteration will still  be helpful - it will save us some copy and pasting from ECSO and potential mistakes there.

We try to maintain the spreadsheet but even I forget to add to it sometimes so if we can flag those while we are annotating that would be great. If we can add that to the metadata maybe in a consistent way (eg. how you have it as `
Measurement Type`) right now that might be tracked better?

**Comment by amoeba** [comment]
> If we can add that to the metadata maybe in a consistent way (eg. how you have it as Measurement Type) right now that might be tracked better?

Yep, it'll be queryable so we can occasionally take a look.

> Side note - might want to discuss this further off this issue but do you have a list of terms that are too broad that you mentioned?

I didn't look comprehensively but I'm able to find examples on most packages with annotations. For example, the `x` attributes in [this package](https://arcticdata.io/catalog/view/doi%3A10.18739%2FA21J97859) are typed as "Seawater Depth" but the measurements are a little more specific if you look at the definition. It might be overkill to generate a term at this level of specificity so I'd call this annotation good as-is.

**Comment by amoeba** [comment]
I've got an updated version of the view ready for review this Thursday. The feedback from a while ago about how we let the user indicate either (1) that they couldn't find a term that suited or (2) that the term they picked wasn't as specific as they liked has been incorporated and I think it's working okay. 

The screenshot below shows the UI when a user has chosen a Measurement Type but opted to select "The term I chose could have been more specific". In the background, we also add a dummy annotation next to the chosen one to keep track of the choice (ie serialized in the EML):

<img width="490" alt="Screen Shot 2021-03-23 at 6 46 41 PM" src="https://user-images.githubusercontent.com/563/112246923-46c6e900-8c08-11eb-9733-ecdd6807b65a.png">

Alternatively, if the user couldn't find a term that matched at all, they can indicate that and most of the view hides itself:

<img width="230" alt="Screen Shot 2021-03-23 at 6 49 11 PM" src="https://user-images.githubusercontent.com/563/112247101-87266700-8c08-11eb-9f73-eadbf94c7799.png">

**Comment by amoeba** [comment]
Just doing the double bookkeeping here the [associated PR](https://github.com/NCEAS/metacatui/pull/1660) has been updated to incorporate the latest changes from develop and has been tested again to ensure it still works. This work is ready for Review/QA.

**Comment by laurenwalker** [comment]
Thanks Bryce, I will see if we can get the arctic data team to try this out

**Comment by amoeba** [comment]
We already decided we'd skip them since it's not of use since they do their work from R for the most part. IIRC, the idea was that this would get deployed directly to users. Maybe we should talk over that again?

**Comment by laijasmine** [comment]
Happy to get the team to test out anything new that was implemented since on some test datasets. It is just logistically hard to keep track of if the interns are working on both test and production with datasets we are actively processing.

**Comment by amoeba** [comment]
Thanks @laijasmine. There aren't any code changes here since last March so I think it'll be very familiar to what you've already tested for us (thanks btw). I'm not sure it'll be very useful to have them test since it sounds like it'll distract them from their core work since they wouldn't use this interface anyway.

**Comment by laurenwalker** [comment]
Okay, we can ship this directly to a release if that's what you have discussed with others already. It might still be a good  idea to  have the data team try it out  for UX feedback, but we won't let that block a release.

**Comment by amoeba** [comment]
I feel like we've gone through a pretty good amount of UX testing between this issue and https://github.com/NCEAS/metacatui/pull/1660 but more couldn't hurt. I was hoping to get your feedback as mentioned in https://github.com/NCEAS/metacatui/pull/1660#issuecomment-812754087 at some point. Maybe we could walk through it real quick on the dev team call. It is feature flagged btw and defaults to off.

**Comment by laurenwalker** [comment]
Sounds good Bryce, I didn't know you had done some UX testing already, so I'll just take a final look and merge to develop! Thanks!

**Comment by amoeba** [comment]
Ah, my apologies. I was just referring the the UX testing described above in this thread and https://github.com/NCEAS/metacatui/pull/1660. At this point the whole semantics team is on board with the UX.
