### ISSUE TITLE
Boolean filters not displaying in editor

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1434]
ON dev.nceas, portal label: "cut34"

One booleanfilter is not showing up in UI, so there's no way to remove it

**Comment by laurenwalker** [comment]
I'm not sure if this is still an issue with the new query builder, @robyngit could you confirm?

**Comment by robyngit** [comment]
This is how that portal appears in the Query Builder:

<img width="1443" alt="Screen Shot 2020-10-29 at 16 29 01" src="https://user-images.githubusercontent.com/26600641/97629059-eb4f5100-1a03-11eb-9c14-c8fbc1a467ca.png">

The boolean filter appears, but not correctly. It's the same bug as I'm working on now: https://github.com/NCEAS/metacatui/issues/1572

The name of the field in rule 2 is blank because it's a `geo_hash` field. That case is covered in this issue: https://github.com/NCEAS/metacatui/issues/1567

So with the Query Builder, and with those other two issues already recorded, I think we can close this issue.

**Comment by laurenwalker** [comment]
Sounds good, thanks for looking into it Robyn
