### ISSUE TITLE
New DataONE nav and footer needs portal view "minimal" styling

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1448]
New nav and footer need to be simplified/minimalized for the new theme style. This was already done by Robyn: https://github.com/NCEAS/metacatui/commit/e90c0e64e44dfa481e535fcc4a0f9cd6492778f8 but was overridden with the new theme files.

**Comment by robyngit** [comment]
The lack of minimal nav is particularly problematic for viewing portals on small screens at the moment, since both the portal navigation and the dataone navigation bars are placed at the bottom of the screen:
<img width="475" alt="Screen Shot 2020-07-31 at 11 23 34" src="https://user-images.githubusercontent.com/26600641/89050675-19e45f80-d321-11ea-9493-1a52dc836e47.png">

**Comment by laurenwalker** [comment]
![Screen Shot 2020-08-04 at 7.21.59 PM.png](https://images.zenhubusercontent.com/5d152e12c27d0c306f021863/abf5665f-ac22-41fc-8a43-84867a4745e7)

This is what the minimal nav looks like. Dataone-web repo is updated as well so that the new HTML is inserted into the metacatui-exports.

Open to feedback

**Comment by robyngit** [comment]
It looks good! I noticed a few of things:
1) The sign-in button doesn't get updated with the user profile menu when a user is signed in.
2) The nav is still positioned at the bottom on small screens, which interferes with the portal & portal editor navigation.
3) Also on small screens, the menu items don't wrap so the sign-in button gets cut off.

**Comment by laurenwalker** [comment]
Thanks for taking  a look, Robyn. I fixed the mobile nav so that the menu is on top now.  
![Screen Shot 2020-08-05 at 11 40 40 AM](https://user-images.githubusercontent.com/6643222/89439919-84761080-d710-11ea-960c-7fba761da619.png)
