### ISSUE TITLE
Deprecate PackageTableView and replace with DataPackageView

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1451]
Use the DataPackageView in the MetadataView to display the package instead of the PackageTableView. This will make improvements to display easier to support and maintain since it will be contained in a single view. It also helps keep the UI consistent.

**Comment by robyngit** [comment]
There are three main tasks for this issue:

- [ ] Update the [DataPackageView](https://github.com/NCEAS/metacatui/blob/main/src/js/views/DataPackageView.js) so that it has a mode for editing and a mode for viewing (currently it's just designed for editing)
  - The view already [checks for an `edit` attribute](https://github.com/NCEAS/metacatui/blob/main/src/js/views/DataPackageView.js#L60-L62) on initialize, but this attribute is not yet used to change how the view is rendered
  - The [FilterGroupsView](https://github.com/NCEAS/metacatui/blob/main/src/js/views/filters/FilterGroupsView.js) is an example of a view that is rendered differently depending on whether the `edit` attribute is set to true or false.
- [ ] Replace the `PackageTableView` [where it is used in the MetadataView](https://github.com/NCEAS/metacatui/blob/26e1a46bd428522b43e6ba696109dfee710eb1a2/src/js/views/MetadataView.js#L838-L885), and make sure that it works the same as before. (The `PackageTableView` is not currently used anywhere else)
- [ ] Deprecate or remove the `PackageTableView` (to discuss). If removing, make sure to remove the associated html template as well, and all references to the view.

**Comment by robyngit** [comment]
@Rushiraj, as we chatted about, here is an example package where the table is expandable in view mode (PackageTableView), but not in edit mode (DataPackageView): https://demo.arcticdata.io/view/urn%3Auuid%3Afc5aac0d-0430-4e4f-abd7-91b4e5bde2da

**Comment by robyngit** [comment]
@rushirajnenuji, in terms of models, the `PackageModel` that the `PackageTableView` uses is also used by the `MetadataView` and the `SearchResultView`, so let's not deprecate it.

The `DataPackageView` instead uses the `DataPackage` collection, which is a collection of other packages, metadata, and data objects. It looks like you will be able to get all the information needed to display the data table from this collection, so I propose that for the `edit:false` version of the `DataPackageView`, use the `DataPackage` collection and not the `PackageModel`.

The `DataPackage` collection already gets set on the `MetadataView` as `MetadataView.dataPackage` with the [`getDataPackage` method](https://github.com/NCEAS/metacatui/blob/b9740df22ccc397102b94496b568bb2b6ae199a8/src/js/views/MetadataView.js#L161-L197). So in theory, when you are rendering the `DataPackage` in the `MetadataView`, you could pass it the `MetadataView.dataPackage`, in the same way that [`MetacatUI.rootDataPackage` is passed to the `DataPackageView` in the `EML211EditorView`](https://github.com/NCEAS/metacatui/blob/b9740df22ccc397102b94496b568bb2b6ae199a8/src/js/views/metadata/EML211EditorView.js#L525-L530)
