### ISSUE TITLE
Start portals with example Freeform page

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1464]

**Comment by robyngit** [comment]
Commit 796aab3 adds a new function for getting the base url for Portal Images. This worked in all the testing environments I tried, but it could use review to make sure that the logic here is correct. See https://github.com/NCEAS/metacatui/blob/796aab3065e56715b7858639c2b6e8e02ecb5a27/src/js/models/portals/PortalImage.js#L125-L166

**Comment by laurenwalker** [comment]
Robyn - Thanks for working on this, I reviewed the code and tested it out and it works well, but I did run into one bug. I really like that you included multiple images for multiple sections.

### Bug
I ran into a bug while trying to upload a photo twice in one "session". For example:
1. Open up a new portal builder
2. Click on the portal logo image uploader and upload a portal logo image
3. Click on the same portal logo image uploader again, and upload a different image (i.e. oops, I uploaded the wrong file, so I'm replacing it)
4. Notice in the Network tab that the upload of the second image failed with a 409 error. It looks like the image was saved using the same identifier as the first upload. A new identifier should have been generated.

### Suggestions
For the default image, could we crop it so that more of the mountains can be seen? Here's a screenshot of the portal builder and possibly what the crop could be: 
![Screen Shot 2020-08-06 at 11.59.50 AM.png](https://images.zenhubusercontent.com/5d152e12c27d0c306f021863/dca1627e-04a5-415d-af2d-da25d6a12182)

![Screen Shot 2020-08-06 at 12.04.36 PM.png](https://images.zenhubusercontent.com/5d152e12c27d0c306f021863/2b5d7551-61eb-4dc7-941b-eea6d20d40e5)

I'm not a huge fan of this image. Could we replace it?

![Screen Shot 2020-08-06 at 12.10.02 PM.png](https://images.zenhubusercontent.com/5d152e12c27d0c306f021863/ace88c89-eae4-4b43-b838-cc256ec5e37c)

**Comment by robyngit** [comment]
Replaced the bubbles image with an ocean landscape:

<img width="1386" alt="Screen Shot 2020-08-06 at 16 12 46" src="https://user-images.githubusercontent.com/26600641/89578939-ef9f1000-d800-11ea-8418-559b301772ca.png">

And instead of cropping the portrait image of a fall scene, I replaced it with a landscape image of a fall scene (also with mountains):

<img width="1386" alt="new-default" src="https://user-images.githubusercontent.com/26600641/89578949-f3cb2d80-d800-11ea-8e83-26fa174d0d71.png">

The order of the images is now randomized as well, so there's no one "default" image. The first page could start with any of the images in the config list.

**Comment by laurenwalker** [comment]
Looks great, thanks Robyn!

**Comment by robyngit** [comment]
Good catch on the second image upload bug, I think this is fixed now

**Comment by robyngit** [comment]
One other task related to this issue - we might want to configure default portal section images in the other themes
