### ISSUE TITLE
Add "not"/exclude filter to EditCollectionView

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1502]

**Comment by laurenwalker** [comment]
I think this is complete since we have the "does not equal" operator selector, right?

**Comment by robyngit** [comment]
I guess it depends on which "exclude" this issue is talking about. We still need an exclude option for the overall collection definition:

<img width="863" alt="Screen Shot 2020-10-27 at 14 05 43" src="https://user-images.githubusercontent.com/26600641/97343352-c4571a80-185d-11eb-8160-591304cccacf.png">
