### ISSUE TITLE
Data search fails to render if gmaps is blocked

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1514]
The app should load anyway without the map features.

**Comment by robyngit** [comment]
I keep running into this bug as well, since I get the "Google Maps JavaScript API error: RefererNotAllowedMapError" error when I'm testing locally. In case it's helpful for diagnosing the issue, I've noticed that after the data search fails to render, if you refresh the page, it renders the second time.

**Comment by laurenwalker** [comment]
That error is usually when you're using an API key that doesn't have your localhost enabled. (I have a private key for testing from localhost, let me know if you need it. It should never be pushed to Github, though).

The app should load with Google Maps totally blocked regardless, it should just disable the map feature.

**Comment by laurenwalker** [comment]
Closing this since we are about to focus on replacing Gmaps with Cesium
