### ISSUE TITLE
identifier filter not working as expected

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1559]
The collection query is constructed so that the `id` filters are applied to the query with an OR operator. The intention behind this was to allow people to add individual datasets to their portal that are not picked up by the rest of the query.

When I added an Identifier filter to the new query builder, the identifier filter was ANDed to the query with the rest of the filters.

Example:
 ![Screen Shot 2020-10-23 at 11.35.38 AM.png](https://images.zenhubusercontent.com/5d152e12c27d0c306f021863/4a87710b-ef64-46a8-ba47-850a61dd2fcd)

The solr query constructed was: `((isPartOf:urn\:uuid\:753c87fa-06d9-461d-8731-b6d1810e4c9a) OR (title:*data* AND -title:*test* AND identifier:urn\:uuid\:eaa10cbd-38af-4bfc-880e-67749c4596ff)) AND (-obsoletedBy:* AND formatType:METADATA)`

**Expected behavior**
The query should have been: `(((isPartOf:urn\:uuid\:753c87fa-06d9-461d-8731-b6d1810e4c9a) OR (title:*data* AND -title:*test*)) AND (-obsoletedBy:* AND formatType:METADATA)) OR (identifier:urn\:uuid\:eaa10cbd-38af-4bfc-880e-67749c4596ff)`

If you look at the Filters collection, you will see that in the `getQuery()` function, we separate out the id filters:

https://github.com/NCEAS/metacatui/blob/814f4d4d304d09ee13e1760dcb137e94fdbcbfed/src/js/collections/Filters.js#L94-L97

And then add them to the query string with an OR operator:
https://github.com/NCEAS/metacatui/blob/814f4d4d304d09ee13e1760dcb137e94fdbcbfed/src/js/collections/Filters.js#L138-L148

That is the pathway all Identifier rules should take when added in the Query builder.

**Comment by robyngit** [comment]
This was happening simply because we hid the `id` field from the Query Builder, and instead displayed the `identifier` field, which is a copy of id. I fixed this by [adding filters that include the `identifier` field to the list of idFilters](https://github.com/NCEAS/metacatui/commit/440e7fc9aef2a940185c7e3eb0031beedeb42f34). I could have alternatively hidden the `identifier` field and displayed the `id` field instead. Is there any reason that one solution is better than the other?

**Comment by laurenwalker** [comment]
`identifier` is the better field to use since it's a `text_general` type, so it can match substrings.
