### ISSUE TITLE
Some Solr fields used in production portals are hidden in the Query Builder

### ISSUE THREAD

**Issue by robyngit** [NCEAS/metacatui#1573]
**Describe the bug**

`siteText` and `project` are fields that we decided to exclude from the list of metadata fields in the Query Builder, however, these fields are used to build definitions in at least two production portals. [Data Keeper Portal](https://search.dataone.org/portals/1679861) uses `siteText` and [SASAP](https://search.dataone.org/portals/1679861/SASAP) uses `project`.

`isSpatial` is also hidden, and I didn't find it in any production portals, though it's one of the fields we use it to [generate random portals](https://github.com/DataONEorg/collections-portals-schemas/blob/master/tools/py-randomize-portal/randomize-portal.py) for testing.

**Comment by laurenwalker** [comment]
`siteText` should not be hidden, that must have been a mistake in the Solr Field spreadsheet. (It should be used instead of 'site')

SASAP should probably use `projectText` instead, although there's no need to change if it works as needed right now.

We can ignore `isSpatial` since it's not used in any production portals and we are going to hide it in the query builder.

Let's fix this issue with the solution proposed in #1567, and add `siteText` as a geography field.
