### ISSUE TITLE
Copy Citation content truncated if text contains quotation marks 

### ISSUE THREAD

**Issue by FiannaOBrien** [NCEAS/metacatui#1583]
**Describe the bug**
Using "Copy citation" for data package with quotation marks in title causes the clipboard content to be truncated.

*Example*: Data package with title `Data from: "Growth strategies and threshold responses to water deficit modulate effects of warming on tree seedlings from forest to alpine"`
*Full clipboard result*: `Lazarus B ; Castanha C ; Germino M J ; Kueppers L M ; Moyes A B  (2020): Data from:  `

**To Reproduce**
1. Create data package with double quotes in the title
2. Click on "Copy Citation"
3. Paste contents elsewhere
4. See truncated citation

**Expected behavior**
Quotes should be escaped within the string

**Comment by amoeba** [comment]
Good catch and thanks for taking the time to write this up @FiannaOBrien!

The failure kinda makes sense because we're storing the citation text in a `data` attribute as-is and it must not like seeing double quotes inside it:

https://github.com/NCEAS/metacatui/blob/814f4d4d304d09ee13e1760dcb137e94fdbcbfed/src/js/templates/metadataControls.html#L4

We might need to urlencode or base64 encode the value prior to rendering the template and decode on the way into the clipboard.

**Comment by amoeba** [comment]
Fix made in 7df21b002ae628d53595046748632aa8ece364f2. I tested on some fake datasets with lots of double quotes in their titles and also on some datasets that don't have quotes in their titles to make sure this didn't break anything. Appears to work nicely.

**Comment by laurenwalker** [comment]
Works for me, thanks
