### ISSUE TITLE
Rescale images uploaded in markdown editor

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1618]

**Comment by robyngit** [comment]
I set the default max resolution to 1200x1200 which I think is a good balance between allowing detailed images but still loading them relatively quickly. See [this portal](https://dev.nceas.ucsb.edu/portals/test) for an example with a scaled down image.

The max height and width are configurable in the MarkdownEditorView.

**Comment by laurenwalker** [comment]
I get an error message when I try to view that portal:

![Screen Shot 2020-12-11 at 4 27 55 PM](https://user-images.githubusercontent.com/6643222/101960824-e1596a00-3bcd-11eb-9ef5-f7ddcd60aa5d.png)

From the console:
```
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery.js:3429:51

This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. test

XHR GET https://dev.nceas.ucsb.edu/knb/d1/mn/v2/meta/urn%3Auuid%3Ab8567c42-d226-42d9-b6c4-2314469c72c7
[HTTP/1.1 401 401 145ms]

XHR GET https://dev.nceas.ucsb.edu/knb/d1/mn/v2/object/urn%3Auuid%3Ab8567c42-d226-42d9-b6c4-2314469c72c7
[HTTP/1.1 401 401 145ms]

```

**Comment by laurenwalker** [comment]
I'm guessing it's private because of the 401, but I'm not sure why the error message says "something went wrong"

**Comment by robyngit** [comment]
> I'm guessing it's private because of the 401, but I'm not sure why the error message says "something went wrong"

It only said "something went wrong" because the error response was not being passed to `PortalView.showError`. Even with that fixed, the 401 error message wasn't very nice looking:

<img width="1045" alt="Screen Shot 2020-12-14 at 14 05 28" src="https://user-images.githubusercontent.com/26600641/102123842-75694280-3e15-11eb-887c-6f882b4b364a.png">

I changed it to look like this when the user is not signed in:

<img width="1045" alt="Screen Shot 2020-12-14 at 13 52 34" src="https://user-images.githubusercontent.com/26600641/102123520-f4aa4680-3e14-11eb-96ea-99e47ab77a79.png">

And like this when they are signed in:

<img width="1045" alt="Screen Shot 2020-12-14 at 13 52 54" src="https://user-images.githubusercontent.com/26600641/102123512-f116bf80-3e14-11eb-9d69-0c0180dd8ed2.png">

**Comment by laurenwalker** [comment]
That's much nicer!!
