### ISSUE TITLE
Extend semantic search widget to support more than just ECSO MeasurementTypes

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacatui#1654]
The Annotation filter in the search catalog is currently hard-coded to search for classes in the [MeasurementType](http://ecoinformatics.org/oboe/oboe.1.2/oboe-core.owl#MeasurementType) sub-tree of [ECSO](https://bioportal.bioontology.org/ontologies/ECSO/). It can quickly be reconfigured to search in another ontology or ontology sub-tree. This has worked well because as it's let us bootstrap _some_ form of semantic search that is immediately useful to users by constraining scope to a single portion of a single ontology.

<img width="420" alt="Screen Shot 2021-01-25 at 10 30 33 PM" src="https://user-images.githubusercontent.com/563/105813876-f7906f00-5f5c-11eb-9dc6-ce92e8f4ab78.png">

However, we're starting to bring in annotations from other ontologies and it's too hard to search for datasets with those annotations using the current interface. We should consider if we can extend this to support more than just a sub-tree of a single ontology. Some ideas of mine include:

- Let the deployment have a configured a set of ontologies that the widget might search from and optionally show browse-able trees for
- Find a way to search just within just the set of existing annotations (by free-text). Searching for datasets by browsing the `ECSO#MeasurementType` tree isn't that useful until you have annotations all over the tree. It's pretty frustrating to click on a term and get zero results. As an aside: If we could show the number of results you'd get if you searched for a term _next_ to a term in the tree browser that'd be cool
- Let users search annotations using the main search box. We could index property labels and this would support terms from any new ontologies

**Comment by amoeba** [comment]
I think the next iteration of this could and should work pretty similarly to the current implementation (above). Without changing too much, we could extend the current widget to:

- Have a configurable default ontology or ontology sub-tree to search and browse
- Accept a configurable list of ontologies or ontology sub-trees to let the user search and browse
- Show the search and browse widget for the default ontology or ontology sub-tree by default
- Provide an easy way for the user to select an alternative ontology or ontology sub-tree to work with

This might look something like:

<img width="361" alt="Screen Shot 2021-06-02 at 4 37 12 PM" src="https://user-images.githubusercontent.com/563/120568801-21511b00-c3c1-11eb-8241-2f5d64c7aca1.png">

This could be done with by re-using the Bootstrap nav pills component:

<img width="381" alt="Screen Shot 2021-06-02 at 4 40 27 PM" src="https://user-images.githubusercontent.com/563/120568883-48a7e800-c3c1-11eb-857f-79d0e8a14e2e.png">

**Comment by amoeba** [comment]
I've got a fully working version of the above prototype done,

![Kapture 2021-10-11 at 17 14 59](https://user-images.githubusercontent.com/563/136876112-9b06c2b8-2ab1-4469-ae14-0faed77a707d.gif)

And now I want to turn to how this would integrate with the variant of this filter we use in the Portals collection search builder:

<img width="1048" alt="Screen Shot 2021-10-11 at 5 34 05 PM" src="https://user-images.githubusercontent.com/563/136876174-f7cd63de-e1e8-4eb7-81a6-464c55fd5660.png">
 
We currently have three variants of this filter and this would be a fourth. Ideally, we only have one variant, though I'm not sure that's feasible. If anyone has any good ideas I'm all ears.

**Comment by amoeba** [comment]
I spent some time tinkering and I think I have something that will cover all cases (turning four into one). The basic idea is that we'd extend the SearchableSelect to support a dropdown where the user can pick which ontology they're working against. We could use this on the main search (DataCatalogView) and in the Portals editor equally well. Since it's a change to the SearchableSelect I'm going to coordinate with @laurenwalker and @robyngit for thoughts.

![Multi Ontology Search Mockups](https://user-images.githubusercontent.com/563/137015683-37dc8ee4-f74c-4c4c-a9df-abddd936e550.png)

Full link: https://www.figma.com/file/JtkdJiI8Y454uWpYsUwuvF/Multi-Ontology-Search-Mockups?node-id=0%3A1.

**Comment by robyngit** [comment]
Here is a little audit of where we are currently with this issue:
- We have a WIP version of the annotation filter using multiple ontologies in the DataCatalog in [this branch](https://github.com/NCEAS/metacatui/compare/feature-1654-annotation-filter-improvements). I tested and it works pretty well, though the branch was created ~1.5 years ago and there are some conflicts with the main branch.
- As Bryce pointed out, if we implement this new `TabbedAnnotationFilter` view, MetacatUI will have yet another version of an Annotation filter. (We currently use the `AnnotationFilterView`, the `AnnotationView`, and the `AnnotatorView`). Ideally, we would roll all of these very similar views into a single configurable view.
- Bryce suggested extending the `SearchableSelect` view. This has already been done in the `AnnotationFilterView`, though only when the filter is rendered as a multi-select.
- Making a single view that would work for all contexts where the Annotation filter is currently used presents some challenges. For example, in the query builder, a user can keep adding terms to the input, and those terms are displayed in the input itself. In the DataCatalog search, each time a user enters some text, it should be added to the list of "applied filters" instead. (See https://github.com/NCEAS/metacatui/issues/1693)

Here are some options for completing this issue:

#### The **ideal** way

Take the opportunity to combine all of the Annotation views into one. This would take the most time.

#### The **fastest** way

Use Bryce's WIP view. This needs more testing and a way to configure the ontologies for the repository. The downside is that you would not be able to configure multiple ontologies in all places, e.g. not in the QueryBuilder.

#### The fastest way without creating a brand new view

Add the ability to select multiple ontologies to the current AnnotationFilterView. This involves basically moving all of the logic Bryce wrote in the `TabbedAnnotationFilter` to the `AnnotationFilterView`. The downside is that the `AnnotationFilterView` would become larger and more complicated than it already is. Also, because the way the multi-select is rendered is so different from the way the single-select is rendered, there would probably be some duplicate logic in the same view, unless we do a bit of a refactor.

**Comment by yvanlebras** [comment]
Really of interest! Thank you for this work! Not sure I fully understand operationalization scenarios, but just my 2 cents: It appears to me of interest to index all "terminological resources terms" on metacat/metacatui so we can use a searchable form comparable to the one we can use for "attributs" with autocompletion. So having a way to select search terms using the "tree representation of terms"  as proposed by @amoeba Oct 12, 2021 + "just" typing the term and having autocompletion would be very nice IMO.

**Comment by robyngit** [comment]
I'm working on this feature by first combining the two Annotation views into one. Here is a summary of those two views:

#### AnnotationFilterView
- uses the `SearchableSelectView` if in "multiselect" mode
- views that use it:
  - `DataCatalogView`
  - `QueryRuleView`
  - `SemanticFilterView`

#### SemanticFilterView
- extends `FilterView`
- uses `AnnotationFilterView` as sub-view
- views that use it:
  - `FilterGroupView`
