### ISSUE TITLE
Tweak BioPortal tree widget behavior to require fewer clicks

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacatui#1659]
The BioPortal tree widget we use in the search catalog and are soon going to use in #1402 and #1653 has a behavior I think most of us find odd: When you type into the autocomplete box and select an item by clicking on it, the tree below expands and shows you your selection. To actually pick that item in our search, you have to then go click on the item in the tree. You can't just pick an item from the autocomplete.

While working on #1402, I added a configuration option to change this behavior so you can just click and be done:

![2021-02-04 12 39 23](https://user-images.githubusercontent.com/563/106959881-c7c53200-66e7-11eb-8d6b-9c49c6f5db3b.gif)

I'll note that you can still use the tree to pick items. I got a few thumbs up in Slack on this idea but would love thoughts or 👍. I think if we like this change, we can make it the default behavior of the widget and make all instances of the widget use the default behavior.

PS: I think this change makes the two buttons on the right pointless:

<img width="344" alt="Screen Shot 2021-02-04 at 12 55 17 PM" src="https://user-images.githubusercontent.com/563/106960274-4cb04b80-66e8-11eb-95ad-c296d79dd259.png">

So they could be absent when the widget is configured in this way.

**Comment by laijasmine** [comment]
@amoeba one clarifying question because I couldn't really tell in the gif - can the tree "open up" to the term after you have made the selection? Kind of like this where it highlights your selected term -

<img width="446" alt="Screen Shot 2021-02-04 at 2 17 09 PM" src="https://user-images.githubusercontent.com/13112379/106962312-ca2d8900-66f3-11eb-80bf-731925abd515.png">

It might help guide people to more specific and accurate terms. When I use the Bioportal interface, I often find myself looking at the tree after finding an annotation just to make sure that my selection of the semantic term makes sense by looking at what it is nested under. Or if it could be more specific by looking at any terms under it.

**Comment by amoeba** [comment]
Yeah I think we could do that and that it could be useful. 

>  just to make sure that my selection of the semantic term makes sense by looking at what it is nested under

btw, this is really good feedback.

**Comment by amoeba** [comment]
hey @laijasmine, so I put together a demo which you can play with at https://neutral-cat.nceas.ucsb.edu. Let me know what you think about how that works.

**Comment by mbjones** [comment]
Worked great for me on a quick run through. 👍

**Comment by yvanlebras** [comment]
Oh, the @laijasmine comment seems to be very similar to the comment I made https://github.com/NCEAS/metacatui/issues/1402 !

**Comment by laurenwalker** [comment]
@amoeba I see that you implemented these changes on neutral-cat - did that work get pushed to a branch?

**Comment by amoeba** [comment]
I don't think so but I can apply them to develop tomorrow. I'll ping you here when I do. Thanks for checking.

**Comment by amoeba** [comment]
Hey @laurenwalker, I tested it out against the tip of `develop` and it's working fine. Committed in https://github.com/NCEAS/metacatui/commit/e79e26e04621c8e15758d9dc8193bef5aea07df1. This issue's in the Review/QA column on ZenHub and ready for you.

**Comment by mbjones** [comment]
This release will be a fantastic milestone! Thanks!

**Comment by laurenwalker** [comment]
Thanks Bryce!
