### ISSUE TITLE
Portals missing filter by project

### ISSUE THREAD

**Issue by vchendrix** [NCEAS/metacatui#1705]
**Describe the bug**
In Metacat 2.14.0 Portals enhancement for filtering, I cannot figure out how to filter by Project

### Old Filter
![Screen Shot 2021-03-24 at 4 29 12 PM](https://user-images.githubusercontent.com/1558129/112396957-5f91d600-8cbe-11eb-9398-09d717ec0642.png)

**Expected behavior**
I expect to be able to filter portal data by the `project` solr field

**Comment by mbjones** [comment]
Hi @vchendrix thanks for the report. I tried to reproduce, but its working fine for me on the Arctic Data Center site, as shown in this screenshot:

<img width="1594" alt="Screen Shot 2021-03-24 at 5 16 19 PM" src="https://user-images.githubusercontent.com/766407/112404375-198c4080-8cc5-11eb-8d0b-f902785d3fb9.png">

Based on your screenshot, it appears to me that you are using the old filter configuration UI (which is oriented vertically), rather than the new one (which is oriented horizontally, and provides configurable sets of rules). Are you sure you're using the new release? Can you provide details of MetacatUI version, how you got there, new portal versus existing, browser, etc.? Hopefully this issue will be obvious to @laurenwalker or @robyngit.

**Comment by vchendrix** [comment]
Sorry for the confusion. I gave you the screenshot of the old version to show the field I wanted.

When I cycled through the list of fields to filter by in 2.14.0, I couldn’t find the project field in the list. Maybe is it a user education issue. Can you submit a screenshot of where I would find the project field in the drop down?

**Comment by mbjones** [comment]
@vchendrix You can just start typing the field name "Pro" and it will show where it is in the categories. In this case, it's under "Awards and Funding", which is arguably not too intuitive.

**Comment by vchendrix** [comment]
Ah!! That did not occur to me. Thanks!

**Comment by robyngit** [comment]
Could I ask which category you would have expected to find "Project" in, @vchendrix? We are currently reviewing the organization of solr fields in portal builder (see https://github.com/NCEAS/metacatui/issues/1678), so that feedback would be helpful!

**Comment by vchendrix** [comment]
@robyngit That is a good question.  I guess I would have expected them in General or the People and Organizations section.  However it should be mentioned that I didn't know I could type my search in the field.  That would have been enough for me and I wouldn't have needed the categories.

**Comment by laurenwalker** [comment]
@robyngit Could we list the Project field under multiple categories?

**Comment by robyngit** [comment]
Just tested that. We _could_, for example:
<img width="298" alt="Screen Shot 2021-04-14 at 11 11 45" src="https://user-images.githubusercontent.com/26600641/114734668-6c7c7500-9d12-11eb-9a1b-0e6c3dc780ce.png">*

But the dropdown interface assumes that each option has a unique value, so there would be some bugs to work out. For example, if both "Project" items are selected, then the second one gets removed from the list completely, even if the first selection is removed:

https://user-images.githubusercontent.com/26600641/114735107-ddbc2800-9d12-11eb-95c5-e59d52c5e7b7.mov

_(*clearly Project should not appear under Taxon, bad example)_

**Comment by vchendrix** [comment]
This is not an issue
