### ISSUE TITLE
Support Google Analytics 4

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1709]
Add configurable support for the new version of Google ANalytics (4) which uses the gtag.js API instead of analytics.js. We may want to support using both since Google ANalytics still seems somewhat immature and metacatui users may want to support both versions for a while before fully switching over.

**Comment by robyngit** [comment]
from https://github.com/NCEAS/metacatui/issues/2149#issuecomment-1610330115 @mbjones said:

> Hi robyn I keep getting notices about the Google Analytics changes that are upcoming. This is the final week to update Google Analytics tag (UA-) to the Google tag (G-) using the GA-4 platform for all sites. Starting July 1, tracking will stop on a site if a new GA-4 property is not connected. My impression from looking at our site is that Google might automatically create GA-4 properties for our existing ones, but I’m not sure of that. Could you look into it and try to be sure we don’t drop our tracking accidentally, especially on core sites like dataone.org, search.dataone.org, arcticdata.io, the KNB site, and the hosted repository sites? cc @nickatnceas

**Comment by robyngit** [comment]
Changes to support GA4 have been made in the `feature-1709-GA4` branch.

In light of the fact that we may switch to a different analytics service in the future (#2149), I took the approach of moving all of the analytics logic to a model. An instance of this model gets attached to the global `MetacatUI` object as the `.analytics` property. I created both a generic `Analytics` model, and an extension of that one called `GoogleAnalytics`. This will hopefully allow us to simply swap out the `GoogleAnalytics` model for a difference `Analytics` model in order to switch services.

Left to do:
- [ ] Configure the new GA-4 properties for each of our repos
- [ ] Test that the new set up works as expected
- [ ] Add release notes and possibly additional docs to help repo owners transition
