### ISSUE TITLE
Save the current Cesium config as a link for sharing

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1806]
Add a feature to Cesium and MetacatUI where users can save their current data layer configuration to come back to later since the map will be reset anytime the browser window is closed. This Cesium config can be reloaded when the user logs in on their next visit.
These saved configs could also be shared with others. e.g. if you found an interesting combination of data layers/colors/filters/time, you could save and share that map with others. We could also allow users to publish their saved maps and create a "Gallery" of maps others have created. This could help a lot with community and cooperativeness around the PDG.

**Comment by robyngit** [comment]
One use case for this came up in the PDG meeting today: the [LEO Network](https://www.leonetwork.org/) would like to include links on their website that open up the PDG portal and specific locations and with specific layers visible

**Comment by robyngit** [comment]
This feature keeps getting requested for different use-cases, which is why I've added the high priority tag.

For example, a researcher just asked whether we could create a link that displays the Details Panel for a particular layer by default. Here are details of the request:

> Also, is there a way to have a link to the PDG where the INFO & DATA tab is already open for the SWI trend? I'm just thinking that if someone (a non-scientist) is directed to this site from a news story, they might be confused
because there is a layer for lakes, another for surface water, and then mine for the SWI trend. As a scientist, I understand how these are all different! But someone else might be confused and it would be nice to highlight the data published in the article, and those who are interested can stay and click around some more.

**Comment by robyngit** [comment]
Here is a mockup of a simple UI we could use in the Cesium map to share a link of the current view:

![share](https://user-images.githubusercontent.com/26600641/201769247-9bf96525-7121-4fe4-bc9f-cc2d82be1692.png)

**Comment by robyngit** [comment]
Overall, there have been few requests to save map views as a collection, but many requests to get a link of the current map view to share between users. If we can get the link functionality implemented, then a user could at least create their own collection of views via browser bookmarks. We could also use the link functionality to create a "Gallery" view in the future.

Map properties that should be shared via the link:
- visible layers
- layer opacity, saturation, etc.
- camera position
- ...?
