### ISSUE TITLE
Edit button show up when user is not logged in. 

### ISSUE THREAD

**Issue by helbashandy** [NCEAS/metacatui#1821]
**Describe the bug**
When a user is not logged in, edit and publish buttons show up on the data packages landing page. 

**To Reproduce**
1. Go to https://data-dev.ess-dive.lbl.gov/view/ess-dive-b0e289d7e7f8390-20210609T031106076772 when logged out.
2. Notice the edit button

**Expected behavior**
Edit and publish buttons should only show up when user is logged in

**Screenshots**
<img width="1665" alt="Screen Shot 2021-07-07 at 1 01 26 PM" src="https://user-images.githubusercontent.com/47407500/124821366-771a6500-df23-11eb-93dd-f6332afc8786.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] OSx
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] `2.15.1`
 
**Additional context**
Same behavior in the portals list feature branch `feature-#1708-portals-list`

**Comment by amoeba** [comment]
Hiya @helbashandy, this looks like expected behavior. The edit button shows up when the person/client viewing the metadata has sufficient permission edit the object. In this case, the object in question gives `public` (ie anyone) `read`, `write`, and `changePermission` permission:

```xml
<allow>
  <subject>public</subject>
  <permission>read</permission>
  <permission>write</permission>
  <permission>changePermission</permission>
</allow>
```

See the full SysMeta record: https://data-dev.ess-dive.lbl.gov/catalog/d1/mn/v2/meta/ess-dive-b0e289d7e7f8390-20210609T031106076772.

The Edit button will not appear if you remove `write` and `changePermission` from the above rule.

Is this intentional on your end? Or were you hoping to be able to use the above access rule but not have the edit button show up?

**Comment by laurenwalker** [comment]
Thanks Bryce. I can confirm that I am seeing the same thing when I look at the system metadata for the above object.

**Comment by helbashandy** [comment]
Thanks everyone - We realized that something probably happened when we published development data packages and it added an access policy that we were not expecting. I'll close this issue since it seems unviable anymore.
