### ISSUE TITLE
Add ability to filter by published vs private packages

### ISSUE THREAD

**Issue by gothub** [NCEAS/metacatui#1902]
**Describe the feature you'd like**
Add a filter option in the left bar to view published or private packages only. Users (& in the future project admins) will want this filter feature to see which packages are yet to be published

**Is your feature request related to a problem? Please describe.**
No, this is a requested enhancement.

**Additional context**
This request originated from the ESS-DIVE project, as described in [this issue](https://github.com/ess-dive/ess-dive-catalog/issues/263).
The use case that this new feature would support is for admin level users that can view all content in the ESS-DIVE repository wish to have a way to only return datasets that are not publicly viewable (private).

**Comment by vchendrix** [comment]
> @laurenwalker @mbjones @vchendrix
> 
> Using the current DataCatalogView, the search filter could be added as radio buttons that select one of the following:
> 
> * Only private datasets
> * Only public datasets
> * Private and public datasets
> 
> The UI would look like the following, which is shown with checkboxes but could be updated to be radio buttons. This image shows the default search filters, with the proposed new filter at the bottom of the image: ![public-private-filter](https://user-images.githubusercontent.com/6412946/138354925-72acf2e7-8aa9-480c-8d0b-8369b8447653.png)
> 
> Note that the following options affect the Solr query that returns the list of datasets in the view as follows:
> 
> * Only private datasets - adds 'isPublic:false' to the Solr query
> * Only public datasets - adds 'isPublic:true' to the Solr query
> * Private and public datasets - doesn't add to the query (this will be the default selected item)

I defer to my other ESS-DIVE team members @spoon @mburrus @charuleka

**Comment by vchendrix** [comment]
IMHO,  you don't need the third checkbox (public and private). If the first two are uncheck then the assumption is that there is no filtering by public or private.

**Comment by laurenwalker** [comment]
Looks good, I merged the PR to `develop` so it will go into the next release.
I made some minor changes to the look of the filter. I changed the icon to the 'private' lock so it matches the icon that represents `private` everywhere else in the app. I also added the word "only" to the checkbox option since when it is unchecked, private datasets *do* appear in the results, so I think it makes more sense. These can all be changed in the `search.html` per theme.

![Screen Shot 2021-12-20 at 12.13.19 PM.png](https://images.zenhubusercontent.com/5d152e12c27d0c306f021863/f2163656-62a7-4815-b3cd-7c4ba546a1d2)![Screen Shot 2021-12-20 at 12.18.11 PM.png](https://images.zenhubusercontent.com/5d152e12c27d0c306f021863/ef33f403-32fe-4136-9aab-9a72830a3334)

**Comment by laurenwalker** [comment]
I also fixed the tooltip wording, which was confusing. If the user is not logged in, I added a sentence that reminds them they should be logged in.

### Before

![Screen Shot 2021-12-20 at 12.25.08 PM.png](https://images.zenhubusercontent.com/5d152e12c27d0c306f021863/f511d5b2-1a31-43d3-99ae-fecae917723c)

### After
![Screen Shot 2021-12-20 at 12.28.35 PM.png](https://images.zenhubusercontent.com/5d152e12c27d0c306f021863/a42883a9-fcf2-4a30-baca-52dfd99088b3)![Screen Shot 2021-12-20 at 12.28.46 PM.png](https://images.zenhubusercontent.com/5d152e12c27d0c306f021863/e36d1b92-2630-43ab-802b-1dcec417b320)

**Comment by gothub** [comment]
@laurenwalker thx for making it more presentable!
