### ISSUE TITLE
Investigate approaches to displaying Data Catalog results on the Cesium map

### ISSUE THREAD

**Issue by robyngit** [NCEAS/metacatui#1941]
Look into alternatives to GeoHashes for displaying search results from the DataCatalogView on the Cesium map. For example, we might want to take advantage of Cesium's [clustering](https://cesium.com/learn/cesiumjs/ref-doc/EntityCluster.html) abilities.

**Comment by laurenwalker** [comment]
We've decided to continue with the geohashes for now since it's immediately ready to use. We might want to use some other method of displaying results in the future.

**Comment by robyngit** [comment]
Just some notes for when this issue comes up again:
- There are currently [626,609 datasets on DataONE](https://cn.dataone.org/cn/v2/query/solr/?q=southBoundCoord:*%20AND%20-obsoletedBy:*&fl=northBoundCoord,eastBoundCoord,southBoundCoord,westBoundCoord,id,title) with location coordinates.
- Displaying hundreds of thousands of points in Cesium is no problem. [Here](https://sandcastle.cesium.com/#c=bVJdb5tAEPwrK55Adg47adp8EKuRI/UlUiJF6kuoqgus7VWPO3R3kC/5v+cWF4PbvAzs3MzoZqEw2nloCZ/RwhVofIYlOmoq8bPj4jwqunlptJek0eZRcpnrXLfSQm1Iexd8uwDhCtQoaksVeWrRCVmW8SjznvX3/fHSKIWFJ6PjhDM5EV+8lb9bqTj1cTaFmZgzHDOcMHxhOGX4yvCN4Yzh/Fd3r5WxEHOUMnpNvikxJB3Nz2aXIyaDQ2IySeA91wCDW/q9+Zyl/ZzBeNwbR1YKniChIB3qCIV67TeBHlkADjoH32B4JO6zU+323G1z72TWEW/vol/vUlof3qQ+EStrqhtcW0QXD7UnQ/50aDRik+kQXxhl7JDNUxd7reqNjA/oH3e3N90XGftrekH1QG94AfM9vU3+ltryI8A2mkaZ868KF73mO1W1sR4aq2IhUo9VHe6KLn1qij/oReFcn5KlY2tWUgtUXn3yz0KhpHPhZNWo7lJ5tMjSoP/PqowsSa/vWrRKvrJsM1/c7kghRJaG8XOnN0Y9SftP8gc) is an example with 648,000 points displayed.
- Clustering these points is also feasible, but actually tends to slow down the rendering rather than improve performance.
- The limitation in showing a point for each dataset in the search results catalog would be how to get all of the location data from Solr. We would need to aggregate the locations in some way.

**Comment by laurenwalker** [comment]
I did some experimenting with displaying geohashes in Cesium (for #1720) to decide between the following options:

1. Displaying geohashes as Cesium entities (polygons, circles, etc)
2. Displaying geohashes as 3D Tiles

I wanted to figure out which option has the best balance of:
- Loading and rendering time
- Time to develop/implement
- Usability
- Visual appeal
- Ability to extend or change in the future

# Results

## Polygon entities
[View in Cesium Sandcastle ](https://sandcastle.cesium.com/#c=vVgLb+O4Ef4rbIDbkyxatpzNPmwzqS/J7qbI7hZI2iuQGAItMTbvZNJHUcnmEv/3zuhtK3sHFG0TJCRnhsOZbx6iNOj1blWPfBR6xdMV+btOHpdapUg7M/whJZxsChrhKiYJX4iE3GlDBI9WZFluS8Q9kEe5CE9TuVS40cBSr0mkE2180Di4VRHotuReigdhCCNKPJBTkcps7f8zpzm3B1G+PtXKcqmEuT1wJ7eq2hmDTaWtIgUFd5mKrNTKcZ9uFQE7bGXuBNeLhf4mUqf/fkj7wbshhRGHkeuDC+fggUMc1OUSdkye8BhCCi24E/THItKxCHFVCNJCBH8inSkLMhtuUnGhrPOZ25VfOO24vWA4bEvzZLPiIJ3vGgDTG/qHk+rICmNWYuMLZaWVIvV5HDtPlZpKbEyeGs0rKQw30eoRyCWYp9xYmHF16N8ZvT4TSyNEOjOGPzo3pNlaIHQTzGkxGc5pm1myD1tsQv5IYPTi/qBhk3kbk5WQy5UFswGOYYu+5lYYyZOWQ3kOoS+f0qQA+i7R2uxiTnrk8M3QHcA/Sob+Ef57k8/ap+rMJpBZoNyaTHQZ+Vn7R//86eL6vBLdFpOtO2mnTFEbfxrBVGLC/lmsHKdE1ishdAcjSpwSRq8MBxAbz4rzd1KDECu+IcCYuzuhuYP6AvqPweuNJWutdLrhkfhxRya1j4mo7bxE9VdI8j9cXF7uSJbI/SxjuwKtw101EU/ET49nMrVcRYh7q+y/CG4+cHMFMtw4gX8kwM0jH+L3zh+KPHhv3e/hnk+2+WLQ68NP3cf+dkUSuYCyeCRI72PvgZJ37rkhP82uzg9H4enXs/MrdnswDEaHr4/evH33fhHF4m65+uXXtdr8ZlKb3T98e/z99oC2d4RnF6fX7GlLJRtO5LTN8hOhlnY1kZ7ndrbc7EhGK25m1pHunMkJGnX+BRnh7B/XX8EmnlkN536++BJezq4Z9q/Ps3/lc5wi+esXlre0nA4LnF9dfPxw8TH8NLv6FF6ef/l4/YndDOkRfUvf0SCgwYgGhzQ4osEbGryFTjinQmF/Y3UbFVRR7T7JO0czxlpG5bTbA5WtF9iTGbOPG6HviHh+foGqXLsy+iEP9LkxGvt6ao1US6K05XkBGPFbJo2I86cJOkw2RkQyBZ6PTR9RMUz46SaRFvYjEeqgBJlapr7HkizvCmv+zTHUuhPNusDcyPlWJKkg91rGZAjO6levwOn37qTKk5DG7GZOMzakHP4i+FuwMgw0YWVw6IyVIaBLVkZmEpemTPXEBdz4DyPGhifq2AmZM/OWWLYnTsQCz4mm08CFnaE7BsKwIsyQIHL5hZd05JN9+QUQKPc8egSeeF7mPqEHK9ZOuptoDoZtsnTlwHMsK1zaGmEzo0js/6KlAiwBym2ZFqFUtpMamunn56NRjRIgDJpkDUxYAxPXwGQVMAjkxCIqvMdG1Na4GObEYHXuJ/dYAFuMO46ZQRCAKb2wxQyRKRkc7XmT0gG+pa2Hdcts96kyFexnfxlSU9tqa1tlbWtY2xqDX0XwRVXZ2ZRPMqjuHN2IiZts7lt9qaHfn/JUOO4kZt3KB9wrExbs9WRxDCAs+v1CS8Li4+PFq2CiTxxVOUoDCGNyEjIFbioINXCMZxsOZP/YAAc90tsyiDeWhtRQyOw2FJ0oNoDoGglTI2FrJGSNRAgoxAyMUBh6tAJwATDiHIyQLYUNF1CJgo56TtzP3D6kJNZUlwEx1MzRngEt4EE5y4VD8MqxnkSOrGZleG/ALaqpnW8nlSukUQ4ulVkgBnnpb/SDMwLyq2CLfhZo7OREng+sfb0TCKaj4KnqKXjEolUG1wGuD+eNLU8JNDCbxWKsaaLVspgbKrDRjRsuaum3RVBN32y3dXi6kSmishe9nIXGaDROl8ZZXAe4ftk40zrZdoxDLf22CKrpWzRO4a1soc0fmIZgGab9Sp2HsPW0n59SU3toJAhVZ3gIZiNVkXuV7cQyodLMiPCeJzIOQcKxeNAulVvHuGWLwgZPq/J0G9tfbF3FE6XBHuhlN3PBULPnjel6I5nZ98Z83xvZ9UbiQR1vrNtquI7FTG+5knbzFirB1E0JNDZBkczWBkPZ2sYuKOBRz+75BHXcIlaiTYlxgMjWxaWY9EQvBtA6jmkWeraXuVR13VN1sHLD3apbcSeg8IqEQ4DDsBj6QT0Oy7Ff8osxX89bAH2vjqipsanKqOxg/1ucdImT6eJkKpx0Fye9kwZovfqvYVW8CO9VBOKT3+vslA1fuLEV17qvd6dwWU3JOoP374UgeI+LbPJYvsrcC7ysVU8UzPkiF+EAy+zz83sX8C2JxYmAcJmw0s2BjffR5m1iHZhop11LvPS0CSFei4rXQXjFjuEFCqq4H+VvSRneqHZ5AfLwtYrj9QvueSt4pK2mLJms4JlW+ZMCMZ2y2SQF4rK4PFV550h6s6Lp3HWril9WQL/Qfgqw93Gq8rLACjMzZHtJ0AIsp0mk/KewNRoWHXKI5P8vhKU5OYxwegvIprY6NSSap/1xeVc5KW8qnvihpIzFtKSdlJQ2b/sd7VCFHe2z65NyrHQipRhBE7pYfgZjT60XpnFrXtb1uBiqKs/A+Tevx024W+XfphZxGhdD6+owbqYVtVTZZWCQx635zgVxd1eVD/t3yA6/CuK4muw8fcftRdOra3K627/HO6uyjMbF0CqqcTMt3vt3Pgg6xYeB4veAHtyqaf4N47j6gPBXud5oY0lmEsf3B1asNxBzkQ4WWfSrsH6Upu6kEJ4O2lunsbwnMmYvfJ4kUcLTFDh3WZJcyd+hHx5PByDf2ZpoHsMr8Nd7YRL+iGKr4PiyIPq+Px3A8uWdVutkwc2e5n8D)

![polygons.gif](https://images.zenhubusercontent.com/5d152e12c27d0c306f021863/aad0caa2-fb19-44f1-96e3-ba2a94e8a418)

## Circle entities
[View in Cesium Sandcastle](https://sandcastle.cesium.com/#c=xVh7b9s4Ev8qvADblSxalpymD9lMzpumbRZp+0dyDyAxBFpibLYy6aWopGni735DiXrYSg+Hwz0MJKRmhsOZ3zxIaTQY3IgB+sDkiuYrdMpVkrHckN4pep8jipKShKhGesVQwoRmCslbxGiyQku7zsnYHcvQ2EUbmT0spfCR0XEFK3L+gzXyVhnPkWIZ1fyOIS1LxYqKVK6zB1ApmKKapSiRhdCI5rlMeEm453oFwmCK3deHTUY3IpEi1+iOs3swjSDB7tEpy3mx9v9a0pybg6R8PpVCUw76bw7cyY1ACNWLU/DWgsBy0HFbiERzKRz3sZRDi4X8znJn+DbAw/BNgGE0w9j1b6U6A98c5JjVLiLHCNZUqxDKmC7Xgs6UJTJlsXmqRHEtZH6VtwRtqMrZudDOJ6pXfgWL4w7CIDAmd9VaMIn13IfQcM1Z7tM0dR5b3RuZc+MLimpYTqnSMKPi0L9Vcv2OLRUD5xxj2vXh3CvHcO6OxhhVxLElBobYNZxlGd/kLEKPXWdytuafuJBq9p3nUeXbCFxAA3R4FMDPD3BPnn79l+VXjC9XOkLj4BnmGpJFcZq17spMqtLTj3nmhK+D0eGrAKPAP2r/7QZDFjqDPInQLc1y1nK29XS7H4yMLqAA/r+xqGzYCwVCmn3XyILqa3mpFRdLZ9dhhG6hNkDq1/DlRqO1FDLf0IT9uieV64eMNbZfmA0vDcl/f35xsSdrQfwbT6FsIxTssUejT/Qbs0aXNuZrmmVQwvcrJtAPKddQ86AEg4xa7tG52DMsoRn77eEdzzUVCYP9Om3gM6PqPVWXIEOVE/pHDMA8grRBb/yAvTIJ8Nr9WZSbcVuGfDQYwq/pmL9foowvFFUPyNCHph9BR3DuqEK/zS7PDsfx6Zd3Z5fk5iAIx4cvj169fvN2kaTsdrn6+m0tNn+oXBd3998fftwc4O6K+N356RV53GJOggmfdll+xsRSrybc89zekusdyWRF1Uw73J0TPjFGnX02jHj2l6svYBMttIR9P51/ji9mV8S0t0+zv5dzMzXkL59J2fFKOjyY+eX5h/fnH+KPs8uP8cXZ5w9XH8l1gI/wa/wGhyEOxzg8xOERDl/h8DU0yjlmwjQ/0vRVhgWW7iO/dSQhpGNUSbs5EMV6Yfo0Ifphw8z58fT0DFW4eqXkfRnsM6Wk6fV5meBISE3LUlPsj4IryBmICzIOo41iCc+B55uDwKCiCPPzTcY1rDdEqDgLMtZE/IzFSdmk1/S7o7B2J5L0gbnm8y2DJoLuJE9RAM7KFy/A6bfupM6TGKfkeo4LEmAKfwn8LYgNA86IDQ6eERsCvCQ2MpPUmjKVExdwo7+MCQlOxLETE2fmLU2DOHESEnpOMp2GLqyM3QgIQU2YGQIr5Rde1pPP9uUXQMDU8/AReOJ5hftoPFiRbtJdJ3MwbFPkKwcOuaJyaauYLpRAqf9VcgFYApRbmxYxF7qXGpLIp6ejcYMSIAyaeANM3ACTNsAUNTAGyIk2qNABGWPd4KKIk4LVpZ/UIyEsUW6UEmVAACb34g4zNkxOYGvPm1gH6BZ3TvKO2e5jbSrYT/4UYNXYqhtbeWNr3Niagl9V8Fld2cWUTgqo7hLdhLDrYg6t+0LC2XJKc+a4k5T0Kx9wr01YkJeTxTGAsBgOKy0ZSY+PFy/CiTxxRO0oDiGM2UlMBLgpINTAUZ5uOZD9kQKO8UhubRCvNY6xwpDZXSh6UWwBkQ0SqkFCN0jwBokYUEgJGCFM6I0VgAuAkZZgxGTJdLyASmR4PHDSYeEOISVNTfUZEENJHOkp0AIe2FkpHINXjva44fB6ZsN7DW5hifV8O6ldQa1ycMlmARuVpb+R984YyC/CrfGzQmMnJ8p8IN27HzNgOgLOb0/AYW6sUuY5NM+H89aWR3NF1kXKIokzKZbVXGFmGl3Uco2WYVfEqBmq7bYJTz8yVVT2oleyjDHSGCetcdo8h+b5eeNUZ2fdM85oGXZFjJqhNsYJc4tbSPVPTDNgKSL9Wp1nYBtIv9yloQ6MkSBU7+EZMFupmjyobUeaMJEXisV3NONpDBKONhvtUql2lGtblGnwuC5Pt7X92dZVnSgt9kC33cwFQ9WeN6rvDSdq3xv1c2943xtuNup5o91Ow3W0yfSOK3k/b6ESVNOUQGMbFE50YzCUrW7tggIeD/SeT1DHHWIt2pYYBYh0U1yCcI8NUgCt55gksacHhYtF3z3RBKs03K27FXVCHMCpBUNohqAahmEzBnYcWn41ls/zDkA/qyOsGmzqMrId7L+Lk7Q4qT5OqsZJ9nGSO2lgrBf/Mayq9+S9ijD4lPc6PSXBMze26lr35fYULqs5WhfwQr5gyNzjEp092JemO2Yua/WJYnK+ykXYQBP99PTWBXwtsdoRELYJy90S2HQfbdolNoFJdto1N5eeLiE216Lq7RxeqVJ4VYMqHibl+1hhblS7vNDwzAscNdcvuOet4EhbTUk2WcGZVvuTAzGfktkkB+KyujzVeedwfL3C+dx164pf1kA/034qsPdxqvOywspkZkz2kqADWEnjhvLvwtZqWPTIsSH/byG05pQwwu4dINva6tUQa0/7Y3tXObE3FY/9YikRm1raiaV0edufaIcq7GmfXZ3YsdZpKNUImoyL9rsXeey8MEWdua3rqBrqKi/A+VcvozbcnfLvUqs4RdXQuTpE7bSmWpV9hgly1JnvXBB3V9X5sH+H7PHrIEb1ZOf0jboPba9uyPlu/452nmwZRdXQKaqonVbv/TtfCOH+fYAPpuXXkOP6a8Gf+XojlUaFyhzfH2m23kCcWT5aFMk3pv0kz+33BDQddZdOU36HeEqe+UyJkozmOXBuiyy75D+gBx5PRyDfW5pJmsJr75c7pjL6YMRW4fFFRfR9fzqCx+dXaimzBVV7mv8B)

![circles.gif](https://images.zenhubusercontent.com/5d152e12c27d0c306f021863/4c89e848-1e4e-4881-8346-6dcf563319f9)

## 3D Tiles
[View in Cesium Sandcastle](https://sandcastle.cesium.com/#c=vVkLb9s4Ev4rvADblWxatpymD9tMLptk2xzS9oDkdg+IDYGWGIutTHopKmk29X+/GYmSZTvdOyzuLkBAaWY4nPnmwYnS73SmqkPeCZ3yPCWH5+RGZiJH2mmS5ISTw6QiCUv0HVk4wZXOHhdagYAlmbgXGRkSrhLC81wukEwMvOoliXWmDbGaCB6nQak3yzXhlfKMz2HrHUggu9aOYv2pikG/JfdSPAhDGFHigZyJXBbL4JeS5k0P4vL9TCvLpRJmeuCPp2qq7jkcWRk9rt5iXSibg5andSlR6U4Mf3CuC2TeFSq2UivPf5oqUqvYPrtaDs8dKF4pSUhhshGZHqTWrvJRvw+Kg4W0aTEvcmHgNCuUDWK97Ge8MEI98OyLMP1FfXgPMOhV3vSX4EvfnZ3XIjUh+JxrNT2g1amJmBeLX6URd4YvxYjc8SwXbd51qh9+At8TqRa/6Kz4rtBZZeKzsii6rpBtQAly+5iJ70NzjewanBwOGBFriurYUhdxkQ3yWCgRrIxcSivvRR5AbnjulN1DeZaVuF9pnogEJS/uweormYPxkBGeT9gxcadidK8wwXKvOpCQOOVqIc4wJ2uic2yTENWW3Wyo9s/n+qvIvd7bAe2FbwYUVlyGfgDxu4AU9oiH0arNqHYRKBFb7gWtiYh1IiJ8q0RpLVQaiHkKUitucnGprPeB2zSoasnzO+FgUEOCP/3+Nb8XxKbCbcRKsqnMSVmkUrVYS76qt1XFcIsyMzirfB1vG1sVJqtjBBhDcFxsnjYGr3QuESIyanKAGwtPXB0Gd0Yvz8XCCEDMQ39vD2fdcg1nfn9ISUUcOuIAiW00KhtG5KkNEOSC+GqBitbTfr80PrD62hpIW28bTQKAKBT+MXy5Agi00vmKx+LHHakylxsXygQo8zf4+fLqakdWFzaDXvOrTGwKmgc77H7/A/8inO2lqfkSshY62EMqFPld66VIUAkFGbPYoUu1Y1jMM/HT4znkN1exgPNa5fZRcPMzN9cgw40XBkcCMD0KBpS8CQbiFSWD4LW/0beuH9ftFEKLzyHrNx0devX0wHk5PSgzqL4WgvauM71cQl5U3pC5iDm0OiLtj6hCkzzTD6jrQZsv5EFkWbO533Fn/Sf5VQnuJEEqheEmTh//Xd6dGsMfvVuyjarLQUpc3tFn2IctNiF/JDB8dn+4YZPZdlamQi5SzMpwi7zkVhjJs5ZP2KdKd97nmRe+HvQPX0F0g6Pqd7Ct1oWMtBrtDqvUt6v+1/eXNxfPZwlewtVLta7rNlr2zVbbbLfV/Wv0z90ZxI0OEPoW/OKeZwUAVbvSHHUnuIWLlRIj8iKz/tYuTFfsaiu4ikXZX10LdLuChbB/NxrY9hGmCnflwjQx60PHHbcVGQEb1PMRKnv1Xaa12W7bpEMgcH4VvUEZuqAsz1c1oOu1wxZRJQjsVK1JifDWjOJVpdvv9OCnmdr+dk0yOYeKeCRI72Hc4CbwcPD56fT64nAYnX06v7hm04NBODx8efTq9Zu38zgRd4v085elWv1mclvcP3x9/B0mi/aO6Pzy7IY9ralkg7GctFlBJtTCpmPZ7fp7W263JCE9zKn1pD9jcoxGXXxERnT6j5tPYBMvrIZzP1x+jK5Obxherh9O/1k+4yOSP31k5X1b0uEFn68v3/18+S56f3r9Prq6+Pju5j27HdAj+pq+oWFIwyEND2l4RMNXNHwN1/SMCoVXL2tyRlBFtf8k7zzNGGsZVdKmB6pYznGoZMw+rgRMv+Lbt2eoyrepgWaHWX1hjMbBNC+vI6K05eX9aMRvBYxpSXlDo8NkZUQsc+AFOLUiKoaJIF9l0sJ+JEIPcSBTy9T3WJKVubbkXz1DYWDSbB+YWzlbw0wjyL2WCRmAs/rFC3D6rT+u8ySiCbud0YINKIffGH7nzIWBZswFh54yFwK6YC4y48SZMtFjH3DjPwwZG5yoYy9i3ml3gbf6iRezsOvFk0now87IHwFhUBNOkSBK+Xk325PPduXnQKC826VH4Em3W/hP6EHK2kl3G8/AsFWRpx6MWEXl0tpVbxJ81lIBlgDl2qVFJJXdSw3N9LdvR8MGJUAYNMkGmKgBJmmAKWpgEMixRVR4hw2pbXAxzEvA6tJP3mUhbDH+KGEGQQCm7EYtZoRMyeDobnfsHOBr2pojW2b7T7WpYD/7y4Caxlbb2CobW6PG1gT8qoIv6souJnxcQHWX6MZM3BYzGLSuNFzYZzwX0IsStl/5gHttwpy9HM+PAYR5r1dpyVhyfDx/EY71iadqR2kIYcxOIqbATQWhBo7p2g0Hsn9kgIMe6bUL4q2lETUUMrsNxV4UN4DoBgnTIGEbJGSDRAQoJAyMUBh6tAJwATCSEoyIwV0RzaESBR12vKRX+D1ISaypfQbEUDNPdw1oAQ/cUykcgVee7UrkyPrJhfcW3KKa2tl6XLtCNsrBJZcFol+W/ko/eEMgvwjX6GeFxlZOlPnA2n95CATTUzDddBWMKGiVwfcQ3w9nG1ueMmhgtkjESNNMq0X1bKjARjfacFFLry2CanoGLrY6PPuRqaKyE72ShcZoNE474yy+h/j+vHGmdbLdMw619NoiqKZn0TiFw9hcmz8wDcEyTAe1ui7C1tFBeUpD7aCRIFSf0UUwN1I1uVPbTiwTKofhI4KRRiYRSHgWD9qmcusZ37UobPC0Lk9/Y/uzrau6UTbYA911Mx8MNTvemH1vJDO73pjveyP3vZF40J431m81XM9iprdcyffzFirBNE0JNG6CIpltDIaytRu7oICHHbvjE9Rxi1iLbkqMA0S2KS7FZFd0EgBtzzHNoq7tFD5V++6pJlil4X7drbgXUhjYcQlxGVRLL2zWgVt7jl+t5fusBdD36oiaBpu6jFwH+9/ipB1OZh8nU+Ok93HSW2mA1qv/GlbVV5qdikB8yrnOTtjgmYmtGus+3Z3BsJqTZZHj37QE57jYZo/uS8e9wGGtvlEw56tchAMss9++vfUBX0esTgSEXcJKvwQ22UWbt4lNYOKtdi1x6GkTIhyLqj8y8Iud582hintx+RGlwIlqmxciD7+6cBy/YM5L4UpLJywbp3Cn1f7kQMwn7HScA3FRDU913nmS3qY0n/l+XfGLGuhn2k8F9i5OdV5WWGFmRmwnCVqAlTSJlD8L20bDfI8cIfn/C6Ezp4QRTm8BuamtvRoSm9v+2M0qJ25S6YofHGUkJo524iht3vo72qEK97Sf3py4tdaJlGoFTeii++uYPbX+YBq1nl1dj6qlrvICnH/1crQJd6v829QqTqNqaY0Oo81jTXUq9xkY5FHreWtA3N5V58PuDLnHr4M4qh+2bt9R+2XTqxtyvt2/R1tvroxG1dIqqtHmsfrackAPJuU3lOP6k8Rf5XKljcV/P3hB0LdiuYK4irw/L+IvwgZxntffGCb99tZJIu+JTNgz/0MhccbzHDh3RZZdy9+h5x1P+iC/tzXTHP9Z8OlemIw/olgaHl9VxCAIJn14fX6n1Tqbc7Oj+V8)

![3d.gif](https://images.zenhubusercontent.com/5d152e12c27d0c306f021863/13a95049-a023-4d9f-b340-9b52f1303d4b)

## Comparison:

You an see that 3DTiles are easily the fastest among the three. It takes ~2 seconds for the polygons and circles to load. Even the labels take longer to render than the 3D tiles.

There are still some issues at the pole where shapes and labels overlap. We can play around with making the labels smaller text at the pole.

I used random colors just to demonstrate the individual geohash boxes. These could be colored to correspond to the count number.

**Pros of entities (polygons, circles, etc):**
- Can easily change which entity type with just a few lines of JS code (switch up to triangles, ellipses, points, lines, etc etc)
- Don't have to host or maintain a 3d tileset
- Since entities are drawn in the client code, we only draw the entities that we need to. (i.e. unpopulated geohash tiles can be skipped during rendering)
- Shape and size of entities can be based on the associated search result number 
- Provides an easy transition to drawing other things on the map (geographic bounding box polygons, etc)

**Cons of entities:**
- Much slower
- Can't click on them


**Pros of 3D Tiles:**
- Much faster
- Can display thousands of tiles very quickly compared to entities
- Can click on tiles (we may want a feature in the future to select tiles to limit a search to or to download data from)

**Cons of 3D Tiles:**
- Can't show outlines (without drawing polygons on top which is too slow to look good, I tried it)
- Need to maintain and host a 3D Tileset
- Less extensible and changeable in the future (e.g. if we want to switch to circles, we will need to write new code that draws them)

**Comment by robyngit** [comment]
Cool to see the 3D tile geohashes! 🎉 Have you tested how performant each method is when removing/redrawing geohashes? In my initial experiments, everything slowed down a lot when I started removing and re-adding geohash entities at different zoom levels.

Just a few comments on some of the pros/cons:

> Cons of entities ... Much slower

Another option is to use primitives, which are faster than entities. [Here](https://cesium.com/blog/2016/03/02/performance-tips-for-points) is a good overview comparing point entities vs point primitives.

Performance can also be improved if events are [suspended, then resumed](https://cesium.com/learn/cesiumjs/ref-doc/EntityCollection.html#resumeEvents) during the creation/removal/updating of entities

> Cons of entities ... Can't click on them

Entities are clickable, but to see a table of attributes in the way that you can see in your 3D tile example, you just need to add [properties](https://cesium.com/learn/cesiumjs/ref-doc/Entity.html#properties) to the entities.

> Cons of 3D Tiles ... Can't show outlines (without drawing polygons on top which is too slow to look good, I tried it)

There is a way to create the appearance of outlines on 3D tiles using what Cesium calls "silhouettes." In MetacatUI, we show outlines around individual 3D tile features when they are clicked. See: https://github.com/NCEAS/metacatui/blob/dc595fb65cf8a60ccb6090678aadae8762581588/src/js/views/maps/CesiumWidgetView.js#L375-L405


Related info: https://github.com/NCEAS/metacatui/issues/1942#issuecomment-1071518384

**Comment by robyngit** [comment]
Since we already have a Geohash layer under development, we can continue any further discussion on approaches to displaying Data Catalog results on the Cesium map in https://github.com/NCEAS/metacatui/issues/1942
