### ISSUE TITLE
EML Drafts unescape XML entities

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1944]
Steps to reproduce:
1. Copy the following text into a field in the editor, e.g. the abstract: `• Amory, C., Kittel, C., Le Toumelin, L., Agosta, C., Delhasse, A., Favier, V., & Fettweis, X. (2021). Performance of MAR (v3.11) in simulating the drifting-snow `

2. Submit the dataset with that text in the EML. Note that the ampersand character was escaped correctly by the editor.

3. Go to the DraftsView and Download or Copy the draft. Open the draft EML in a text editor and note that the ampersand is *not* escaped.

When I inspect in the developer tools the EML string that is locally saved to `localforage`, I see that the ampersand *is* escaped. So something is happening during the Download and Copy process that is unescaping XML entities.

This is causing issues when the ADC data team is using the draft XML file to reupload the EML to Metacat.

**Comment by amoeba** [comment]
Thanks for filing this @laurenwalker. I'll have a look.

**Comment by amoeba** [comment]
I think I've got it fixed in https://github.com/NCEAS/metacatui/commit/9479caefdcca9e83151185ed8db417f4aed1f809. See the commit message for more info.

To verify my change, re-trace the initial steps above and see the Download, Copy to Clipboard, and Download All buttons produce valid XML. I've moved this into Needs Review/Test in case you want to have a look @laurenwalker.
