### ISSUE TITLE
Error (500) when using the sliding publish date

### ISSUE THREAD

**Issue by helbashandy** [NCEAS/metacatui#2165]
**Describe the bug**
The publish date filter is no longer working, it seems like the query contains a trailing backslash of certain characters which Solr errors on.  It might be possible that this is a regression due to Solr version upgrade. 

**To Reproduce**
1. Go to [knb dev](https://dev.nceas.ucsb.edu/data)
2. Click on year filter then publish year. 
3. See error

**Expected behavior**
Search filter to work with no errors. 

**Screenshots**
![Screenshot 2023-07-18 at 1 19 01 PM](https://github.com/NCEAS/metacatui/assets/47407500/d49c14e4-5ab2-48a8-9eba-46c55864760d)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22]  111.0.5563.146

**Comment by robyngit** [comment]
Thanks for the report @helbashandy! This has been fixed in the latest version of MetacatUI. The dev KNB is still running an older version at the moment. You can see the fix in action on the production KNB: https://knb.ecoinformatics.org/data

Please re-open this issue if you're still seeing this problem on the newest MetacatUI :)
