### ISSUE TITLE
Using fact that Markdown supports inline HTML to have iframe on portals possible ?

### ISSUE THREAD

**Issue by yvanlebras** [NCEAS/metacatui#2212]
**Describe the feature you'd like**
Having the possibility to use an iframe HTML tag on markdown pages from portals to embed external websites

**Is your feature request related to a problem? Please describe.**
It seems markdown can do it, but testing it on a portal don't works. I guess there is a security ""firewall"" on metacatui who avoid this? Can we deactivate such ""firewall"" easily? Or maybe there is ohter ways to embed external web content into portal markdown pages ?

**Comment by mbjones** [comment]
Hey @yvanlebras -- I agree that would be great. The constraint is due to security issues for executable content and XSS attacks. Here's a quick overview of some of the issues: https://showdownjs.com/docs/xss/  In metacatui, what is filtered out is somewhat configurable, but @robyngit may have thoughts on what is and isn't feasible. If you control and trust who is editing the portal, then its reasonable to open it up further, but for us most of our sites allow arbitrary people on the internet to create and edit portals, which means we need to be more careful. We have several related feature requests, such as to allow embedded visualizations such as Shiny apps. See https://github.com/NCEAS/metacatui/issues/1383

**Comment by robyngit** [comment]
@yvanlebras we have been discussing this issue for a long time: the need to enable more types of content in portals vs. the risks involved with embedding external content.

One way to mitigate the risks and still enable `<iframe>` content could be to allow content _only_ from a set list of trusted domains. We could either enforce this at the point at which the markdown is rendered into HTML (browser-side) or when the request is made (server-side, via a [Content Security Policy (CSP)](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP)). The downside is that this would involve compiling a list of domains that have content that users want to include,  ensuring those domains are trustworthy, then monitoring them over time, all of which could become tedious and time consuming...

I'm open to other ideas on how we achieve this! What types of external content are you hoping to be able to include in portals?

**Comment by robyngit** [comment]
@yvanlebras I'm going to merge this issue with #1383, supporting embedded viz tools in portals. This issue is on our road map. If you have more ideas about how to safely embed visualizations from external sites, and what types of visualizations would be useful in addition to Galaxy workflows, please add your comments to #1384. Would love to hear your ideas!
