### ISSUE TITLE
Layers list polish

### ISSUE THREAD

**Issue by yvonnesjy** [NCEAS/metacatui#2277]
- Move visibility toggle to left
- Change legend to settings button on hover
- Drop layers icon

Mock: https://www.sketch.com/s/eea6a4f3-5c59-40e6-bf7f-64edc511e4cb

**Comment by yvonnesjy** [comment]
@robyngit Do we want to limit these changes to PDG? Or are we okay with applying them to all portals?

**Comment by robyngit** [comment]
> Do we want to limit these changes to PDG? Or are we okay with applying them to all portals?

@yvonnesjy, I have a few questions myself before I can answer.

> Drop layers icon

In layer lists that are NOT grouped, will the icon be dropped or not? If we continue to show icons for non-grouped layer item, will the visibility toggle stay on the right?

> Change legend to settings button on hover

I don't understand this - the legend will only show when you hover over the layer settings button? Will it not work on touch devices then?



*(Reminder to update the documentation for the layer icon property of the map config if the icon will be deprecated or not show in some circumstances)*

**Comment by hngrtr** [comment]
[The Figma prototype](https://www.figma.com/proto/9R80DBDAMQtOsu8y1HkAVT/permafrost-discovery-gateway?page-id=60%3A41271&type=design&node-id=70-47595&viewport=143%2C173%2C1&t=0T3YWZspyuioCeg5-1&scaling=min-zoom&starting-point-node-id=70%3A47595&mode=design) shows what I'm thinking here for desktop. Clicking a layer list item anywhere will toggle it's visibility, except for the gear icon that triggers the layer detail overlay. 

For mobile, I was thinking the primary tap action is toggling visibility like on desktop. The gear icon would shown when a layer is visible. 

For layers that aren't grouped, you could continue to use the icons that are there today, but have them double as visibility indicators. That way clicking a layer toggles visibility the same way whether or not the layers are grouped. You could use the light grey treatment that the PDG eye icon uses when a layer is off for the icons on a portal like DRP. When you click the DRP layer to turn it on, the icon would then turn solid and be blue (or whatever unique theme color the portal specifies).

As far as the legends go, the full versions are in the layer detail overlay. The swatches are shown when a layer is on more for a "palette overview" and to distinguish between the palettes being used in other enabled layers. Since some of these datasets (particularly categorial ones) can potentially have a lot of values in a legend, the interactive thumbnail won't scale up to support that.

I'm not dead set on any of these answers and I hope we'll get some feedback in our interviews next week, but I'm happy to talk about these things in more detail anytime.

**Comment by yvonnesjy** [comment]
The prototype is looking great Doug! And good idea to use layer icons as visibility indicators for ungrouped layers.

That said, @robyngit does what Doug described sound okay to you for use cases outside PDG?

And @hngrtr since R1 is coming up real soon, I'll go ahead with the current prototype. I can update it if anything comes out of the interviews that's easy to fix. Otherwise, we can discuss. That sounds good?

**Comment by robyngit** [comment]
Love the prototype @hngrtr!!

@yvonnesjy agree that these changes should applying to all portals and all uses of the Cesium map (including the data catalog). When you're developing, could you make sure to test how the changes look in the scenario where a data layer fails to load for some reason? The current behaviour is that there is a warning icon with a tooltip giving some details about the failure. Some other behaviour is fine, as long as it's handled in one way or another.

I think these small changes will have a big impact on the look and feel! Really excited to see this!

**Comment by yvonnesjy** [comment]
@hngrtr For the ungrouped cases, I'm running into a scenario in testing that some layers don't have an icon defined. We'll need a default icon in this case since it'll be doubling as the visibility toggle. I'm thinking of using the layers icon again, which is the default for layer group icon as well. WDYT?
<img width="63" alt="image" src="https://github.com/NCEAS/metacatui/assets/8570665/d11dd3e1-22fb-420e-b6e1-10567e835e12">

**Comment by yvonnesjy** [comment]
Documenting the following fixes that we will implement as a part of the April release (R1):

- Don’t wrap layer badges. [Bug report](https://docs.google.com/spreadsheets/d/14QBov-vecNkz_PUVc7yY3nTozO4NR8jTRKUeEbhilQw/edit#gid=1502293129&range=5:5)
- Don’t wrap layer labels. [Bug report](https://github.com/NCEAS/metacatui/pull/2318#issuecomment-2014123178)
- Widen layers panel
- Move layer details panel to right hand side
- Don’t add paddings in settings button when legend is not available. [Bug report](https://docs.google.com/spreadsheets/d/14QBov-vecNkz_PUVc7yY3nTozO4NR8jTRKUeEbhilQw/edit#gid=1502293129&range=7:7)
- Non-PDG: Make layer icon more obvious as a visibility state indicator when layers are not nested. [Bug report](https://docs.google.com/spreadsheets/d/14QBov-vecNkz_PUVc7yY3nTozO4NR8jTRKUeEbhilQw/edit#gid=1502293129&range=8:8)

**Comment by yvonnesjy** [comment]
For "Widen layers panel", Doug has a version that works on PDG, but not so well on ADC's 3-part view because the map panel is much narrower. Talking with Robyn to figure out a best path forward now. While that's happening, are we okay with releasing R1 without this fix and address it in R1.5 instead?

Implications:
Because the new theme keeps the layer names in one line, long layer names get truncated with ellipsis. Users can still see the full layer name if they hover over it, or open up the layer details panel.
https://github.com/NCEAS/metacatui/assets/8570665/5217e660-3f47-41d5-993d-c2b5907e6c6b

**Comment by robyngit** [comment]
Let's move "Widen layers panel" to 2.29! Otherwise, everything in this issue is complete 🎉🎉🎉
