### ISSUE TITLE
Base layer updates

### ISSUE THREAD

**Issue by yvonnesjy** [NCEAS/metacatui#2360]
1. Support saturation as a layer config to allow grey scale
2. Update Cesium background to a light color, instead of royal blue
3. Add OpenTopoMap as a base layer

**Comment by yvonnesjy** [comment]
@hngrtr Can you comment on what OpenTopoMap is for? Do we need both that and OpenStreetMap? Is there a ticket for it already in https://github.com/PermafrostDiscoveryGateway/pdg-portal/issues?q=is%3Aissue+is%3Aopen?

**Comment by hngrtr** [comment]
Having more base layer options is (almost) always preferable. Sometimes a feature is easier to visualize on a topo map versus the flat OSM.

**OSM**
![image](https://github.com/NCEAS/metacatui/assets/70544298/1a89ad6f-1eb5-48f7-8959-51c85f72c5b5)

**OTM**
![image](https://github.com/NCEAS/metacatui/assets/70544298/2af2e9f5-7fbb-4d9e-8267-dd4cb2bb21c4)

**Comment by robyngit** [comment]
> 1. Support saturation as a layer config to allow grey scale

An issue for this feature exists here: https://github.com/NCEAS/metacatui/issues/1887. It's a little more comprehensive than just saturation, so we can make a separate issue for saturation only if needed. But otherwise, let's use that issue to track the progress on this feature.

> 2. Update Cesium background to a light color, instead of royal blue

Here is an issue for changing the background color of the globe: https://github.com/NCEAS/metacatui/issues/1904 It includes ideas about allowing users to change the color themselves, but I think it's ok if we just make it a configurable color in the map config to start?

> 3. Add OpenTopoMap as a base layer

Since this just involves an update to the PDG portal document, and not the metacatui software, I've moved this issue to the `pdg-portal` repo. But please open a new issue if there are changes to MetacatUI that need to be implemented to support the new base layers: https://github.com/PermafrostDiscoveryGateway/pdg-portal/issues/91

Since all the tasks here are covered in other issues, this is essentially a duplicate and so I will close it. I'll be sure to move other info from comments above to the appropriate issues.
