### ISSUE TITLE
Author name is mixed up in citation and under the title of data package if it's an organization

### ISSUE THREAD

**Issue by justinkadi** [NCEAS/metacatui#2548]
**Describe the bug**
When a data package has an author/creator name that is an organization instead of a normal First/Last name, the order of the words can get mixed up in the Citation and underneath the title of the data package.

**To Reproduce**
2 Examples where the Creator name is different in the Creator section and underneath the title:
[Fresh Eyes on Ice Citizen Scientists](https://arcticdata.io/catalog/view/urn%3Auuid%3Aba49ca49-50eb-43a0-9efb-408fdb8fc21d)
[Alaska Department of Fish and Game](https://arcticdata.io/catalog/view/doi%3A10.18739%2FA2PZ51P09)

**Expected behavior**
We expect the author name to have words in the correct order for these organizations. 

**Screenshots**
<img width="1098" alt="Screen Shot 2024-10-11 at 11 13 56 AM" src="https://github.com/user-attachments/assets/a677987d-3052-4b6e-9ec5-2a36d576ceb5">
<img width="922" alt="Screen Shot 2024-10-11 at 11 14 21 AM" src="https://github.com/user-attachments/assets/b0e0f770-cf85-4531-819b-93118640e931">
<img width="391" alt="Screen Shot 2024-10-11 at 11 14 50 AM" src="https://github.com/user-attachments/assets/081602d7-8805-4928-aeb8-2f0d6d2150c5">
<img width="919" alt="Screen Shot 2024-10-11 at 11 15 05 AM" src="https://github.com/user-attachments/assets/b6ace74c-d0cc-44e9-b6aa-49597adc0136">

**Comment by robyngit** [comment]
The issue is that we're identifying the short, lower case words as "[non-dropping particles](https://docs.citationstyles.org/en/v1.0.2/specification.html)" in a last name. In the first example, we parse the organization name as:

```js
{
    "family": "Scientists",
    "non-dropping-particle": "on",
    "given": "Fresh Eyes Ice Citizen"
}
```


Since it's [difficult to differentiate an organization name from a human name](https://github.com/NCEAS/metacatui/issues/2106), and [we're not following the standard APA format of "Last Name, First Initial" anyways](https://github.com/NCEAS/metacatui/issues/2106#issuecomment-1468594135), I think we should not bother trying to parse the author names when they're given as a single string.
