### ISSUE TITLE
Metacatui display of metadata pages miss some formatting

### ISSUE THREAD

**Issue by yvanlebras** [NCEAS/metacatui#2561]
**Describe the bug**
Previously, when going on a Metacatui data page, there was a nice diplay of the metadata content, organized in sections, for example each entity was separately displayed with relative content in it (attributes listing and relatevie atribute infroamtion) but now, it seems we have somethnig like unorganized lists of elements. This is the case in our French catalog but seems to be the same on search.dataone catalog also.

**To Reproduce**
1. Go [here](https://search.dataone.org/view/https%3A%2F%2Fpasta.lternet.edu%2Fpackage%2Fmetadata%2Feml%2Fedi%2F876%2F8) and see formatting (you can also go [here](https://data.pndb.fr/view/doi%3A10.48502%2F8bb5-pk85)
2. Scroll down to search entity field... 
3. There is no entity field (data table or other)

**Expected behavior**
A clear and nice section to describe each entity content with list of each attribute and for each, detailled related to it.

Like in this screenshot:
![Image3](https://github.com/user-attachments/assets/93475915-d772-4c4d-988b-d6373650bb13)

**Desktop (please complete the following information):**

- OS: Windows
- Browser Firefox

**Comment by robyngit** [comment]
@yvanlebras the dataset is displayed like this because MetacatUI is rendering the content given information from the Solr Index, rather than from the [view service](https://releases.dataone.org/online/api-documentation-v2.0/apis/CN_APIs.html?highlight=view#CNView.view). It's doing this because the view service is returning an empty string rather than HTML, so it resorts to rendering from index as a fallback. This is a backend problem, maybe something went wrong with indexing this dataset, or some other problem occurred while generating the view HTML. I'm going to close this for now, since MetacatUI is responding as it should. Let me know if you have questions or if I can pass some on to the backend team!
