### ISSUE TITLE
Make the entity editor button more obvious

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#261]
We may need to add a text link or use the status column to indicate better that there is an entity section "hidden" in a modal window.

**Comment by laurenwalker** [comment]
Here is an idea for how to make the button more obvious... When the file is successfully uploaded but has no attribute info, the status icon and edit icon are red. When the file is successfully uploaded and has attribute info, we show the red icon.

This wouldn't prevent a Submit/Save since some file have no attribute info.

I also suggest we add "Describe" text next to the edit button to further communicate what its purpose.

![entity-status](https://user-images.githubusercontent.com/6643222/30280188-20a977c0-96dd-11e7-8736-e1dfb2b15db9.png)

**Comment by csjx** [comment]
Hi @laurenwalker : We're totally on the same page here - over the weekend I thought we should use the word `Describe` as well.  Looking ahead, I know we're going to need to support more actions, though, and I suggest we go back to the original design with a dropdown menu.  In particular, the `Replace` and `Copy` actions are on our TODO list.

I feel like things are a little crowded with the edit icon + text + remove icon.  I do like the icons, so we could keep them, but here's a quick mockup of the dropdown.  I used orange to to indicate "something to attend to", and figured we could use red when there's a problem in the described content.  Otherwise, when all is good, we use a white background, with the green status icon.  Let me know what you think.
![describe-entity](https://user-images.githubusercontent.com/1437565/30285590-d0fa1cc6-96db-11e7-9565-2f9f74e7b028.png)

**Comment by mbjones** [comment]
I also like this approach.  I like using a button/dropdown, but prefer keeping the pencil icon which I think will help clarify the intent.  I also like the orange over the red, as red generally means error.  Sounds like we're all on the same page, and any of these proposals would improve the UI.  Thanks,

Matt

**Comment by csjx** [comment]
Sounds good. Yeah, we can easily add the icons for each action on the left of the buttons. To make the folder and file buttons consistent (same width), I think we will eventually want to make the `+ Add Files` button a dropdown too, since we will be supporting other actions at the package level.

**Comment by laurenwalker** [comment]
FYI, I'm working on this now

**Comment by laurenwalker** [comment]
Here is the new edit button and status icon for objects that don't have attribute metadata. (Each object will automatically have an EMLEntity created with an entityName and entityType, so we check for attributes instead.)

I can see this being a little confusing when files don't have attributes to describe, such as images. In the future, we could either:

a.) Only show the yellow warning status icon and yellow "Describe" button when the entityType is not an image or other file type that likely won't have attributes
b.) Let the user indicate that there are no attributes for a particular file, so the warning status goes away

![new-edit-button](https://user-images.githubusercontent.com/6643222/30457696-623294e2-9976-11e7-84b5-ddaa8b8c3ef8.gif)
