### ISSUE TITLE
In citations with many authors, make the "et al." text a link that expands the full author list

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#264]

**Comment by mbjones** [comment]
That could work for the display, but we also need to be sure that the "Copy Citation" includes the full author list in the copied citation.

When designing this feature change, we might want to consider different solutions for different parts of the UI. The datset landing page seems like a good place to display the full citation always, whereas the search results listing might be best if we use the standard journal approach of using et al. for any list of 3 or more authors (e.g., `Jones`, `Jones and Smith`, `Jones et al.` are the only three formats that are traditionally used when abbreviating).

**Comment by robyngit** [comment]
## How it works now

Decisions about how the authors are formatted in the `MetadataView` AND the search `SearchResultsView` are made in three areas of the `CitationView`, all under the render function:
- If the model (`CitationView.model`) set on the view is a `CitationModel`, then the authors are formatted here: https://github.com/NCEAS/metacatui/blob/26e1a46bd428522b43e6ba696109dfee710eb1a2/src/js/views/CitationView.js#L80-L122
- If the model is not a `CitationModel`, but there is a model set on `CitationView.metadata`, then the authors are formatted in one of two places:
  - If the metadata model is an EML model, the authors are formatted here: https://github.com/NCEAS/metacatui/blob/26e1a46bd428522b43e6ba696109dfee710eb1a2/src/js/views/CitationView.js#L152-L182
  - Otherwise, if the authors are formatted here: https://github.com/NCEAS/metacatui/blob/26e1a46bd428522b43e6ba696109dfee710eb1a2/src/js/views/CitationView.js#L185-L210

Besides the `MetadataView` and the `SearchResultsView`, the `CitationView` is used in six other views the: `CitationListView`, `MdqRunView`, `MetricModalView`, `ProvChartView`, `RegisterCitationView`, and the `EML211EditorView`

The `CitationView` doesn't use a template, but creates each HTML element and adds classes in the render function as needed. E.g.:
https://github.com/NCEAS/metacatui/blob/26e1a46bd428522b43e6ba696109dfee710eb1a2/src/js/views/CitationView.js#L224
- Using a template would not only make this view consistent with the pattern we use in other MetacatUI views, but it would facilitate more easily making display changes. We could also easily switch out the template in different circumstances.

The copy citation button works by highlighting whatever text is in some targeted HTML element and adding it the the clipboard. To do this, it uses a library that looks for an element ID that is set on the button's `data-clipboard-target` attribute (see https://github.com/NCEAS/metacatui/blob/main/src/js/templates/metadataControls.html#L4)

## How we can update it

Here is a path forward we can take to create the expandable author list:

- [ ] Create a default `citationView.html` template, to which we pass variables to insert. Remove the creation of HTML elements from the render function as much as possible.
- [ ] Remove the formatting of the authors from the render function. Pass the author list to the template, and allow the template to create the author string.
- [ ] Add an `expandable` boolean option to the template. When it's true, and when there are 6+ authors, make the "et al." text a link that expands the full author list. (If there is no bootstrap class that works for this type of expandable section, then the click/expand behaviour will need to be controlled in the `CitationView`)
  - When `expandable` is false, just show the et al. like we currently do
  - To decide: when the list is expanded, we presumably remove the et al. text. What should the user click to collapse back to the truncated author list? Perhaps add an icon?
- [ ] Update the behaviour of the copy citation button so that we copy the complete citation, not the truncated et al. version.
  - To decide: should the button first expand the citation, then copy it? Should citation be collapsed again after copying?
  - The button must work even if there is not an expandable section
- [ ] Add a boolean option to the citationView (e.g. `expandable`) that decides whether the template is rendered with the expandable section or without (when there are 6+ authors). Default to False. Set to True for the `MetadataView`. 
- [ ] Test how the citations appear in all eight views in which the CitationView is used, and with 1, 2, 3, and 6+ authors.

Optionally, we should also:
- [ ] Make the whitespace / indentation consistent in the `CitationView`
- [ ] Add JSdocs to the `CitationView` (currently there are none)
- [ ] Remove the unused `getAuthorText` function from the `MetadataView`

**Comment by vchendrix** [comment]
@robyngit It is exciting to see that the citation functionality is being refactored!  I wanted to point out that there is a [ticket](https://github.com/NCEAS/metacatui/issues/567) that we submitted a while back to be able to format the citation differently.  What  you are doing here might address this but I wanted to point you to this issue ticket just incase there are additional things you may be able to consider in this refactor.

**Comment by robyngit** [comment]
This is really helpful, @vchendrix, thank you! I think addressing both these issues at the same time makes a lot of sense.

**Comment by robyngit** [comment]
Update: The CitationView is tricky to make updates to at the moment since it formats a whole bunch of different models (EML models, solr results, Citation models, etc.) in a whole bunch of different ways depending on context. To resolve this, the plan is to add on to the CitationModel so that the model attributes can be populated from different sources (EML, Solr result, data object, etc.), not just the results from the metrics service. The Citation View will then render only the Citation Model. All of the logic that maps various model attributes to parts of a citation will be moved from the CitationView to the CitationModel.

This will hopefully achieve  the following:
- make the CitationView consistent with how we separate model vs view logic in MetacatUI
- make the rest of the steps for this issue much more straight-forward
- provide a solid foundation for eventually implementing more flexible and configurable citation formats (https://github.com/NCEAS/metacatui/issues/567)

**Comment by mbjones** [comment]
Sounds great!

**Comment by robyngit** [comment]
Update:

The Citation model now has new functionality for populating its attributes from other models used for citations. I've made it modular so that it's easier to modify how attributes are populated, and which attributes we pull in from source models (e.g. the "project" field, see https://github.com/NCEAS/metacatui/issues/567).

The CitationView only renders content directly from the CitationModel, but can still be initialized with other types of models. (These are just passed to the CitationModel, which handles pulling in the right content). It still accepts both the "model", "metadata" and "id" init options so that it is backwards compatible. All HTML creation has been moved to a new template.

The CitationView currently works for the most common use cases, such as in the search results and the metadata landing page, but there's work to do to cover all contexts and render all available information, like the "Cites Data" list from the citationMetadata attribute.

Once this is done, I will add a template option for an expandable list of authors!

**Comment by robyngit** [comment]
The Citation view & model still need review, and the CitationModel needs unit tests, but otherwise they are both at a state now where we can easily add a template with an expandable section to show all authors.

While updating the view & model, I was able to make some other minor improvements:

### Switch from using `<span>` tag to `<time>` tag for dates in citations. (more semantic)

**Before**:
```html
<span class="pubdate">2017. </span>
```

**After**:
```html
<time class="pubdate" datetime="2017">2017. </time>
```

### Improve formatting of strings returned from the metrics service, remove curly braces.

**Before**:
<img width="600" src="https://user-images.githubusercontent.com/26600641/217613172-834c7d0d-1e03-4a86-b168-72bf6cfe81ae.png">

**After**:
<img width="600" src="https://user-images.githubusercontent.com/26600641/217613346-4a583b16-c18a-4ff7-934e-fa618ed60a27.png">

### Add date and title to citations shown in the prov popup

**Before**:
![Screen Shot 2023-02-08 at 13 28 09](https://user-images.githubusercontent.com/26600641/217619825-0eea81ac-b27b-4ed9-9107-a6924dc3a64a.png)

**After**:
![Screen Shot 2023-02-08 at 13 28 19](https://user-images.githubusercontent.com/26600641/217619793-4a423f79-c179-46ff-968b-4df1b15db09b.png)

**Comment by robyngit** [comment]
I'm currently working on designing and building the new expandable author list layout. I've included some images showing the direction that I'm heading with it and welcome any and all feedback at this stage!

## Before
Here is an [example dataset](https://arcticdata.io/catalog/view/doi%3A10.18739%2FA2BN9X45M) as it's currently displayed on the ADC. It's not clear that there are so many contributors to this dataset. In fact, there are 46!
<img width="1017" alt="before" src="https://user-images.githubusercontent.com/26600641/218203417-97bd300d-e9e8-4726-acfe-414fc7a55913.png">

## After
Here is the new WIP design.

When a user lands on a page, by default, as many authors as possible are displayed, plus the last author preceded by and ellipse. Bold, highlighted text at the end of the list indicates how many more authors there are for the dataset.

<img width="1017" alt="collapsed" src="https://user-images.githubusercontent.com/26600641/218203445-a91246eb-1316-4a59-b8dc-7e6490f98f9b.png">

Either the `more authors` button or the `...` ellipse text can be clicked to expand to see the complete list:

<img width="1017" alt="expanded" src="https://user-images.githubusercontent.com/26600641/218203450-b4302a5c-73c0-427a-aa61-3222f59a8e4e.png">

The "Cite this dataset" button below can be clicked to bring up a modal that shows the complete citation with all authors

<img width="1017" alt="citation modal" src="https://user-images.githubusercontent.com/26600641/218203447-dba97379-740d-4bb3-a1d9-27d68254577e.png">

## Other details
- This design is based on layouts that are common in online scientific journals. In every example I could find, journals use the same collapsible/expandable list to accommodate  publications with many authors. Here are a few examples with links to articles that have too many authors to display at once: [Nature](https://www.nature.com/articles/srep22219), [Science](https://www.science.org/doi/10.1126/science.abd2438), [The Lancet](https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(23)00129-0/fulltext#%20), [NEJM](https://www.nejm.org/doi/full/10.1056/NEJMoa2214403), [Cell](https://www.cell.com/cell/fulltext/S0092-8674(22)01577-X),  [Cancer](https://acsjournals.onlinelibrary.wiley.com/doi/10.1002/cncr.33991)
- I added the citation modal so that we have a place to eventually provide citations in different formats: https://github.com/NCEAS/metacatui/issues/973

**Comment by dvirlar2** [comment]
That's awesome, Robyn! Does the dataset citation change based upon whether a user is viewing the condensed list or full list? For example, if someone's viewing the condensed list, would the "Cite this dataset" button truncate the author list to et al, and vice versa if they're looking at the expanded list? 

I don't think it's a big deal one way or the other, just curious :)

**Comment by robyngit** [comment]
Thanks @dvirlar2! No, the "Cite this dataset" list will always show the full author list, regardless of whether or not the landing page list is expanded or collapsed. Is that the behaviour you think users would expect?

**Comment by dvirlar2** [comment]
@robyngit I asked Bruce how many authors he was expecting to add on his dataset, and he said between 24-30. You had asked him for a number, so I wanted to let you know! Here's the [specific message](https://support.nceas.ucsb.edu/rt/Transaction/Display.html?id=601259) if you want it.

As for the expected behavior, I think it's what **_I_** would expect, but I don't think it's what most users would expect. I'll have to think on that a bit more.
