### ISSUE TITLE
Morpho referenceID causes EML validation error

### ISSUE THREAD

**Issue by jeanetteclark** [NCEAS/metacatui#295]
Upon editing a EML doc originally created in Morpho, the following error shows up when trying to edit that EML record using metacatUI

<img width="863" alt="screen shot 2017-10-06 at 1 55 35 pm" src="https://user-images.githubusercontent.com/24237074/31302811-9f4e8a4e-aab9-11e7-8209-0c9a50930468.png">

From Chris in Slack: "Ah, so if Morpho added in some `references`, we need to be sure they are still valid after editing a document.  So far, we’ve punted on creating them, but obviously we need to handle existing ones."

**Comment by amoeba** [comment]
Thanks for filing an issue. Could you possibly link an example document so I/we don't have to make one ourselves if you have one on hand?

**Comment by jeanetteclark** [comment]
[permafrost_metadata.txt](https://github.com/NCEAS/metacatui/files/1364153/permafrost_metadata.txt)

**Comment by csjx** [comment]
I think that at a minimum, at the end of `EML211.serialize()`, we need to call `DOM.getElementByTagName("references")`, and if the list size is greater than 0, for each in the list, we call `DOM.getElementById()`.  If the element exists, no problem, move on.  If it doesn't exist (i.e. we removed it in the editor), we'll need to remove the `references` element that it refers to.  Of course, this is tricky, because we also need to ensure the element content is added in where we remove the reference.  For instance, if there is a `<contact><references>blah</references></contact>`, we need to be sure we populate the contact with a `blah` party entry (or that another one exists). Otherwise, we might be producing invalid EML content.  So, something to think about.  Ultimately, we want to fully support `references` anywhere they are valid in EML. Handling references in general needs some thought.

**Comment by amoeba** [comment]
All good points. Handling references seems tricky. What does Morpho do on parse and serialize?

I think what you're suggesting is to de-reference references and sanitize out invalid references on parse which sounds overall to be the most workable thing.

**Comment by mbjones** [comment]
IIRC, Morpho does the following:

1) Creates a full eml-party entry whenever the user types info into the form 
2) Creates a reference entry whenever the user chooses an existing person from the dropdown (except when the person comes from another data set, in which case a full entry is created)
3) handles 'editing' of the reference entries by duplicating the referenced entry's fields and then allowing the user to edit that person
4) Keeps track of reference entries in a separate data structure, and ensures that ids and references are unique and not missing

**Comment by csjx** [comment]
I've implemented a stop-gap here, and have manually tested that the dereferenced XML is correct.
