### ISSUE TITLE
Make the table/package section and title field more obvious

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#308]
Here are some proposed changes:

- Increase the table height so it takes up more of the page real estate
- Add a large and obvious "Upload files" button and title to the table area, which would go away after the first file is uploaded.
- Add a title text field to the Overview section. The folder/metadata row will **not** be editable anymore, since it may be confusing to have the field editable in more than one place. However, anywhere in the editor the title is displayed (citation, folder table row, and title text input) will be synced and update anytime the model changes.

![more-obvious-table-header](https://user-images.githubusercontent.com/6643222/31682903-6d9d8890-b349-11e7-9404-3a906de4903a.png)

**Comment by csjx** [comment]
Thanks for the mockup @laurenwalker. I've been thinking this through a bit, and have a couple of comments.

First, I like the front-and-center nature of this button because 1) it promotes *data* upload (not just metadata), and 2) you can't miss it.  One concern is that we don't *require* data uploads for most repositories, so it might be a bit confusing.  Second, if we are going to use it, I vote for consistency with the other button and make this one `+ Add Files` also. I'd also suggest the text be say `Upload files for this dataset`, or something like that, so it doesn't seem quite as "required".

I think it's fine to have the title in the `Overview` area - let's give that a go. Ultimately, I think we should bind all three locations to the model for instant updates (citation, table row, and overview field), with both the table row and the overview filed editable.

So, my guess is that we may run into hurdles with social scientists that aren't uploading sensitive data, but let's see how it goes.

**Comment by csjx** [comment]
Oh, and I assume we will remove the button once one or more files have been uploaded, and we rely on the green `+ Add Files` button in the table there on out?

**Comment by laurenwalker** [comment]
Yeah, I feel like we may cause some confusion about data not necessarily being required, but we definitely want to encourage it as much as possible, so let's give it a go and see how people react.

Agreed, I was thinking the buttons should read consistently.

Yes, the big header and button will go away after the first file uploads.

**Comment by csjx** [comment]
After using the editor with the above fixes, I see a few issues that I think we need to address:
- [ ] While the centered `Add Files` button is good, it leaves too much white space and pushes the `Overview` form too far down. Raise the form up so we have the view is more like one-half`DataPackageView` and one-half `EML211View` rather than two-thirds and one-third.
- [ ] Adding the `Title` field to the `Overview` section is good, but disabling editing in the table is now inconsistent.  We are able to edit rows of the table for data file names still, but not metadata folders.  Make this more consistent by re-enabling the editable field, and ensure that both the folder row input and the title field input in the form listen to updates in the model and re-render appropriately.

I'm re-opening this bug, and would like to get thoughts on this.  

We're also looking for a small issue for @rushirajnenuji to tackle to gain familiarity with the code base, so I'm assigning it to him.

**Comment by laurenwalker** [comment]
The title field is now editable in the Overview section and the table cell.

We decided to wait on UX test feedback before editing the table height more.

**Comment by csjx** [comment]
Although we've closed this out, the proportions keep bothering me.  Here's a typical 1280x800 (larger than a 1024x768 standard screen):
![1280x800-75pct](https://user-images.githubusercontent.com/1437565/34189334-2a94fd18-e4f8-11e7-8b7d-4ab00354062e.png)
The metadata view is at the current 75% of the way down the viewport. I changed this to 40%:
![1280x800-40pct](https://user-images.githubusercontent.com/1437565/34189417-a65a133e-e4f8-11e7-9542-55cc0a7c3d2f.png)
I think the whitespace proportion is much better, and still highlights the `Add Files` button.  Let's go with this for now, but I'd like to revisit where we highlight the sections of the editor with a help tour instead.
