### ISSUE TITLE
Provenance view icon rendering

### ISSUE THREAD

**Issue by datadavev** [NCEAS/metacatui#326]
When viewing a provenance record in the UI, some icons are populated by retrieving the dataset into the browser to render the icon by downscaling the downloaded image.

This practice is not only very inefficient, but also inappropriately inflates download stats for the content.

These graphics downloaded through the resolve method should be replaced with appropriate static images until a solution more in line with widely adopted best practices is available.

**Comment by csjx** [comment]
Good point @datadavev. This kind of begs for a thumbnailing or preview server-side API call. Perhaps a `GET /object?preview=true&size=<height,width>` parameters? It would of course be formatId dependent, so the service would need to be extendable to make previews for future formats.  Needs some thought.

**Comment by mbjones** [comment]
I agree in principle with this issue, particularly the inflating download counts issue.  I have always wished we had browse graphics available as part of science metadata for all of our data objects.  But that has not really been standardized across metadata standards.  What are the best practices you refer to?  As far as I can tell, most metadata standards don't support browse graphics at all (EML, Dublin Core, FGDC, ...), and the ones that do, do it by convention, except for ISO which has the explicit [graphicOverview](http://www.datypic.com/sc/niem21/e-gmd_graphicOverview-1.html) section which contains an explicit `gmd:MD_BrowseGraphic` element.  Otherwise, I think its the wild west.

In practice, I'm not sure how we get MNs to provide these consistently enough for inclusion in a UI.

**Comment by laurenwalker** [comment]
We also already display images in the dataset landing pages outside of the prov charts (in the entity details section next to the file name, size, etc.) - a feature that users have really seemed to like - so the image files are already being retrieved for that page. There is no extra request being called for the prov chart images.

I think this issue reaches beyond just images, though. It would be great to have a `preview` API that retrieves smaller version of any object without increasing the download count. For example, we would like to have previews of data files, such as the first few lines of a data table. For images, the `preview` API could retrieve a thumbnail-size version.

**Comment by mbjones** [comment]
A `preview` API sounds like a great approach to me, as it would 1) give us a standard way of finding out if a browse graphic is available, and 2) normalize the different ways that people provide browse graphics in metadata and elsewhere so that it is readily accessible.  This might be done as part of the indexing process as we are parsing the metadata, which raises the question of whether it might not just be simpler to include a new field in SOLR to contain the preview content (maybe there already is one there).  

Also, if a browse graphic is not found in the metadata, but one could be easily be generated from the data (e.g., a thumbnail from image data, or the head rows of a table), should we consider adding this to the index processor's responsibility, or would it better be the purview of a different processor (because reading the data is much more time consuming than parsing metadata)?

**Comment by laurenwalker** [comment]
I'm going to go ahead and close the issue since we seem to agree that a `preview` API needs to be built to better support previewing objects, and since there is no extra download being made for images in the prov charts.
