### ISSUE TITLE
Discussion: How to handle nested packages for 2.0.0

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#334]
We have many nested packages in the ADC. We don't yet support them in the Editor. If a user opens a nested package now, edits it, and saves, then the parent resource map will not aggregate the newly created resource map. This is technically correct, but likely not what the user wants. The user most likely wants to edit a nested package and keep it nested inside its parent.

When we release 2.0.0 to the ADC, how should we handle these? Should we display a message to the user that nested packages are not supported yet? Should we let them edit and "break" their nesting, causing us to fix it?

**Comment by amoeba** [comment]
Hard decision! I'd put a vote in for the default behavior to be automatically re-linking the updated package to the parent. Kinda similar to renaming a folder on a filesystem (since we're going with the folder metaphor in this UI). 

Of course this would require the agent have access to update the parent resource map too 😱. If the user doesn't, I have no clue what to do besides break the linkage and notify the user with a (hopefully) useful error message (which will be hard to do).

**Comment by laurenwalker** [comment]
Chris and I decided that since nested packages primarily exist on the Arctic node, the Arctic bot will alert our data team to manually update the parent package. So our editor doesn't necessarily need to tell the user this at this point.

In the future, we do want to give the user the ability to nest their packages inside of one another. Created issue #406
