### ISSUE TITLE
Validation Errors on Incorrect Location Fields

### ISSUE THREAD

**Issue by ThomasThelen** [NCEAS/metacatui#351]
When a northeast coordinate is out of bounds, the corresponding southeast coordinate will have an error.

For example,

1. Enter a description and click out of the box
2. Enter a latitude that is out of bounds and click out of the box.
3. See an error associated with the other latitude.

This may be happening (if I understand correctly) because when we only provide one lat/long pair we set the other box corner to match it. The validation routine is probably grabbing the value, realizing that it's incorrect, and throwing the error.

**Comment by laurenwalker** [comment]
<img width="871" alt="screen shot 2018-06-21 at 11 48 52 am" src="https://user-images.githubusercontent.com/6643222/41730164-1a519088-7549-11e8-88ae-646b8479511b.png">

I tested this in Chrome and FF and didn't see this issue. I think it has already been fixed since there were some changes made to the locations validation since November.
