### ISSUE TITLE
Prov "View" dialog button refreshes entire page

### ISSUE THREAD

**Issue by csjx** [NCEAS/metacatui#365]
When you click on a prov icon to see the details of the relationship between the `Program` or`Data`, there is a `View` button that links to the location.  By default, clicking on this button seems to refresh the entire page.  this seems reasonable if it links to another package, however, within the same package, it should scroll on the page to the correct entity description. 

![prov-view-dialog](https://user-images.githubusercontent.com/1437565/32762579-61797492-c8b7-11e7-8d63-74f78c4975af.png)

**Comment by ThomasThelen** [comment]
We handle the `.click'` event on `preview` elements with custom redirection in `ProvChartView.previewData`. From `previewData`, we call the parent's `previewData` method. In our case, we're a child to `MetaDataView`. `MetaDataView.previewData` calls `appView.scrollto`, which causes the page to scroll.

 In the development versions where the full redirection occurs, this event is never actually firing when the "View <<" button is clicked. Instead, we `router.renderMetaData` -> `MetacatUI.appView.showView`, which will change the views (the refresh that we're getting). 


Based on that behavior, it seems sensible(?) to think that the "View <<" button isn't getting set to a `preview` class. I'm not completely sure where this occurs but I my guess is that we do it in `ProvStatementView.render`. We create elements with a `preview` class on lines 189 and 237 (search for `preview`). 

The problem however, probably isn't due to any code changes in ProvStatementView. A diff between the two files only shows one changed line, 

```
var predicates = _.difference(MetacatUI.appSearchModel.getProvFields(), this.skipPredicates);			
var predicates = _.difference(appSearchModel.getProvFields(), this.skipPredicates);
```
`CitationView.js` may be the culprit. In particular, changes were made to the creation of links around line 226.

**Comment by csjx** [comment]
It does look like the membership test is returning `false`, which is odd, and needs to be tracked down. But my thought is that we should also be adding the `preview` class to prov links out to objects in other packages in the `else` statement.  Am I missing something here.

Also, when you change this @ThomasThelen , please add code blocks `{...}` in the `if ... else` statements - while it can work without them, it's less readable and can actually lead to unexpected results in some circumstances (general FYI for everyone: see http://shop.oreilly.com/product/9780596806767.do).

**Comment by ThomasThelen** [comment]
It actually looks like `this.packageModel.get("memberIds")` is returning undefined. This can be traced back to the construction of the ProvChartView from the MetedataView where we pass in an `options.dataPackage` without any `memberId`s.

```
   var ProvChartView = Backbone.View.extend({
      initialize: function(options){
```

**Comment by laurenwalker** [comment]
I think this is an artifact of the refactoring we did for the prov charts. The prov charts used to be rendered using the soon-to-be-deprecated `PackageModel` but they are now rendered using the `DataPackage` collection. The `memberIds` attribute was a `PackageModel` attribute and I don't believe it exists or is needed in the new `DataPackage`.

@gothub - This is not critical, but we should not have models or collections triggering events that are related to display. It looks like `this.dataPackage` triggers a `redrawProvCharts` event. Instead, we should design events to reflect changes on the model or collection instead of designing them based on what we the event callback will do. That may mean the event simply needs a new name, but I haven't looked at the code closely enough to know if other design changes are needed.

**Comment by laurenwalker** [comment]
I'm going to close this since this works for me now.
