### ISSUE TITLE
Prov editor RDF updates fail

### ISSUE THREAD

**Issue by csjx** [NCEAS/metacatui#366]
While doing routine provenance edits using the prov icons, I noticed multiple calls to `MN.update()` failing with:
```
PUT https://dev.christopherjones.co/metacat/d1/mn/v2/object/undefined (400 Bad Request)
```
It seems like the `pid` is not being set correctly and is set as `undefined`. See:

![prov-put-errors](https://user-images.githubusercontent.com/1437565/32767623-73942aea-c8d1-11e7-9779-7e332f1788e6.png)

**Comment by gothub** [comment]
The prov editor is not catching the 'sucessSaving' or 'error' events triggered by DataPackage.save().
These need to be implemented for the prov edit save, so that it can ensure that the
resmap id is set correctly depending on the save status. Also, the 'save' button needs to 
be disabled until the status is returned, and a 'saving' status needs to be displayed like the
very cool status displayed by the metadata editor.

**Comment by gothub** [comment]
Prov editor save 'sucess' and 'error' callbacks implemented in these commits:
9a77f5ffb6862d7e8a9f406e7508ed85119b66d8
9ce6164c1a15803ac2abbebc2cffbbfb211de07b
dd579dd5a6ee64f478dcbda38a5e6e8f01ae2db7
