### ISSUE TITLE
EML validation error when adding two identical data files

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#382]
I opened an existing package in the Editor. I added a .csv file and watched it upload successfully. I then added the same file again, watched it upload successfully, and then clicked Submit. I got this validation error:

`Error inserting or updating document: urn:uuid:600bda0e-f840-4713-b53f-4b5290bdd05f since <?xml version="1.0"?><error>Error running xpath expression: //dateTimeDomain|//nonNumericDomain|//numericDomain|//access|//attributeList|//attribute|//constraint|//coverage|//temporalCoverage|//geographicCoverage|//taxonomicCoverage|//dataset|//dataSource|//dataTable|//otherEntity|//citation|//address|//conferenceLocation|//party|//originator|//creator|//contact|//publisher|//editor|//recipient|//performer|//institution|//metadataProvider|//associatedParty|//personnel|//physical|//connectionDefinition|//distribution|//researchProject|//project|//relatedProject|//software|//spatialRaster|//spatialReference|//spatialVector|//storedProcedure|//view|//protocol|//additionalMetadata : Error in xml document.  This EML document is not valid because the id urn-uuid-05cab5dd-c1a5-4d43-9fa7-cebea7cfdc27 occurs more than once.  IDs must be unique.</error>`

<img width="1615" alt="screen shot 2017-11-17 at 4 28 04 pm" src="https://user-images.githubusercontent.com/6643222/32969778-57028170-cbb4-11e7-936a-64f94d310557.png">

We should be preventing users from adding identical files by checking MD5 checksums before uploading.

**Comment by ThomasThelen** [comment]
We could link this with #275

**Comment by csjx** [comment]
Yes, we already generate the MD5, so I'll have a stab at this and only add it to the collection if it doesn't already exist.

**Comment by csjx** [comment]
This should be fixed now. I'll test in other browsers to but will close this ticket.  One note is that in order to respond to `fileLoadError` events on models that are not yet reference-able from the `EditorView`, I created an app-wide event bus called `MetacatUI.eventDispatcher`.  This sort of pattern is described in the Backbone documentation as a cross-component messaging solution and a way to organize event messages.  So this is the first use of it, but we can use it for other events if we want.
