### ISSUE TITLE
Fetch metadata quality info from metadig Kubernetes cluster

### ISSUE THREAD

**Issue by gothub** [NCEAS/metacatui#413]
Currently metadata quality info is obtained directly from the quality engine at
https://quality.nceas.ucsb.edu/quality (from MdqRunView.js). When quality info has been
added to the DataONE Solr index (for MNs), try to obtain the info from the Solr index
first, and if it is not available, get it from the quality engine. 

As part of the MetaDIG project, Metacat will be updated to initiate generation of quality
reports for newly uploaded metadata documents. In addition, a facility to generate reports
for existing metadata objects is being developed. An overview diagram is [here](https://github.com/NCEAS/metadig/blob/master/mdqengine/docs/metadig-generation-backlog.png).

**Comment by gothub** [comment]
@lauren @csjx the k8s cluster has been enabled for CORS and SSL. The `feature-quality-k8s` branch is now current and ready for testing against the k8s cluster. I haven't pre-generated quality reports yet for ADC, KNB, so you may see how the `MdqRunView` handles submitting a request to generate a quality report, vs just fetching an already generated one. The plan is to have metadig engine monitor KNB, ADC (and others) to detect newly added content and automatically generate quality reports, but that isn't implemented yet.

**Comment by laurenwalker** [comment]
Thanks Peter, I will test it out today.

**Comment by laurenwalker** [comment]
Some notes after testing:

#### 1. The quality report button does not display in the default theme

<img width="321" alt="screen shot 2018-08-22 at 4 00 27 pm" src="https://user-images.githubusercontent.com/6643222/44487535-84b09a80-a624-11e8-87c6-789844ac7428.png">

#### 2. The quality report button overlaps the container element in the KNB theme

<img width="401" alt="screen shot 2018-08-22 at 3 46 43 pm" src="https://user-images.githubusercontent.com/6643222/44486866-c50f1900-a622-11e8-94a4-28b535e272a1.png">

#### 3. The quality report button needs a left margin 
So that there is space between the Copy Citation and Quality Report button.

<img width="350" alt="screen shot 2018-08-22 at 3 49 38 pm" src="https://user-images.githubusercontent.com/6643222/44486990-13bcb300-a623-11e8-88d9-bfbf070a4ae3.png">

#### 3. Retrieving the quality report fails in the DataONE theme

MdqRunView gets the `objectServiceUrl` from the appModel. The DataONE theme should use the `resolveServiceUrl` instead. This causes the following error in the JS console:

`MdqRunView.js?v=2.1.0:195 Failed to load undefinedurn:uuid:0702cc63-4483-4af4-a218-531ccc59069f`

#### 4. Improve behavior when a report is generating
I think what we can do is after the POST to /run is sent, display a message that the report is being generated, and show the loading icon and a `Back to data package` link (or just use breadcrumbs). And then the view just keeps sending a GET to the /quality/runs/ URL to get the report every 5 seconds or so. As soon as it retrieves the report, it renders it. If it takes longer than X minutes, then we can display the error message and redirect back to the metadata view.

#### 5. JS error that kills the app
When I try to directly navigate to a /quality/pid URL, the content area of the page is blank and there is this JS error in the console:

<img width="1169" alt="screen shot 2018-08-22 at 3 58 41 pm" src="https://user-images.githubusercontent.com/6643222/44487503-6fd40700-a624-11e8-8ec3-11973dd81b0c.png">


#### 6. Lots of XHR requests being sent in the views instead of a model?
To follow the Model-View framework of Backbone/MetacatUI, we should do most of the HTTP requests in models, not views. Views should be limited as much as possible to just retrieving data from models and rendering the UI.
In fact, it looks like there is no Quality model at all? I would suggest making a Quality model and moving most of the "work" to the model. I know all this was probably done when the MDQ work was first done and isn't directly related to this recent work, but I see it as problematic design.

**Comment by gothub** [comment]
@laurenwalker thanks for the in-depth review. Great point about the lack of models to contain data, this really needs to happen. Is the current branch (feature-quality-k8s, branched from dev-2.1) still the right location for this work?

**Comment by gothub** [comment]
All these points are now addressed/resolved.

1. I would say that the quality report button should not appear in the default view, because it's not clear to me which quality suite should be run for this. Currently we have the `knb` and `arctic` suites, with the `dataone` suite still in development. For this reason, the `quality report` btn should not appear for either the `default` or the `dataone` themes. As soon as the `dataone` suite is ready, then the btn should be enabled. I'm leaving it on now, for testing purposes.

2. Fixed in commit 65e1a09b78551add57832f60adfdc8a21afe9c85

3. Fixed in 96673a9940a48b8a610aa8749f889bb27e858385

4. For both `3.` and `4`, only retrieving pre-generated quality reports should be implemented. This view should not request, then wait for a newly generated report. The metadig-engine/k8s is responsible for generating reports for all DataONE content, so the reports should be available, even for newly added content. Having the view request that a report is created, then waiting around for it is not a good solution, so I'm excising this from our code base now.

5. This is working for me, but I have to use the old style routes, i.e. `#quality/urn%3Auuid%3A4055c97c-62e2-43d3-bf78-4cc8d660f7bd`, so maybe someone could confirm that this is working?

6. Refactored for MV in commit 96673a9940a48b8a610aa8749f889bb27e858385
