### ISSUE TITLE
MetacatUI config flags for setting required/not required fields in dataset form

### ISSUE THREAD

**Issue by vchendrix** [NCEAS/metacatui#422]
It would be nice to have a way to simply flag the dataset edit required fields in the MetacatUI config.

**Comment by laurenwalker** [comment]
This is already a feature of MetacatUI. In the AppModel, there is an attribute called `emlEditorRequiredFields` which lists several fields that can be flagged as required/not required. Only certain fields are configurable.

```JS
/*
* emlEditorRequiredFields is a hash map of all the required fields in the EML Editor.
 * Any field set to true will prevent the user from saving the Editor until a value has been given
 */
emlEditorRequiredFields: {
	abstract: true,
	alternateIdentifier: false,
	funding: true,
	generalTaxonomicCoverage: false,
	geoCoverage: true,
	intellectualRights: true,
	keywordSets: false,
	methods: false,
	samplingDescription: false,
	studyExtentDescription: false,
	taxonCoverage: false,
	temporalCoverage: true,
	title: true
}
```

**Comment by mbjones** [comment]
Thanks, Lauren, those are good.  Lets review the list and be sure the fields that ESS-DIVE wants to turn on/off are present.  And that themes can easily mark which fields should be required beyond those that EML requires per se.  Re-opening issue to get this feedback from @vchendrix and @csjx .

**Comment by csjx** [comment]
I'd like us to think this through where we have properties for showing and/or requiring  sections, components, and fields. This would probably be best to do after we factor the configuration out into a new structure. (#281).
Something like
```javascript
{
  'sections' : {
    'overview' : {
        'show' : ['title', 'abstract', 'funding', 'publicationDate', '...'],
        'require' : ['title', 'abstract', 'funding', '...'],
        'order' : ['title', 'abstract', 'funding', '...'],
    },    
    'people' : {
        'show' : ['givenName', 'surName', 'email', 'organizationName', '...'],
        'require' : ['surName', 'email', 'organizationName', '...'],
        'order' : ['title', 'abstract', 'funding', '...'],
    },
    /* 'taxa' : { } // removed or commented out */   
  }
}
```
If we component-ize the fields in our templating system with Web Components or React we could take advantage of the `order` property above to dynamically populate the `View`. If a group of fields are turned into a component (like say an `address` component with subfields already layed out), then components could be part of the configuration. This would certainly take some design thought of course.  

A downfall of the above is that tricky structures like `eml-party/{individualName/surName | organizationName | positionName}` that are choices with required sub elements aren't expressed very easily in pure JSON syntax. The `order` part may also not be needed since you could just rearrange the template contents in a theme to get the desired order.

**Comment by vchendrix** [comment]
Closing this as it is not and issue right now.
