### ISSUE TITLE
Adding attribute information when editing adds otherEntities

### ISSUE THREAD

**Issue by jeanetteclark** [NCEAS/metacatui#436]
Adding attribute information results in the addition of otherEntities instead of editing the old otherEntities

see example here:
https://arcticdata.io/catalog/#view/urn:uuid:9431dcb1-2bac-407c-a19d-68cad599ca45

also, these should be dataTables with attributes and not otherEntities if we are getting picky

**Comment by laurenwalker** [comment]
I'm not sure exactly what happened here. Can you describe what steps you took to produce this error? Something like:

1.  Went to https://beta.arcticdata.io/catalog/#submit/urn:uuid:9431dcb1-2bac-407c-a19d-68cad599ca45
2. Clicked "Describe" for ??? (unknown) file which has a `otherEntity` entry in the EML
3. Added a new attribute
4. Clicked Submit, and saw that the editor added a new `otherEntity` rather than edited the existing `otherEntity`

**Comment by jeanetteclark** [comment]
Yes that is exactly what happened.

I added attribute information for 2 files, from this submission: https://beta.arcticdata.io/catalog/#view/arctic-data.14493.2

Expecting it to edit the existing otherEntities, and instead saw new otherEntities were added

**Comment by laurenwalker** [comment]
Ok, thanks!

**Comment by csjx** [comment]
I've added in support for editing existing `dataTable` entries, but we don't convert `otherEntity` entries to `dataTable` at the moment. When we add in parsing for delimited data files, we could address that issue.  Otherwise, I'll have a look at this issue to see why we're not editing the existing `otherEntity`.

**Comment by jeanetteclark** [comment]
No matter what the file is, the registry will describe it as an `otherEntity`. So there will never be an existing dataTable entry unless we make it in R. Not sure of the best way around this - you could try to guess dataTable or otherEntity based on the `formatID` - at the very least describing `text/csv` with `dataTable`

The new editor definitely does not seem to edit the existing `otherEntity`.

**Comment by laurenwalker** [comment]
I was able to recreate this bug using this dataset and figured out that the editor was not finding the `<otherEntity>` in the EML that corresponds to each file in the dataset. This is mainly because the old registry uses a different checksum algorithm than the editor (SHA1 vs MD5) and it does not add `fileName`s to the system metadata. So the editor creates a new `<otherEntity>` instead of updating the existing one.

The only way the editor can find the correct EML entity for registry uploads is to parse the identifier from the `ecogrid` URL found in the EML `distribution` element. I believe this should work for packages uploaded via the registry.

Thanks for reporting this bug @jeanetteclark as it likely effects many datasets in the ADC and KNB.
