### ISSUE TITLE
Prov relationship disappears after adding attributes in test editor

### ISSUE THREAD

**Issue by jagoldstein** [NCEAS/metacatui#478]
in Safari v 11.0 on macOS Sierra v 10.12.6:
I built provenance relationships with the UI on an existing package in test.arcticdata.io. Then I edited the metadata in the new editor, including adding attribute tables to 2 data objects, and re-submitted. The prov relationships that I did not add attribute tables to were retained, but the relationship between an output object (`urn:uuid:08a93184-0595-4040-a0d9-fd3ed4988e10`) that I added attributes to and its input (`urn:uuid:ba63de4e-b4d1-4527-83e1-671478bf2738`) disappeared from the metacatUI metadata view.

View the latest version of the package here:
https://test.arcticdata.io/#view/urn:uuid:8d31e6c7-111f-4cdc-a593-a3e5883e48b6

**Comment by emilyodean** [comment]
Adding to this - I am seeing the same behavior (Windows 7, Chrome) but all of my prov relationships are disappearing with package edits (updating attributes, updating package metadata ie abstract, adding new data files).

**Comment by rachelsun97** [comment]
I'm seeing the same behavior as @jagoldstein on Firefox v 58.0.2 (64-bit). I'm on the MacOS High Sierra version 10.13.2

**Comment by rachelsun97** [comment]
I'm seeing the same behavior as @jagoldstein on Firefox v 57.0.2 (32-bit) on Windows 7

**Comment by laurenwalker** [comment]
@jagoldstein @emilyodean @rachelsun97 - I have been trying to recreate this bug for a few hours now and I haven't been able to. Editing a dataset with prov relationships always works for me without messing up the prov charts.

Can you give me some more information on how I can recreate this myself? Is there a specific set of steps you took to find this bug? Is there only a certain type of metadata/dataset that this is happening to (e.g. only with datasets uploaded via R, only with new datasets created in the editor, only in datasets with more than 10 files, etc.)?

If you are able to recreate it yourself, screencapture gifs or screenshot images would be helpful to, e.g. to see before/correct and after/incorrect prov charts.

Any additional info you can provide would be so great! Thanks!

**Comment by areevesman** [comment]
I am getting the same issue on Firefox 54.0.1 on Windows 7. 

Tested on https://test.arcticdata.io/#view/urn:uuid:23347066-2c12-4822-b2fa-f3563bd61f45 

First added " tidbitDepths.txt " and " Levelogger_2010.txt " as sources of "ion_data.csv" with the prov editor, 
then hit the green submit button in the bottom right,
then hit the green edit button under the title,
then changed the title to "Central Arctic snow chemical composition, 2013 - 2014. NO PARA...PROV TEST" and hit the green submit button in the bottom right,
Finally, after hitting view dataset, the provenance relationships disappeared.

**Comment by areevesman** [comment]
Did the same thing and had the same error on Microsoft Edge 41.16299.248.0 on Windows 10

**Comment by laurenwalker** [comment]
So I've finally managed to track down what is causing this issue.

The SparQL queries that grab all the provenance relationships from the RDF are failing because the original RDF XML was serialized with the `https://cn.dataone.org...` prefix for identifiers, while the provenance editor serialized all the provenance relationships with the `https://cn-stage.test.dataone.org....` prefix (because test.arcticdata.io is in the stage environment).

When I tested this theory by replacing all the `stage` URL strings with production URL strings, the provenance charts rendered correctly.

I guess this parsing is _technically_ correct since two objects with the exact same identifier but in different CN environments are two separate obejcts. But, in this specific case where we are parsing a single resource map, we can assume objects are equivalent if they have the same identifier.

I think we can solve this bug by always serializing provenance relationships with the `cn.dataone.org` URLs, regardless of the MetacatUI settings/current environment.

We could also do some kind of string replacement on the RDF XML if there are more than one CN URLs detected, so that if a resource map with more than one CN URL is used, we can still parse it correctly.

**Comment by laurenwalker** [comment]
> I think we can solve this bug by always serializing provenance relationships with the cn.dataone.org URLs, regardless of the MetacatUI settings/current environment.

I decided to not do this. Serialization should follow the MetacatUI settings.

I did this instead:

> We could also do some kind of string replacement on the RDF XML if there are more than one CN URLs detected, so that if a resource map with more than one CN URL is used, we can still parse it correctly.

See commit referenced above.

**Comment by jagoldstein** [comment]
great job debugging this @laurenwalker !

**Comment by gothub** [comment]
I'd like to discuss this one a bit, apologies for being the `negative ned`. I think that any pid that is a package member should be written to the resource map with the CN for the environment that the package resides in, whether dev or production. We always know which pids are package members because they have the `<dcterms:identifier>` relationship for them. Any pids that are referenced that aren't package members should not have their resolve URLs changes (they could be in a prov relationship).

If there isn't another way to handle this, i.e. maybe converting the package pids to the new environment first before uploading them, then i'll close this issue again.

**Comment by laurenwalker** [comment]
I just tested this with this resourceMap: https://test.arcticdata.io/#view/urn:uuid:e9b972e1-6f1b-466e-bc5e-b0aba0bea4a4 and the CN resolve URLs were indeed changed because of the parse() code that changes all the resolve URLs. This is something that will need to be looked at. Because it's not a debilitating bug, I'm going to move it to 2.1.0.

**Comment by laurenwalker** [comment]
I have been fixing the loose ends to this issue along with #946. 

Note that the bug that caused resource map issues was fixed in the referenced commit above, over a year ago. This ticket is still open because of Peter's comments above.

**Comment by laurenwalker** [comment]
The most recent part of this bug was fixed in this specific chunk of code: https://github.com/NCEAS/metacatui/commit/a76494368d5ab446f38f915106257ed60a174855#r33997607

Now, `parse()` searches for all the CN URLs that exist in the resource map, and if there is more than one, it replaces them with the CN URL that is configured in that instance of MetacatUI.
