### ISSUE TITLE
Selecting a program in the prov chart adds the object to the data column, not the program column

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#503]
When I select a program via the "Add" button in the program column, it is added to the "Source" data column instead. See screencapture:

![prov-bug](https://user-images.githubusercontent.com/6643222/36808825-39a80fa6-1c94-11e8-8861-251f52b54a73.gif)

**Comment by laurenwalker** [comment]
Note: I checked the resource map that was serialized for the above example, and the `prov:wasGeneratedBy` relationship WAS serialized correctly. So this looks like a display issue only.

**Comment by gothub** [comment]
When items are added to a prov chart, the mime-type was used to determine whether they are 'data' or 'software' (DataONEObject.getType()) and they would be put into the appropriate column after being added. Now that any type of file can be selected as a program, we need to use another attribute to determine the 'type' of an item. Selecting an item as a 'program' is asserting that it is an instance of a ProvONE program, so that is now being set in `DataONEObject.prov_instanceOfClass`, to `provone:...#Program`.

Note that when a package is initially loaded, this attribute is set appropriately for all objects in prov relationships, hence when reloading, the prov would display correctly (in the above bug report).

@laurenwalker please review - I don't like to hard-code values like the `provone:...#Program`, but not sure where to define a constant for this.

Fixed in commit d609aaef2c4b035ee5def2ce9209003ac2fe082a

**Comment by laurenwalker** [comment]
Yeah, I can see how hard-coding in the `provone:...#Program` value could be problematic. We could make a function on the `DataONEObject` model called `setProvClass()` which could be called like `setProvClass("program")` to set the `prov_instanceOfClass` attribute.

**Comment by gothub** [comment]
Added `setProvClass()` in commit f3204d9360c0b5dc4c1331a069fb9045558c61af
