### ISSUE TITLE
add ability to reorder EMLParties

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacatui#521]
Creator order is preserved in the citation.  Need to be able to reorder creators easily.  Probably easiest with drag and drop on the rows with a drag handle.  But could also be done with Move up/Move down arrow butttons.

**Comment by vchendrix** [comment]
We just got this feature request from one of our users.

**Comment by laurenwalker** [comment]
Thanks, Val. I'm going to incorporate this feature into a release soon.

**Comment by laurenwalker** [comment]
To start, this feature should use a simple move up/down buttons, rather than drag-and-drop, since the EMLPartyView tends to be pretty tall. 

When designing the Portal Editor, we came up with a redesign of the EMLPartyView that would make drag-and-drop reordering much simpler. When we redesign the EMLPartyView, we can introduce drag-and-drop reordering at the same time. I created a new issue to contain that iterative enhancement: #1239

**Comment by amoeba** [comment]
Partial support pushed up in https://github.com/NCEAS/metacatui/commit/64ea4f67d18509f7f5f08ee23c037c0b56f46817. Will continue on this tomorrow AM. You can currently move a party down and it moves the party down the page and in the serialized EML doc. Want to find a nice way to display the move buttons and catch a few edge cases.

**Comment by amoeba** [comment]
Simple up down button implementation PR'd in #1334. 

Action shot:

![Kapture 2020-04-16 at 16 11 02](https://user-images.githubusercontent.com/563/79518193-ecd3a180-7ffc-11ea-8f9f-5138f19abdee.gif)
