### ISSUE TITLE
Obsoleted resource maps are shown in the download dropdown menu

### ISSUE THREAD

**Issue by vchendrix** [NCEAS/metacatui#537]
If a user creates data derivations, thus resulting in multple resource maps for a data package why would the user be allowed to download all the different resulting data packages and not the most current one?

## Multiple data package downloads
This is confusing.  It seems to me that the user should only be able to download the current data package.
![screen shot 2018-03-28 at 7 59 26 am](https://user-images.githubusercontent.com/1558129/38042634-be2fce0e-3269-11e8-9a6e-88200b350011.png)

**Comment by laurenwalker** [comment]
If a metadata document is in multiple resource maps that are **not** in the same obsolescence chain, that dropdown menu will appear so they can choose which package to download.

**Comment by vchendrix** [comment]
@laurenwalker What I am confused by is how does the user know which package they want? It just numbers them 1-3.

**Comment by laurenwalker** [comment]
Yeah, it's not a very informative interface. It has been a rare case in our repositories so we haven't dedicated the time to improving it.

**Comment by vchendrix** [comment]
The problem with this is that it is not clear which dataset is the current
one.  Is the last dataset the current one?

**Comment by vchendrix** [comment]
Based on my observations is looks like the resource maps are ordered up
upload data in ascending order. Is that correct?

**Comment by laurenwalker** [comment]
I believe they are ordered semi-arbitrarily based on the ordering received from the Solr index `resourceMap` field. They are all "current versions" in that none of the resource maps listed in that dropdown are obsoleted. It would make sense to order them by uploadDate and give them a better label than "Dataset 1", "Dataset 2", etc. Maybe we could show the citation for that package with a link to that package's MetadataView (#view).

**Comment by laurenwalker** [comment]
This is a symptom of having a metadata-centric system - the search on the DataCatalogView (#data) returns science metadata objects, so when a science metadata object is in more than one package/resource map, we don't really have a way of determining which package is the "current one" that the user is interested in downloading. So ultimately they need to choose which package they want to download. 

This has been a rare case in the DataONE world since science metadata documents are usually only in one dataset, so we haven't flushed out that dataset selection UI. Is this is a common occurrence in your repository?

**Comment by vchendrix** [comment]
From my tests using the Metacat UI derivations interface, I have confirmed that if I make an number of new derivations that the obsoleted resource maps show up in the index search results.

### Example of multiple derivations
This is an image taken from my localhost
![screen shot 2018-04-09 at 9 36 22 am](https://user-images.githubusercontent.com/1558129/38510338-9b97c54e-3bd9-11e8-9402-f390035d3bf0.png)

### Three obsoleted resourceMaps
```
This document returns four resource maps.  The first three in the list are obsoleted.  The last one is the current one.   Is this an issue with metacat or metacat UI.  It seems to me that either Metacat should not return the obsoleted resource maps OR the query in Metacat UI needs to filter out the obsoleted resource maps.

Search by ID: ess-dive-7d51d34fce3ce31-20180330T175118791
id=ess-dive-7d51d34fce3ce31-20180330T175118791 seriesId=
	formatType=METADATA
	title=FOOOOOOO
	obsoletes=
	obsoletedBy=
	resourceMap=['urn:uuid:6d8641e5-1882-4415-b4ee-b3052b8104bb', 
               'ess-dive-6a6fdd22f6b14d6-20180409T163002986', 
               'ess-dive-12f541e7f9f6116-20180409T163011714', 
               'ess-dive-edd489d38bd083b-20180409T163022313']

```

**Comment by laurenwalker** [comment]
@vchendrix - Ok, I see the issue you are talking about now. I'll create a separate ticket for the download dropdown menu UI improvements, since that is a different issue than this bug.

@gothub - It looks like Val found a bug in the prov editor where a new resource map is created and the old resource maps are not obsoleted in the system metadata. Let me know if you have the time to look into this and if not, I can.

**Comment by laurenwalker** [comment]
I created the above referenced [Metacat issue](https://github.com/NCEAS/metacat/issues/1258) to solve this bug, which is ultimately caused by a Solr index bug, not a MetacatUI bug. When the Solr index is fixed, the messed-up download buttons will resolve themselves. Will keep track of the progress there.

**Comment by laurenwalker** [comment]
After some discussion with the dev team, this may not be a Metacat issue after all. Reopening.

**Comment by laurenwalker** [comment]
I typed up a description of this bug and some solutions here: https://hackmd.io/kcnViO5ZSEGx1u2L7aonBw?view

Anyone feel free to share input if interested. I am leaning towards solution C in the hackpad above.

**Comment by vchendrix** [comment]
Option C seems good to me.

**Comment by laurenwalker** [comment]
I am going to move forward with Option C.

**Comment by laurenwalker** [comment]
This has been fixed by changing the `resultsItem` template. @vchendrix, just make sure that the ESS-DIVE theme `resultsItem.html` template merges these changes in. If you'd like me to do that, let me know!
