### ISSUE TITLE
Cannot read property 'length' of null in resultsItem.html template

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacatui#579]
Hey @laurenwalker and/or @csjx :

Just ran into this while talking with @rushirajnenuji about his [feature branch](https://github.com/NCEAS/metacatui/tree/feature-jsonld). When he pointed his local MetacatUI at DataONE instead of his local Metacat, he saw this on the DataCatalogView:

```
VM1259:31 Uncaught TypeError: Cannot read property 'length' of null
    at n.eval (eval at m.template (underscore.js:1454), <anonymous>:31:193)
    at n.c [as template] (underscore.js:1461)
    at n.render (SearchResultView.js?v=2.0.0RC5:43)
    at n.addOne (DataCatalogView.js?v=2.0.0RC5:2767)
    at n.renderAll (DataCatalogView.js?v=2.0.0RC5:2743)
    at n.addAll (DataCatalogView.js?v=2.0.0RC5:2686)
    at _ (backbone.js:370)
    at m (backbone.js:356)
    at f (backbone.js:155)
    at n.u.trigger (backbone.js:346)
```

The offending bit of code is:

https://github.com/NCEAS/metacatui/blob/403baccb4af080aecc33512c2c2a3962b080582c/src/js/themes/dataone/templates/resultsItem.html#L21-L26

This exception doesn't normally happen on DataONE because `southBoundCoord` is always undefined because it's not an attribute on the `SolrResult` model. This exception cropped up on this feature branch because @rushirajnenuji added this fields to support injecting JSON-LD into dataset landing pages.

Two questions:

- Is there a reason why the call to `geohash_9.length` was guarded behind `typeof southBoundCoord != undefined` instead of guarding it behind an inspection of `geohash_9` itself?
- The template (and other templates really) need to guard against `undefined` and `null`, ala `if (typeof x !== undefined && x != null) { ... }` or better to be truly safe from future changes like this. Could/should we do a quick survey of the code to check for other potential places this type of issue could crop up and fix them?

**Comment by csjx** [comment]
Good catch @rushirajnenuji @amoeba - Yes, we should be checking for `null` as well, since `typeof null` is `"object"`.  So yeah, we generally should be checking for this in the templates.  That said, we may be expecting a `null` in other parts of the code, so this may not be a total global change wherever we see a `typeof` comparison.  Also, we typically should be using the `===` and `!==` operators in these scenarios to check both type and equality, but that's a minor code best practice point.  

Regarding your first question - another good point - we should be checking the existence of a variable  like `geohash_9` before calling one of its methods or inspecting its attributes like `length`.  That's probably just an oversight, so thanks for catching it.

**Comment by amoeba** [comment]
Thanks @csjx. I agree on all points!
