### ISSUE TITLE
Editing EML attributes without physical sections

### ISSUE THREAD

**Issue by maier-m** [NCEAS/metacatui#617]
You can edit attributes on a data file that is in the resource map but not within an eml physical section. The eml will update with the attributes, but when you go back into the editor, those attributes will not show up in the editor when you click on the file to describe. Potentially need to build physical sections when they aren't present the first time?

Also, not expected to have many files without physicals once the editor is released

**Comment by laurenwalker** [comment]
This is the EML doc that was originally uploaded and had attributes added in the editor: https://beta.arcticdata.io/catalog/#view/arctic-data.14789.1

**Comment by laurenwalker** [comment]
I've attempted to reproduce this bug and I haven't been able to. 

When I edit [the same EML doc](https://arcticdata.io/metacat/d1/mn/v2/meta/arctic-data.14789.1) with the physical section, the attributes are successfully added and I can edit them later. 

When I edit [the next version of that EML doc](https://arcticdata.io/metacat/d1/mn/v2/meta/urn:uuid:067724d8-4b47-4571-a36d-a4508a43c536), which has the attributes and is missing the physical section, I can edit the attributes listed in the EML.

When I removed the data file from the package and added a new one, I was again able to add and later edit attributes (without a physical section, since it was all created in the editor).

This may be a bug caused by a rare order of events, so we can reopen this issue when/if we run into this error again.
