### ISSUE TITLE
Metadata View (/#view) does not load

### ISSUE THREAD

**Issue by vchendrix** [NCEAS/metacatui#622]
Metadata View (/#view) does not load. The javascript console has the following error.  It looks like ` views/ServiceTableView` file was not commited to the [repository](https://github.com/NCEAS/metacatui/tree/2.0.0-rc7/src/js/views).

+ **MetacatUI Version:** 2.0.0-rc7
+ **OS:** macOS High Sierra 10.13.4
+ **Browser:** Version 66.0.3359.139 (Official Build) (64-bit)

```javascript
Failed to load resource: the server responded with a status of 404 (Not Found)
require.js:138 Uncaught Error: Script error for: views/ServiceTableView
http://requirejs.org/docs/errors.html#scripterror
    at makeError (require.js:163)
    at HTMLScriptElement.onScriptError (require.js:1666)
```

![screen shot 2018-05-17 at 9 08 13 am](https://user-images.githubusercontent.com/1558129/40189690-e810ff08-59b1-11e8-9f9b-045fee3f13f4.png)

**Comment by laurenwalker** [comment]
Can you double-check that your `MetadataView.js` file was updated? We removed the `ServiceTableView` from the 2.0.0 RC 7 release since those tables are now rendered by the Metacat/DataONE view service. It looks like your MetadataView is still trying to load `ServiceTableView.js` as a required component.

**Comment by vchendrix** [comment]
Thanks. I will check that it was updated.
