### ISSUE TITLE
Add editor error tracking with Google Analytics

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#624]
I would love to see better error tracking in Metacat so we can track editor save errors, including saving the invalid EML document to the server for debugging later. But I think we could try tracking save errors via Google Analytics, which only requires a MetacatUI update, which could happen as early as today since it's so easy to set up.

We could also track JS errors throughout the app.

Here's a good article I found that demonstrates what I'm talking about: http://danwilkerson.com/google-analytics-error-tracking-guide/#javascripterrors

**Comment by amoeba** [comment]
Huge fan of this idea! I tend do this for various production apps I run and it's a total lifesaver (plus I sleep better). I hadn't seen the GA stuff you linked before so that was cool and new. 

For a lot of stuff I just user Papertrail so I get emails on stack traces, other kinds of errors, etc. That approach could be useful for tracking Metacat-side errors like when a user's submission fails validation and maybe they encounter a JS bug that prevents them from fixing it. If we dump the create call from Metacat to a log we could help them recover their work. What do you think about doing some of this too?

For JS errors, that GA solution sounds awesome. I also like [Sentry](https://sentry.io/) and [NewRelic](https://newrelic.com).

**Comment by laurenwalker** [comment]
Awesome, thanks for the info. GA doesn't seem like a perfect solution for tracking exceptions - it is a bit clunky and I can't quite get the report info I would like, but I think it's probably better than adding another library at this point. 

I would love to get an email and/or Slack bot that monitors the Metacat Tomcat logs and sends errors. And if we could log the actual EML content when there is an EML save or validation error, that would be great for both debugging and recovering metadata that users have spent time creating in the Editor. We could probably do the same for resource maps, too.

**Comment by amoeba** [comment]
> I would love to get an email and/or Slack bot that monitors the Metacat Tomcat logs and sends errors. 

Yeah something proactive would be nice! Let us know how the GA integration works.

**Comment by laurenwalker** [comment]
This was included in the 2.0.0 RC 8 release and is now installed on beta.arcticdata.io. To view the exceptions in Google Analytics, go to the "Exceptions" report I created, which looks like this:

<img width="913" alt="screen shot 2018-05-21 at 2 05 21 pm" src="https://user-images.githubusercontent.com/6643222/40322380-34516852-5d00-11e8-825b-0d8a5b8a8170.png">
