### ISSUE TITLE
EML save error: Entity referenced but not declared

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#659]
Full error message from GA:
`EML save error: Error inserting or updating document: urn:uuid:9d64e9f1-ddf5-49e4-b192-c20b2258f862 since <?xml version="1.0"?><error>Error running xpath expression: //dateTimeDomain|//nonNumericDomain|//numericDomain|//access|//attributeList|//attribute|//constraint|//coverage|//temporalCoverage|//geographicCoverage|//taxonomicCoverage|//dataset|//dataSource|//dataTable|//otherEntity|//citation|//address|//conferenceLocation|//party|//originator|//creator|//contact|//publisher|//editor|//recipient|//performer|//institution|//metadataProvider|//associatedParty|//personnel|//physical|//connectionDefinition|//distribution|//researchProject|//project|//relatedProject|//software|//spatialRaster|//spatialReference|//spatialVector|//storedProcedure|//view|//protocol|//additionalMetadata : The entity "nbsp" was referenced, but not declared.</error> | Id: urn:uuid:9d64e9f1-ddf5-49e4-b192-c20b2258f862 | v. 2.0.0RC12`

**Comment by laurenwalker** [comment]
This was an issue with HTML symbol codes, such as `&nbsp;`. It looks like the EML parser does not like any HTML code in the EML, so they are now removed during serialization.

**Comment by mbjones** [comment]
@lauren That is because `&` is one of the 5 reserved XML characters that always must be escaped. It has nothing to do with HTML per se.   Are you now escaping all text to ensure that all 5 reserved characters (`&`, `<`, `>`, `"`, and `'`) are properly escaped, and that entity encodings are properly handled?  See http://xml.silmaril.ie/specials.html

**Comment by mbjones** [comment]
@laurenwalker Looking more closely at your commit, is the fix you put in on [line 793](https://github.com/NCEAS/metacatui/blob/321c3b5554af4c3e55373b4107eec94dc46c3276/src/js/models/metadata/eml211/EML211.js#L793), where you replace the `&` with and empty string?  Its hard to see in the diff with all the whitespace changes in the file, so I could have missed the real change. If so, then I think that would be an issue too, because the ampersand would be deleted from the text altogether, which modifies the user's text, which we'd want to keep.  

We can encode a bare ampersand in the text by using `&amp;` in its place.  Because this gets recursive, I've found it best to not do this with regexes.  Most languages have a pre-built function for xml encoding strings, which in our case could probably be done with the Underscore `_escape(string)` function (see https://underscorejs.org/#escape).  And, nicely, that would get all 5 of the reserved XML characters. Sound ok?

**Comment by laurenwalker** [comment]
The issue seemed to be with any symbol code, like `&nbsp;`, `&foo;`, '&bar;`,  etc. Replacing ampersands with `&amp;` would still cause a validation error.

I think the ampersands themselves need to be escaped.

**Comment by mbjones** [comment]
Yes, exactly.  Things like `&nbsp;` are XML Entities, and are perfectly legal.  The reason the ampersand character itself is a reserved character in XML is specifically so that it can be used to mark the start of an XML Entity.  There are five defined XML Entities in XML, one for each of the reserved characters (`&amp;`, `&lt;`, `&gt`, `&quot;` and `&apos;`).  Others can be defined by the XML author in the DTD for the XML document using an ENTITY declaration.  Unfortunately, there is no way to define an ENTITY in xml schema.  So the ENTITY definition would have to occur at the top of the XML document in the DOCTYPE section after the PROLOG. We don't generally include that in our documents because we use XML Schema rather than DTD to define our validation rules.

`&nbsp` is not a pre-defined XML entity, but it is is a predefined ENTITY in HTML. Which is why you are probably finding it in the text from an HTML form. This difference between XML and HTML causes lots of problems.  But EML is XML, and those are the rules that need to be followed.  So, if you find an ENTITY reference in the text (like `&nbsp`) that is not one of the 5 pre-defined ones, then you'll need to escape it with its hex equivalent (e.g., `&#160;` for `&nbsp;`).  There are many HTML Entity lists, but here's a [hex-to-entity-name](https://www.obkb.com/dcljr/charstxt.html) mapping that seems fairly complete, although keep in mind that other custom HTML entities could be encountered too.  This complexity is generally why its best to use a good library with an XML `escape()` function.  Not sure if the Underscore function handles all it should, but worth a look.

**Comment by mbjones** [comment]
Oh, and we went through all of this with Morpho too, so there's some code in there that handles all of the escaping if you want to see examples in Java.  People got really frustrated with us when Morpho kept creating not well-formed XML.  Any XML editor needs to deal properly with reserved characters and XML Entities.

**Comment by laurenwalker** [comment]
That makes sense. I will improve the code to better handle EML entities outside of the 5 defined entities and will escape all the reserved characters.
