### ISSUE TITLE
Support EML 2.2.0 in the Editor

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#694]
Support the specific EML 2.2.0 new features in the editor through this issue.  Let's discuss which features should come first.  I will open a separate issue for serializing EML 2.2.0, which is simpler and shouldn't require all of the new features to be added.

**Comment by mbjones** [comment]
While technically true, the support is mostly incomplete still. I could be wrong on some of these, but I think we still don't have full support for funding info changes (#1403), structured license info (#1404), markdown (#1935), the various citation changes (literatureCited, usageCitation) and editing [bibtex](https://eml.ecoinformatics.org/whats-new-in-eml-2-2-0.html#bibtex-support), the new [data paper sections](https://eml.ecoinformatics.org/whats-new-in-eml-2-2-0.html#data-paper-support) (introduction, getting started, acknowledgements, etc.), and other new [EML 2.2. features](https://eml.ecoinformatics.org/whats-new-in-eml-2-2-0.html). So, while I guess its ok to close this because we have the `EML 2.2 support` label, do keep in mind that we only have a bare minimum supported currently and it would be good if we could support all of that (e.g., for data papers).

**Comment by laurenwalker** [comment]
@mbjones - Yes, there are still lots of other EML 2.2.0 features to support. I closed this issue since it is not particularly helpful during roadmapping since it is so broad. We should use the other issues to track scopable work. We could use this issue as an Epic if we want to group those features together.
