### ISSUE TITLE
Complete the People section of the editor

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#7]
- [x] Display the People section in the editor form, with a space for creators, PIs, metadata providers, etc.
- [x] Update the EMLParty models when the UI is changed
- [x] Update or add the people in the EML doc during serialize()
- [x] Parse the EML parties from the EML doc

**Comment by leinfelder** [comment]
Added to EMLParty.updateDOM() with what I think you guys were wanting - someone mind taking a look for sanity check before I continue with other models?

**Comment by csjx** [comment]
Heya @leinfelder - Thanks for this.  I had a look at `updateDOM()` and I think the pattern is looking great so far. In each of these models, we have to handle 1) a completely empty DOM, 2) a partially complete DOM, and 3) a fully complete DOM.  Really (2) and (3) can be treated as the same.
When the DOM is completely empty, the `remove()`, then `find()` then `append()` pattern should work, although I'm not sure if you'd get an `UncaughtType Error` if the result of the `find()` is an empty array or `undefined`, so that's something to test.
When the DOM is partially complete, I'm wondering if the `append()` will work as expected.  In fleshing out the `DataONEObject.serializeSysMeta()`, I found that I needed to look for existing elements and use the `after()` call to insert my node after it's sibling so the order is correct.  Also, if your target node isn't in the DOM - for instance for `postalCode`:
```javascript
$(objectDOM).find("address").find("postalCode").text(this.get("address").postalCode);
```
I think this will fail.  I think you'd need to call `createElement()` first, and insert that element in after it's known sibling.  If its immediate previous sibling is optional and missing, you have to find the next known previous sibling before you can call `after()`.
Anyway, this is what I was kind of rambling about in our last meeting, so let me know if I'm not making myself clear, or if it's perfectly clear, but just wrong =).

**Comment by laurenwalker** [comment]
I've fixed a bunch of issues I was having with EMLParty.updateDOM(). I'm going to start on the rest of this section now (the UI, mainly, and further testing of parsing and serialization).

**Comment by laurenwalker** [comment]
![image](https://cloud.githubusercontent.com/assets/6643222/22794979/f30c304a-eec2-11e6-9ad6-f19a2db02fbd.png)

The People section is coming along... all the parties are parsed from the EML doc and displayed in the Editor.

**Comment by amoeba** [comment]
This is looking really good!

**Comment by laurenwalker** [comment]
The People section is now a lot shorter to scroll through. All empty party types are consolidated into one form with a dropdown menu to select the new type. When a new type is selected, that party gets added to the page and the dropdown menu is reset for adding another new party type.

![screen shot 2017-02-24 at 12 08 13 pm](https://cloud.githubusercontent.com/assets/6643222/23313032/f6ab9628-fa89-11e6-8283-5e84073d8d81.png)


Besides some small tasks like adding validation help, formatting the phone and fax numbers, verifying ORCIDs, etc., this section is done.
