### ISSUE TITLE
Make MetacatUI.root more tolerant (Was: New routing refactor changes do not work for me)

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#713]
Not sure if I am not configuring my MetacatUI properly or if this is a bug in the code. I set up my local Apache with the `FallbackResource` config and it is working. The `MetacatUI.root` variable is set correctly. The AppView is initialized, which renders the navbar. But the specified view (e.g. `DataCatalogView`) does not render, so the page is just blank white space.

This is happening in the DataONE and default themes (other themes not tested yet)

<img width="1270" alt="screen shot 2018-07-26 at 1 32 26 pm" src="https://user-images.githubusercontent.com/6643222/43278528-6142ca38-90d9-11e8-8bee-63aaaa0e2d2b.png">

**Comment by laurenwalker** [comment]
And there are no errors in the console.

**Comment by laurenwalker** [comment]
When I click a link in the navbar, the routing works and the view is rendered. It is only on the initial app load where the page is blank.

**Comment by amoeba** [comment]
Thanks for kicking the tires. Sorry I hadn't gotten to installation instructions just yet. Still fixing some remaining bugs in the implementation.

For a top-level deployment, you should:

- Ensure index.html has an absolute reference to loader.js `/loader.js` ala
```
<script id="loader" type="text/javascript" src="/loader.js?v=2.0.0" 
```
- Ensure Apache has `FallbackResource /index.html`
- Ensure `loader.js` has `MetacatUI.root = "/"`

I don't yet like the amount of config needed to support this feature and top-level and non-top-level deployments so I hope there's some room for improvement yet.

If things are still not working after all that, I'd ensure your cache is cleared and if _that_ fails, look in the Network tab for me and look at the requests for the core MetacatUI JS files like AppModel and paste the URLs the browser is requesting for them. If those requests are to the wrong URL, the `FallbackResource` directive set in the Apache config will return index.html for them instead of a 404.

**Comment by amoeba** [comment]
After talking on Slack, it sounds like @laurenwalker was setting these config params to full URLs rather than paths which is something that totally makes sense to do and something I think the code should be tolerant of. e.g., http://metacatui.localhost or http://metacatui.localhost/subdir.

I'm going to rename this Issue and make it into a task to make the code more tolerant.

**Comment by laurenwalker** [comment]
I am working on this now

**Comment by amoeba** [comment]
Nice, thanks @laurenwalker !

**Comment by laurenwalker** [comment]
I pushed a fix for this. If @amoeba and @rushirajnenuji could just make sure it works for their setup too, that would be helpful.

**Comment by amoeba** [comment]
Will do, thanks @laurenwalker

**Comment by amoeba** [comment]
LGTM, thanks @laurenwalker.
