### ISSUE TITLE
Deploy new editor on the KNB

### ISSUE THREAD

**Issue by jeanetteclark** [NCEAS/metacatui#724]
I want to push that we make deploying the new editor on the KNB a priority. To my knowledge the only missing piece is the intellectual rights section. You probably don't need convincing but in case you do...

- There are lots of users out there still using Morpho. They are having a lot of issues (see ecoinfo RT queue) and I think many of these issues would be absolved with the new editor, since Morpho is not compatible with the old editor

- SASAP is winding down, and right now it would be impossible for anyone to update their dataset after the project ends. All SASAP metadata is incompatible with the currently deployed version of the web editor.

- The KNB is going to become the home for a considerable amount of Alaska Department of Fish and Game data that has been trapped within the department for a long time. This dataset definitely would benefit from entity/attribute level metadata and I'd like to make it as easy as possible for them to create good metadata for it

- Personally, I really would like to be able to use the prov editor on production. Updating prov through the prov editor is much easier than doing it through R since you don't have to flip back and forth between the metadata document and your console.

**Comment by laurenwalker** [comment]
This is a priority for the devteam, too, and we haven't forgotten about it, and are working on it.

We are currently finishing up [MetacatUI 2.1.0](https://github.com/NCEAS/metacatui/milestone/10) which has three big new features (JSON-LD, Dataset metrics/Making Data Count, and non-hash paths for making pages indexable by Google). There are deadlines fast approaching (and already past) for these features to be in production in DataONE, so that is our immediate priority.

Next is [MetacatUI 2.2.0](https://github.com/NCEAS/metacatui/milestone/35) which will be the version that gets deployed in production for Arctic Data Center and the KNB. You can see the issue regarding the privacy feature here: https://github.com/NCEAS/metacatui/issues/343.

Also, we have a MetacatUI milestone document checked into the repository (just as of yesterday) that shows our schedule for these and other releases: https://github.com/NCEAS/metacatui/blob/master/docs/Milestones.md. We plan on keeping that updated so that these schedules are easier for the whole team to be informed of the MetacatUI schedules.

Hope that info helps.

**Comment by jeanetteclark** [comment]
Thanks Lauren - Matt asked me to create an issue for this I think partially because he didn't see where this fell in the deployment timeline, but it sounds like it is there

**Comment by laurenwalker** [comment]
Yeah, it is not written explicitly in the milestone document - it probably should be.

**Comment by csjx** [comment]
Quick comment on this: the missing portion of the editor needed for KNB deployment is the `Sharing` section that allows researchers to set individual, group, and public `read/write/change permission` permissions.

**Comment by laurenwalker** [comment]
I updated the milestone document with the deployment details.

@csjx  - I don't think that is the case. We only need to replace the KNB functionality at first. The KNB right now only has a public/private toggle for each data file in the package. That is all we need to replace in the new editor before deploying to production. Having more specific sharing options can come later down the line and shouldn't stop a production release.

**Comment by csjx** [comment]
Yes, thanks @laurenwalker - I should have mentioned that we have planned to phase this in, with `public/read` access being the first phase.
