### ISSUE TITLE
Archived data packages don't show citation or allow data download

### ISSUE THREAD

**Issue by vchendrix** [NCEAS/metacatui#744]
I have tried archiving two different ways

1.  All of the data objects (METADATA, RESOURCE, DATA) in the data package are marked as archived (See https://data.ess-dive.lbl.gov/#view/doi:10.15485/1463701)
2. Only the METADATA object is archived when a data package is marked as archived 
![screen shot 2018-08-24 at 1 48 59 pm](https://user-images.githubusercontent.com/1558129/44607225-8608d100-a7a4-11e8-8e5a-803c227fd28b.png)

Both of these produce the same metadata view that has no citation and no data is available to be downloaded.  

If a user has a doi and wants to see the old data package, they should be able to access it.

Which is the proper way to archive data packages above? (Choice 1 or 2 above)

**Comment by mbjones** [comment]
This is a long-standing discussion about what it means to 'archive' a data package, and related to changes in how Metacat traditionally handled it 'archive' operation  versus how DataONE handles it in terms of search indexing.  I think this requires a broader discussion about what we (collectively) think the right behavior should be, and fixes to both the DataONE indexer and Metacat/GMN to make it work that way.  Maybe grist for discussion at the DataONE All Hands Meeting (although there may not be time).

**Comment by nahf** [comment]
I hope we can discuss at the AHM.

The treatment of archived data is an important aspect to the design of index processing, as removing archived records is a processing complication that would be great to side-step.   The complication is because documents are cross-referenced with other indexed items, and so archiving - that is, removing - one document triggers introspection and possible updates to other records,  along with the need for managing locks to avoid race conditions.

**Comment by amoeba** [comment]
(Circling back on this). We had a fruitful discussion about this in our CI breakout at the DataONE AHM last week. I'll try to summarize them here but I'd appreciate if others would chime in.

I think we all agreed that @vchendrix's use case is very important:

> If a user has a doi and wants to see the old data package, they should be able to access it.
 
We think "archival" should essentially mean,

- From an API perspective: Hide archived records in Solr queries by default, show them when explicitly requested
- From a MetacatUI perspective: Only hide archived content in search listings, show elsewhere

The current sense of "archival" is to hide the record from the all queries regardless and this disrupts the notion of DataONE being good for long-term archival (note that overloaded use of the word here).

**What does this mean?**

- The default behavior of the Solr index will be to not show archived content unless explicitly requested by the client. i.e., by passing an `archived:true` query parameter.
- Archived content will no longer be absent from the Solr index but will not be returned by default, which means _this is a non-breaking change for clients_.
- While client tools will _not_ break and will see the same results as they would've prior to this change but they _will_ need updating in order to properly show archived content where appropriate (see below) such as showing dataset landing pages for archived content.

**Where will you see archived content in MetacatUI?**

Simply: When you know the identifier. This is similar to the common web idiom of "only users with the link can view".

As for MetacatUI, this means:

- /catalog: **Does not** show archived metadata records (current behavior)
- /view: **Does** show archived/non-archived Data Packages (new behavior)
- /profile: **Does not** show archived/non-archived Data Packages (current behavior)

Note: I think we were learning towards /profile showing archived content by default but I think it's more consistent to not show archived content in /profile since it's a public listing just like /catalog. I'm open to more discussion on this.

**Why can't we just fall back to the ORE when we run into archived content?**

Displaying a human-readable view of a dataset requires the search index. First, to route from the metadata PID the user is requesting a view of to the Data Pakcage(s) it's contained in and, second, to bulk query for the members of the Data Packages and their associated metdata (file names, sizes, etc).

**What does ESS-DIVE need to do to archive content?**

After these changes, the minimum thing to do to archive a dataset would be to archive _just_ the metadata record. The best thing, as far as the API goes, would be to archive the metadata, the ORE, and all aggregated objects. The above page in your screenshot would show the actual package and not just a broken page.

**How do I really hide my content?**

After this change, the only option is either:

1. Remove public read or other permissions from the object(s) in question
2. Administratively delete objects

I think this is a bit hacky to leave these as the only two options.

**Steps forward**

- Look into how to achieve this with Solr (hide archived content by default)
- Update DataONE indexing stack to reflect this change
- Update MetacatUI so dataset landing pages like in the screenshot at the top work with the new indexing behavior
- Update DataONE API docs

**Comment by csjx** [comment]
@amoeba I really like your summary here - thanks for writing it up.  A few of things came up for me:
1) We **chose** to render metadata views in MetacatUI from the Solr search index largely because of the expediency of it. It's a one-stop-shop for system metadata info, science metadata info (albeit a subset), and package relationship info (indexed resource map statements).  As we do in the metadata editor, we may consider what it takes to render the `MetadataView` directly from the ORE, scimeta, and sysmeta documents.  As it is, we rely on a transformed science metadata HTML result from the `MNView.getView()` API endpoint, which gets enhanced by package info and sysmeta info. I think we may consider a more direct approach like this. Needs discussion.
2) By changing the content of the Solr search index and adding archived content into it, and hiding archived content using Solr queries in MetacatUI is effective for this particular web app, but it means that all other clients also need to be modified such that they also exclude archived content when searching, but allowing it when displaying.  The Java (therefore Matlab), Python, and R libraries would need to do this.  So, in that sense, buy adding archived content back into the search index, are we somewhat betraying our definition of "archived" (i.e. not searchable) because we are then relying on client conventions to exclude those in searches?  I feel like the underlying reason this is coming up is because MetacatUI uses the search index for display (and perhaps shouldn't).
3) One possible thought: if we decide that client-side display directly from the sysmeta, scimeta, and ORE docs is too heavy, what about indexing archived content into an *archived_search* Solr core, where the schema is set such that no fields are searchable, they are only readable as a direct query when you know the `pid`? I haven't thought this through much, but it might be a way to still make the content easily fetched, but completely separate from the main *search* core, and it avoids a lot of client-side parsing of XML content.  I'm not advocating for this per se, but we might explore it a bit, and decide if it's a worthwhile route to pursue.
4) Administratively deleting objects, I would venture to say,  isn't a viable solution based on our DataONE policies for preserving content. It's really just there for DCMA-style takedown orders, and is only supported with MN and CN admin subjects.  Removing `public/read` is a currently supported means of hiding content, and yes, I agree that it's pretty hacky.  I've got nada for solutions here unfortunately. :slightly_frowning_face:
Again, thanks for the summary - it's really helpful.

**Comment by amoeba** [comment]
Thanks for taking a look! Some thoughts...

> As we do in the metadata editor, we may consider what it takes to render the MetadataView directly from the ORE, scimeta, and sysmeta documents.

This isn't practical for datasets over a certain size and I don't think the metadata editor needs to do this. Rendering a landing page for a dataset with even ten files would take far too long for most users: Just grabbing and parsing an ORE takes 2-5 seconds. Having to also fetch the sysmeta would take 1-2 seconds per sysmeta record which blows things way out of the realm of reasonableness as far as page load time is concerned. We need to use an index of some fashion and that index needs to be at the DataONE CN level.

> But it means that all other clients also need to be modified such that they also exclude archived content when searching, but allowing it when displaying. 

That's not my understanding. The proposal is to not returned archived content by default which makes this a non-breaking change from an API perspective so no client tools would need an update and we wouldn't have to issue a new API version. Am I missing something here?

Re: (3), I think that's addressed by my above.

**Comment by laurenwalker** [comment]
Metacat 2.10.0 now includes the ability to search for archived content in the index. MetacatUI 2.5.0 will take advantage of this feature and display citation and resource map information about archived datasets.

![archived](https://user-images.githubusercontent.com/6643222/49611031-47231380-f96e-11e8-8bf0-76fdef9febd4.png)
