### ISSUE TITLE
Metric Modal navigation links

### ISSUE THREAD

**Issue by rushirajnenuji** [NCEAS/metacatui#760]
- Keep the metric buttons enabled that have `0` download counts. We need to display the modal even if the metric counts are `0`. 
  - Add the navigation links in the modal footer for all the metric modals. 

- Add display text if no data available for time series chart.

**Comment by robyngit** [comment]
Hey @rushirajnenuji, I think I have a solution to the second item in this To Do list. I've changed the `metricsChartView` so that it displays text instead of a chart when there's no download/view data.  It was straightforward to add this feature to the chart view, but if it's better to do this in the modal view, just let me know and I'll undo the change. Otherwise, I'll include this in my next pull request.

**Comment by rushirajnenuji** [comment]
Hi @robyngit - I liked your idea. I merged your recent [PR](https://github.com/NCEAS/metacatui/pull/766) and the design looks good. I'm thinking to extend this for the use-cases where we don't have citations available.

**Comment by rushirajnenuji** [comment]
Implemented CIrcular Queue navigation for the Metric Modals.

Saved with the commit: https://github.com/NCEAS/metacatui/commit/417fdb982629ac7898d35521a7111bd7dd90d0fd
