### ISSUE TITLE
Accessing files for authenticatedUser  access policy

### ISSUE THREAD

**Issue by vchendrix** [NCEAS/metacatui#793]
ESS-DIVE requires users to authenticate before downloading data files for a data package.  The ideal application of access policy for published data packages would be as follows:

 * METADATA - public/read
 * RESOURCE - public/read
 * DATA - authenticatedUser/read

This would allow anonymous users to view metadata but require them to login to download any data.  However, this is problematic in MetacatUI as the data table would be empty  unless the user is logged in. 

I have discussed a proposed  enhancment to Metacat UI with @csjx to give a message to the the user in the data table telling them to login for inaccessible files (metadata and resource map must be public).  
* When a user is not logged in let the user know that there are X files for download but they need to login first.
* If file is authenticatedUser then they see files when logged in
* If they are logged in but still don’t have access to the file, say this is a private file. This should be possible by looking at the resource map)

**Comment by laurenwalker** [comment]
Currently we are not parsing the resource map to render the package table on the dataset landing pages (the package contents are determined via a Solr query instead), however, I think we perhaps should start doing this. The editor draws a similar package table by parsing the resource map, so I think we could reuse those views. 

This would need some performance testing since the system metadata of each file would be retrieved in order to render the table. For large packages, that can take some time.

We could also make this a configurable feature in MetacatUI that applies to all packages in the repo, but I think like the idea of doing it on per-package basis better. Open to thoughts.

**Comment by vchendrix** [comment]
This is no longer an issue for ESS-DIVE
