### ISSUE TITLE
Metadata editor set the authoritativeMN to 'null' on my local Metacat

### ISSUE THREAD

**Issue by taojing2002** [NCEAS/metacatui#797]
When I use the online metadata editor to create packages, I found the authoritativeMN on the system metadata of every object is 'null' (not the null value, literally the value is the four letters - null). Since the authoritativeMN was set, Metacat.create method wouldn't change it even it is wrong. I guess this because my local Metacat wasn't registered on any cn environment. 

Version 2.2.2

**Comment by laurenwalker** [comment]
This was likely happening because either your Metacat wasn't registered in the CN environment that was configured in MetacatUI. You can get around this issue by configuring the `nodeId` property in the MetacatUI AppModel.

We have talked before about getting the member node document from the MN API when the member node is not found in the node list taken from the CN API. That would solve this bug when MetacatUI is not configured correctly.

**Comment by csjx** [comment]
While I understand that this is a configuration issue, I feel like we should still be checking the `authoritativeMemberNode` and `originMemberNode` when we serialize the system metadata.  Sending system metadata documents with `null` values is guaranteed to be wrong, and will only cause issues down the road with `MN.update()` calls. Checking for `urn:node:` in each value is pretty quick, and if this is fresh system metadata, we should not be serializing those fields at all (the MN is responsible for it).

We can address this in #570 rather than re-open this ticket.
