### ISSUE TITLE
Bring back user rights access at the bottom?

### ISSUE THREAD

**Issue by brunj7** [NCEAS/metacatui#800]
I am missing to see at the bottom of the page (for packages I have edit access to)  who else has also edit access to the package. That was pretty convenient. Can we have it back ?

**Comment by laurenwalker** [comment]
You mean the access policy that shows up at the bottom of the data set landing pages?

**Comment by brunj7** [comment]
yes, at the very bottom of the data package page, you used to be able to see users, ldpap groups who had access to the package. Not sure if it was/is working with the ORCID login...

I guess if I try to summarize better my point is:  it would be great for packages you have edit access to, to be able to see from the webinterface who else has also specific access rights on the package, mainly who else could edit it.

**Comment by laurenwalker** [comment]
This is a feature we want to work into the editor. Users who have edit access to a dataset will be able to view and (sometimes) edit the access policy of the contents of that dataset.

The access policy that used to get displayed at the bottom of the page on the dataset landing pages was taken directly from the EML. We are not longer serializing access policies to the EML since we now control access policies via the system metadata.

But displaying that info inside the editor I think will be very helpful. See #344
