### ISSUE TITLE
Serialized resource maps contain entries of failed upload members

### ISSUE THREAD

**Issue by csjx** [NCEAS/metacatui#812]
We've seen issues where a researcher has added data files to a package, but the three attempts to upload them have failed.  A subsequent call to `DataPackage.save()` is serializing the resource map and uploading it, but it includes the failed members.  On the server side, indexing of the resource map fails because its listed members have not indexed (they do not exist on the server). This causes the `MetadataView` landing page to render a `PackageTable` with no data rows, making it look like they "disappeared". An example of this is https://knb.ecoinformatics.org/view/urn:uuid:79288f2b-f15c-4b21-a302-8256842da55e. 

When serializing resource maps, we need to, at a minimum, check the `DataONEObject.uploadStatus` field to insure it is `c` (complete) and not `e` (error) or really any other value (`p`, `l`) if we do not already. We may consider making a REST call to `MNRead.describe()` for each aggregated `pid` before serialization, but that seems a bit heavy.  Whatever we do, we ought to do this checking in `DataPackage.validate()` which will get called prior to `DataPackage.save()`.

**Comment by mbjones** [comment]
Seems like there are two approaches to this.  You've addressed the first, which is to make MetacatUI more robust as to what it sends, and to be sure its building good resource maps.  Which is great, and we should do that.  

In addition, we should be making the indexer more robust so that it doesn't just die out when a component is missing from a resource map -- it seems to me that we should be able to skip missing items from a resource map, and when that item shows up later and is indexed, we can update the index fields as needed.  I don't see this in the [indexer refactor](https://redmine.dataone.org/issues/8702), but maybe its in another ticket.

**Comment by csjx** [comment]
@mbjones - The plan is to support sparse resource maps and index them no matter if their members have already been indexed, so that's a good long term goal. Currently though, the indexer will in fact add the resource map identifier back on to the index queue, effectively waiting for its members to be indexed.  The problem in this scenario is that those members will never be uploaded, because of the errors on the client side.  So better client-side handling of errors is the solution here.  Also, as we incorporate the client-side draft feature, we'll be able to maintain a reference to the on-disk `File` object, and could theoretically attempt an upload later under the same minted identifier, but ultimately we should never be including failed upload identifiers in the resource maps or the science metadata for that matter.  Both of these get serialized after data files are uploaded, so we have the status values readily available, we just need to check them before serialization.
