### ISSUE TITLE
Broken obsolescence chain

### ISSUE THREAD

**Issue by vchendrix** [NCEAS/metacatui#845]
We had an issue last week where we noticed that a data package had lost all of its data files.  When we inspected the obsolesence chain we noticed that it had been broken.

https://data.ess-dive.lbl.gov/#view/ess-dive-e21bac2c1bb0597-20181119T180158729993. This is a private data package.

What I think happend was that the Metadata editor somehow lost the original resource map and created a new one thus breaking the chain.  We fixed it by doing the following:

- fix the resource map obsolescence chain: updated the obsoletedBy and obsoletes attributes of the resource maps that were broken ( See 4 and 5 below)
- add the files back to the data package from the previous correct version: created a new resource map with the existing files ( See 1 below).

Search by ID: ess-dive-1225149bbc279a1-20181121T130932677780
---------------------------------------------------------------------

```
1. id=ess-dive-1225149bbc279a1-20181121T130932677780 seriesId=
	obsoletes=ess-dive-8641f5eaa8d9f91-20181119T180207332604
	obsoletedBy=
	dateModified=2018-11-21T21:14:35.685Z

2. id=ess-dive-8641f5eaa8d9f91-20181119T180207332604 seriesId=
	obsoletes=ess-dive-64b2414c36e90f3-20181117T211632329
	obsoletedBy=ess-dive-1225149bbc279a1-20181121T130932677780
	dateModified=2018-11-21T21:14:35.512Z

3. id=ess-dive-64b2414c36e90f3-20181117T211632329 seriesId=
	obsoletes=urn:uuid:259baa34-be6f-40c9-9b3a-f2221c246377
	obsoletedBy=ess-dive-8641f5eaa8d9f91-20181119T180207332604
	dateModified=2018-11-20T02:02:13.578Z

4. id=urn:uuid:259baa34-be6f-40c9-9b3a-f2221c246377 seriesId=
	obsoletes=ess-dive-30f82337761ad2f-20181115T215503562
	obsoletedBy=ess-dive-64b2414c36e90f3-20181117T211632329
	dateModified=2018-11-21T20:58:00.741Z

5. id=ess-dive-30f82337761ad2f-20181115T215503562 seriesId=
	obsoletes=ess-dive-b4f1043a2294617-20181115T214744144
	obsoletedBy=urn:uuid:259baa34-be6f-40c9-9b3a-f2221c246377
	dateModified=2018-11-21T20:59:33.235Z

6. id=ess-dive-b4f1043a2294617-20181115T214744144 seriesId=
	obsoletes=ess-dive-b95ed1aae6926a1-20181115T214611666
	obsoletedBy=ess-dive-30f82337761ad2f-20181115T215503562
	dateModified=2018-11-15T21:55:04.695Z
```

**Comment by laurenwalker** [comment]
I've seen this happen before when the resource map is not indexed, so the editor creates a new one. This could be either from an indexing delay or an error that prevented the old resource map from being indexed at all. 

Either way, it would be great if the UI could handle these situations better. We could possibly add a feature that allows the user to "replace" another package with the one currently open in the editor. (i.e. fixing the broken chain).

**Comment by vchendrix** [comment]
We just had it happen again with another user.  I had to peform the same fix.  It could be an indexing  delay issue.  The data package was eventually indexed. It looks like the two versions of the data package were saved within a minute of each other.  The fix should not require the user to do anything.  

I just reproduced this issue:

1. The user makes some metadata changes to a data package that has data files. 
2. Clicks save. 
3. View the Data Package 
4. Click edit again before the previous data package was index.
5. Make metadata changes
6. Click save

Now the obsolescence chain is broken.
 
I would say this is a critical issue.

**Comment by csjx** [comment]
I agree that MetacatUI needs to handle this more gracefully.  That said, I think we also need to look into why the indexing of the first resource map is not effectively instantaneous.

On the MetacatUI side, we probably can keep the original `DataPackage` instance until there is a known indexed update to it.  Otherwise we will continue to overwrite it with a fresh `DataPackage` instance (if I understand this correctly).

**Comment by laurenwalker** [comment]
Agreed, I think we should just keep the DataPackage collection and it's models in memory until the application is closed.

**Comment by vchendrix** [comment]
> On the MetacatUI side, we probably can keep the original DataPackage instance until there is a known indexed update to it. Otherwise we will continue to overwrite it with a fresh DataPackage instance (if I understand this correctly).

@csjx  This seems correct to me.  If this works with the steps for reproducing the issue I detailed above. We should be good.  However, I wonder if clicking "View Data Package" would clear the memory.

**Comment by laurenwalker** [comment]
I just pushed a fix for this issue. It applies to this scenario that was mentioned above:

> I just reproduced this issue:
> 
> - The user makes some metadata changes to a data package that has data files.
> - Clicks save.
> - View the Data Package
> - Click edit again before the previous data package was index.
> - Make metadata changes
> - Click save
> 
> Now the obsolescence chain is broken.

If the `MetacatUI.rootDataPackage` collection contains metadata object that is being edited, then the editor will use that collection instead of creating a new empty one. This will keep obsolescence chains intact when a resource map fails to index for whatever reason. If the resource map did successfully index, then the Editor will function as it always has.

Note that if the user opens up another package in the Editor, the `MetacatUI.rootDataPackage` will be replaced, and this won't work anymore. Or if the user refreshes the page or navigates away from the page. In the future, our draft feature should be able to cover more cases like this.
