### ISSUE TITLE
Update unordered categories definition

### ISSUE THREAD

**Issue by dmullen17** [NCEAS/metacatui#865]
I've noticed that a majority of submitters don't realize that the following category applies when they use integers to represent their categories.

```
Unordered categories
The values of this attribute are unordered categories or classifications. Example: male or female
```

I think it would be a good idea to expand on this a bit more so they make the connection.  For instance: 

``` 
The values of this attribute are unordered categories or classifications.  Example: 1. male or female 2. 1 or 2 where 1 and 2 represent groups.
```
I'm sure the above could be improved on, just an example

**Comment by amoeba** [comment]
Having a go at this now.

**Comment by amoeba** [comment]
Came up with a change to both unordered and ordered:

<img width="578" alt="Screen Shot 2020-04-17 at 11 05 45 AM" src="https://user-images.githubusercontent.com/563/79605024-a719e600-809b-11ea-8848-6cffb65dea98.png">

Open to minor tweaks anyone has. Feel free to commit them up top of comment here. Otherwise, ready for merge.

**Comment by laurenwalker** [comment]
Looks good, my minor suggestion is to put an "or" before "site codes":

`Examples: Sex (Male, Female), or site codes coded as letters or numbers (e.g., 1, 2, 3 or A, B, C).`

**Comment by amoeba** [comment]
Sounds good, thanks! Updated in https://github.com/NCEAS/metacatui/commit/d10bd2e3162418f7a684b87665969158436db9c4.

I'll go ahead and close this now. If anyone has any further suggestions please comment here and we can reopen and address them.
