### ISSUE TITLE
Render citations and a reference list in the MarkdownView and project home tab

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#870]

**Comment by jkibele** [comment]
This issue should reference #820

**Comment by jkibele** [comment]
After the dev call we just had, the following plan has emerged for citations:

- [ ] Project Model parsing will read BibTex from `literatureCited` and write it into the `overview:markdown` element of the project so that...
- [ ] Our custom showdown extension can access the BibTex and stick it in a citation.js `Cite` object so that it can:
    - [ ] Write out an html bibliography
    - [ ] Replace markdown inline citations (e.g., `[@jones_2001]`) with styled inline citations linked to the html bibliography

**Comment by mbjones** [comment]
This sounds good, but one slight tweak: be prepared to collate citations from multiple locations in the document.  For the project pages, they might all be in one element, but in EML they are allowed to be in different elements, and we'll want to be able to create an integrated bibliography from them.  For guidance, note in EML how many places use the `CitationType` complex type to get an idea of where they might be represented.

**Comment by jkibele** [comment]
I think the approach I outlined above should actually work pretty well in that regard. In the current case we're going to have the project model inject the bibliography into the markdown. This should (hopefully) leave us open to either rendering markdown that already has the bibliography in it, or having some other model (or set of models) inject it.

**Comment by jkibele** [comment]
This is just a note (mostly so that I can pick this back up after the 3 day weekend):

After @amoeba pointed out the inline bib [format used in RMarkdown](https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html), I thought it might be nice to use that format when we injected the bib into the markdown. ...and this could be particularly useful down the road in that we could potentially let people export pure markdown from their Rmd files and use that as their project markdown...

However, it seems that the YAML header bibliography stuff in RMarkdown comes from Pandoc and does not seem to be implemented in any client side JS markdown (including showdown and citation.js). So, short of extending citation.js, I don't think we can stick the bib in the YAML header. Darn.

I think I'm just going to stick it into the end of the markdown in BibTex wrapped in some kind of ad hoc custom markdown tag that will then get removed before it's displayed.
