### ISSUE TITLE
Consistently place remove 'X' icons

### ISSUE THREAD

**Issue by csjx** [NCEAS/metacatui#88]
I'm seeing the red `X` icon to remove entries in various metadata subsections on the left in the 20px gutter, whereas the package table has them on the right, inside each row.  My preference is that we move them all to the right, and place them inside the entry.  But, let's discuss @amoeba @laurenwalker

**Comment by amoeba** [comment]
I can get down with this. Remove icons on the left may be easier for the user to spot but I think there may be visual techniques we could use to make it obvious. This issue kinda interacts with another thing we may or may not need to deal with which is that of clearing a set of elements (clear the fields in a taxonomy table, reset all geo coordinates, clear a person's details).

What about something like this, where the remove and clear buttons are off to the right and are shown when hovering over the section that will be removed or cleared? https://codepen.io/petridish/full/LyRgaV/ Sorry for the ugly.

**Comment by laurenwalker** [comment]
I'm fine moving them to the right, but with the note that it is super low priority, in my opinion.

I originally designed the remove icons so that they only displayed when you hover over that section, but during a dev team call we got negative feedback about it. It might require some further discussion with the devs and our data team UX testers before changing it.

**Comment by csjx** [comment]
Yes, low priority, definitely.

**Comment by laurenwalker** [comment]
I moved them all to the right side of the page. There are still some issues with certain remove buttons not working and a couple sections are missing remove buttons. Will create new tickets for those.
