### ISSUE TITLE
Change how identifiers and file names are created in the editor

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#915]
-We will now use resource_map_{UUID-for-RDF} for resource map pids
- New resource map filenames will be: `resource_map_{UUID-for-RDF}.rdf.xml` 
- Data, metadata, and resource map file names will have all non [A-Za-z0-9] replaced with _ (underscore)

**Comment by dmullen17** [comment]
This is already the `pid` naming convention (except for replacing non alpha-numerics with _) in `arcticdatautils::create_resource_map`.  Do we want those `fileName` fields set as `resource_map_resource_map_urn_uuid_54dc84cd-d232-4531-9561-153139278c73.rdf.xml`?

**Comment by jagoldstein** [comment]
I believe we want the PID in the above comment to have a `fileName` of either:
`resource_map_urn_uuid_54dc84cd-d232-4531-9561-153139278c73.rdf.xml`, OR
`resource_map_urn_uuid_54dc84cd_d232_4531_9561_153139278c73.rdf.xml`.
Do we want to replace all the hyphens`-` in UUIDs with underscores`_`? @laurenwalker @csjx 

This PID `resource_map_doi:10.18739/A2R20RW3W` would have `fileName` `resource_map_doi_10_18739_A2R20RW3W.rdf.xml`.

The other question seems to be: What qualifies as `{UUID-for-RDF}` in Lauren's original comment?; does `{UUID-for-RDF}` refer to
`resource_map_urn_uuid_54dc84cd-d232-4531-9561-153139278c73`,
`urn_uuid_54dc84cd-d232-4531-9561-153139278c73`, OR
`54dc84cd-d232-4531-9561-153139278c73`?

**Comment by laurenwalker** [comment]
`{UUID-for-RDF}` is refering to the UUID only - e.g. `urn_uuid_54dc84cd-d232-4531-9561-153139278c73`

We discussed replacing all non a-zA-z0-9 characters with underscores, which includes hyphens. If we want to keep the hyphens, let me know.

**Comment by jagoldstein** [comment]
Ok, good clarification. So the PID 
`resource_map_urn:uuid:54dc84cd-d232-4531-9561-153139278c73` would be set to a `fileName` of `resource_map_urn_uuid_54dc84cd_d232_4531_9561_153139278c73.rdf.xml` (hyphens, along with all other non-alphanumeric characters in the UUID, replaced with underscores). Does this make sense to you @dmullen17 ?

**Comment by laurenwalker** [comment]
I just pushed the changes for this. Here are some file name and id examples, just to be clear on the new format:

### Resource Map
Id: `resource_map_urn:uuid:0134818a-6e59-4141-9b69-d5843d06c731`
Filename: `resource_map_urn_uuid_0134818a_6e59_4141_9b69_d5843d06c731.rdf.xml`

### Metadata
Id: `urn:uuid:771ca3b7-02ff-44d8-92b5-6702a6953d5f`
Filename: `Water_isotope_data_collected_from_precipitation__snow__and_rivers__Thule_Air_Force_Base__Northwest_Greenland__2011_2013.xml`

### Data
Id: `urn:uuid:b571728e-47aa-41b6-bb84-419eaeb917e9`
Filename: `ThuleAFB_ppt_isotopes.csv`

**Comment by jagoldstein** [comment]
@laurenwalker these resmap and data object `fileName` naming strategies make sense to me, but I don't recall discussing the naming convention you mentioned for EMLs and don't see it in our [meeting notes](https://docs.google.com/document/d/1WbB_GRCo-hivgBintHxr-aMwEpecMZhu-YSDngiLRtM/edit#) from the call with @csjx .

My understanding was that we were still going with `science_metadata.xml` for all metadata `fileName`s, but of course it would be nice for different EMLs to download from the MN with different names in order to discern them from one another on the local end. My concern with the naming convention you outline here is that many of those files names will be _really_ long.

**Comment by laurenwalker** [comment]
I'm not keen on the idea of naming all the metadata files `science_metadata.xml`. We have done that in the past and have gotten complaints about it, because the files names are so generic.

We've been using the title as the science metadata file name since the new editor was created, and there haven't been any issues with it so far. But I understand that the titles can get very long, so we could cut if off after a certain number of characters.

We could also do something like:

`science_metadata_{title}.xml`

I moved this from 2.5.1 to 2.6.0 since there is still some discussion and I want to get 2.5.1 out today.

**Comment by jagoldstein** [comment]
That's fine with me to push this back to a later Milestone. I _don't_ think this convention (`science_metadata_{title}.xml`) is a good choice because it would just make the names even longer.


As an example, here is an EML `fileName` that was just assigned by the editor:
`Arctic Oases - How does the delayed release of winter discharge from aufeis affect the ecosystem structure and function of rivers_  Stream Data.xml` (https://arcticdata.io/catalog/view/urn:uuid:35bfb72b-cd0e-4b95-a85c-8ee4b65a4ac4).
Widening my local finder window to the full width of my large monitor still does not allow for the display of the entire file name, unless I hide other columns (like "Date Modified").

It sounds like we all agree that we should replace the spaces with underscores, but I also vote for truncating the `fileName`s after a certain number of characters.

**Comment by laurenwalker** [comment]
Agreed, that's why I suggested we truncate after a certain number of characters...

**Comment by laurenwalker** [comment]
We decided to change the metadata file names to use the title only, replacing all nonalphanumeric characters with underscores, and truncating after the first word break before 50 characters. Multiple underscores in a row would be consolidated down to one underscore.

So the title example of:
`Arctic Oases - How does the delayed release of winter discharge from aufeis affect the ecosystem structure and function of rivers Stream Data` 

would have a filename of:

`Arctic_Oases_How_does_the_delayed_release_of.xml`

**Comment by laurenwalker** [comment]
This is now complete. Just to reiterate, here is the new file naming convention:

### Resource Map
Id: `resource_map_urn:uuid:0134818a-6e59-4141-9b69-d5843d06c731`
Filename: `resource_map_urn_uuid_0134818a_6e59_4141_9b69_d5843d06c731.rdf.xml`

### Metadata
Id: `urn:uuid:771ca3b7-02ff-44d8-92b5-6702a6953d5f`
Filename: `Water_isotope_data_collected_from_precipitation.xml`

### Data
Id: `urn:uuid:b571728e-47aa-41b6-bb84-419eaeb917e9`
Filename: `ThuleAFB_ppt_isotopes.csv`
