### ISSUE TITLE
updating dataset after using "publish with DOI" button results in mangled resource map

### ISSUE THREAD

**Issue by jeanetteclark** [NCEAS/metacatui#946]
To recreate this issue:
1) create data package using the editor with one data file
2) publish with a DOI using the button
3) edit package using editor, adding one file

I recreated this on `dev`, the ORE pid is `urn:uuid:bdb289b8-243c-4297-8ec9-badce5ab5bab` and here's a [link to the resulting landing page](https://dev.nceas.ucsb.edu/view/urn:uuid:708b1d93-0570-487f-ba20-ba333f8dc826)

relevant @csjx comments from slack

> I downloaded the resource map, and yeah, it looks mangled at first glance.  It defines two aggregations rather than one.  Perhaps we’re mishandling the ore in the DOI process on Metacat.
> 
> ...we are somehow not removing the old aggregation correctly

**Comment by jeanetteclark** [comment]
hey @laurenwalker just wondering if there was an update on this ticket. I continue to experience issues with the button, and we recently lost a user because of the issues he experienced (https://support.nceas.ucsb.edu/rt/Ticket/Display.html?id=18685)

**Comment by laurenwalker** [comment]
Yep, this one was a bit of a doozy so I've been working on it and I'm actually about to commit the fix for it within the next hour or so.

**Comment by mbjones** [comment]
@laurenwalker could you please summarize what the problem was and how you fixed it on this bug (and others)?  Thanks.

**Comment by laurenwalker** [comment]
**Summary of the issue:**

The resource map serialization in MetacatUI was failing sometimes, particularly after the DOI publish action, because the code was assuming that all of the object identifiers in the RDF statements were written as: CN v2 resolve URL + encoded object id (e.g. https://cn.dataone.org/cn/v2/resolve/urn%3Auuid%3Ad5a1fcd5-6bc7-447e-ba42-9bde3031aef6). This was causing a break in the RDF graph because nodes are not interpreted as equal if they do not pass a simple string comparison. (i.e. https://cn.dataone.org/cn/v2/resolve/urn%3Auuid%3Ad5a1fcd5-6bc7-447e-ba42-9bde3031aef6 does not equal https://cn.dataone.org/cn/v2/resolve/urn:uuid:d5a1fcd5-6bc7-447e-ba42-9bde3031aef6)

When Metacat publishes a metadata with a DOI, it was creating statements in the RDF using the following syntax, which MetacatUI was not accounting for:
- Using v1 instead of v2 URLs
- Using unencoded pids in the URLs
- Using literals as the object of the `isAggregatedBy` statements. (e.g. `    <ore:isAggregatedBy rdf:datatype="http://www.w3.org/2001/XMLSchema#anyURI">https://cn-stage-2.test.dataone.org/cn/v1/resolve/urn:uuid:087f9a8d-2095-427c-b66f-3bf71218fc92#aggregation</ore:isAggregatedBy>` instead of `<ore:isAggregatedBy rdf:resouce="https://cn-stage-2.test.dataone.org/cn/v1/resolve/urn:uuid:087f9a8d-2095-427c-b66f-3bf71218fc92#aggregation" />`)

**Summary of the fix:**
During resource map serialization, MetacatUI will now search for the above ways that RDF statements can exist in the resource map. It doesn't just assume that all statements are written as CN v2 resolve URL + encoded pid.

I added comments to the commit above specific chunks of code, if you want a finder detail breakdown:
https://github.com/NCEAS/metacatui/commit/a76494368d5ab446f38f915106257ed60a174855

**Comment by jeanetteclark** [comment]
Thanks for the summary @laurenwalker that does sound like a doozy.

Do you think it would be worth looking into the R code to try and mitigate the issue when a package is copied from one `cn` to another and the base URL is not changed in the resource map? I imagine this is how most packages are copied from one node to another.

**Comment by laurenwalker** [comment]
It shouldn't cause any issues in the MetacatUI editor. Now, the URLs will get changed to the current environment after any update in the MetacatUI editor.
