### ISSUE TITLE
Add a Save function to the Project Editor

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#986]
The Save button is always displayed. (After the MVP, we will display it only when a change has been made to the model.) When clicked, ProjectModel.save() is executed so that the project document is saved to the server.

If the ProjectModel save fails, an error message is displayed.

If the ProjectModel save succeeds, a success message is displayed.

**Comment by rushirajnenuji** [comment]
Tested the `save()` functionality - and it is working as expected. Performed the following tests:

- [x] saving a single project multiple times in a row.
- [x] saving DataONE objects / EML from Metadata editor.
- [x] updating filename and saving a data file.

One interesting observation was having too many REST calls being made from MetacatUI to both `SOLR` and `DataONE Metrics Service API`. Lauren has filed a seperate issue for that here: https://github.com/NCEAS/metacatui/issues/1063.

As far as this issue is concerned - we've added the DataONE Project saving funcitonality and tested it on local and development servers. We can now close this ticket.
